#include <asm/irq.h>

#define USE_POWER_MANAGEMENT
//#define USE_GPIO_CPU_MEASURE
#define USE_NO_CLOCK
#define USE_FW_DOWNLOAD

#define USE_DMA
#define USE_CMD3_TEST

#define USE_IRQ_ID_RESPONSE_COMPLETION
//#define USE_IRQ_ID_FIFO_READ_READY
//#define USE_IRQ_ID_FIFO_WRITE_READY
//#define USE_IRQ_ID_RW_ACCESS_COMPLETION

#define HOST_SDIO_IRQ_NUM INT_MMC_SDIO1





