/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef NME_CONNECTION_MANAGER_XML_TYPES_H
#define NME_CONNECTION_MANAGER_XML_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum unifi_ConnMgrDisconnectReason
{
    unifi_ConnMgrDisconnectReasonCancelled                  = 0x00,
    unifi_ConnMgrDisconnectReasonSecurityAborted            = 0x01
} unifi_ConnMgrDisconnectReason;











#ifdef __cplusplus
}
#endif

#endif /* NME_CONNECTION_MANAGER_XML_TYPES_H */
