
obj-$(CONFIG_SND_SUN4I_SOC_I2S_INTERFACE) += sun4i-i2s.o
obj-$(CONFIG_SND_SUN4I_SOC_I2S_INTERFACE) += sun4i-codecchip.o
obj-$(CONFIG_SND_SUN4I_SOC_I2S_INTERFACE) += codecchip.o
obj-$(CONFIG_SND_SUN4I_SOC_I2S_INTERFACE) += sun4i-pcm.o
 
