/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#include "fsm/fsm_internal.h"
#include "sme_top_level_fsm/sme_top_level_fsm.h"

/*lint -e725 */

#define INIT_EVENT_HEADER(event,evtid) \
    event->common.id = evtid; \
    event->common.destination = 0; \
    event->common.sender_ = FSM_ENV


void pal_ctrl_activate_cfm(FsmContext* context,
                           void* appHandle,
                           CsrUint16 numDataBlocks)
{
    PalCtrlActivateCfm_Evt* evt = (PalCtrlActivateCfm_Evt*)CsrPmalloc(sizeof(PalCtrlActivateCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_ACTIVATE_CFM_ID);

    evt->appHandle = appHandle;
    evt->numDataBlocks = numDataBlocks;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_deactivate_cfm(FsmContext* context,
                             void* appHandle)
{
    PalCtrlDeactivateCfm_Evt* evt = (PalCtrlDeactivateCfm_Evt*)CsrPmalloc(sizeof(PalCtrlDeactivateCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_DEACTIVATE_CFM_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_early_link_loss_ind(FsmContext* context,
                                  void* appHandle,
                                  CsrUint8 physicalLinkHandle)
{
    PalCtrlEarlyLinkLossInd_Evt* evt = (PalCtrlEarlyLinkLossInd_Evt*)CsrPmalloc(sizeof(PalCtrlEarlyLinkLossInd_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_EARLY_LINK_LOSS_IND_ID);

    evt->appHandle = appHandle;
    evt->physicalLinkHandle = physicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_event_mask_set_cfm(FsmContext* context,
                                 void* appHandle)
{
    PalCtrlEventMaskSetCfm_Evt* evt = (PalCtrlEventMaskSetCfm_Evt*)CsrPmalloc(sizeof(PalCtrlEventMaskSetCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_EVENT_MASK_SET_CFM_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_failed_contact_counter_read_cfm(FsmContext* context,
                                              void* appHandle,
                                              CsrUint16 logicalLinkHandle,
                                              CsrUint16 failedContactCounter)
{
    PalCtrlFailedContactCounterReadCfm_Evt* evt = (PalCtrlFailedContactCounterReadCfm_Evt*)CsrPmalloc(sizeof(PalCtrlFailedContactCounterReadCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_FAILED_CONTACT_COUNTER_READ_CFM_ID);

    evt->appHandle = appHandle;
    evt->logicalLinkHandle = logicalLinkHandle;
    evt->failedContactCounter = failedContactCounter;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_failed_contact_counter_reset_cfm(FsmContext* context,
                                               void* appHandle,
                                               CsrUint16 logicalLinkHandle)
{
    PalCtrlFailedContactCounterResetCfm_Evt* evt = (PalCtrlFailedContactCounterResetCfm_Evt*)CsrPmalloc(sizeof(PalCtrlFailedContactCounterResetCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_FAILED_CONTACT_COUNTER_RESET_CFM_ID);

    evt->appHandle = appHandle;
    evt->logicalLinkHandle = logicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_create_cfm(FsmContext* context,
                              void* appHandle,
                              CsrUint16 logicalLinkHandle)
{
    PalCtrlLinkCreateCfm_Evt* evt = (PalCtrlLinkCreateCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkCreateCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_CREATE_CFM_ID);

    evt->appHandle = appHandle;
    evt->logicalLinkHandle = logicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_delete_cfm(FsmContext* context,
                              void* appHandle,
                              CsrUint16 logicalLinkHandle,
                              CsrUint8 physicalLinkHandle)
{
    PalCtrlLinkDeleteCfm_Evt* evt = (PalCtrlLinkDeleteCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkDeleteCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_DELETE_CFM_ID);

    evt->appHandle = appHandle;
    evt->logicalLinkHandle = logicalLinkHandle;
    evt->physicalLinkHandle = physicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_flush_cfm(FsmContext* context,
                             void* appHandle,
                             CsrUint16 logicalLinkHandle,
                             CsrBool flushOccured)
{
    PalCtrlLinkFlushCfm_Evt* evt = (PalCtrlLinkFlushCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkFlushCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_FLUSH_CFM_ID);

    evt->appHandle = appHandle;
    evt->logicalLinkHandle = logicalLinkHandle;
    evt->flushOccured = flushOccured;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_lost_ind(FsmContext* context,
                            void* appHandle,
                            CsrUint8 physicalLinkHandle)
{
    PalCtrlLinkLostInd_Evt* evt = (PalCtrlLinkLostInd_Evt*)CsrPmalloc(sizeof(PalCtrlLinkLostInd_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_LOST_IND_ID);

    evt->appHandle = appHandle;
    evt->physicalLinkHandle = physicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_modify_cfm(FsmContext* context,
                              void* appHandle,
                              CsrUint16 logicalLinkHandle)
{
    PalCtrlLinkModifyCfm_Evt* evt = (PalCtrlLinkModifyCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkModifyCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_MODIFY_CFM_ID);

    evt->appHandle = appHandle;
    evt->logicalLinkHandle = logicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_supervision_timeout_delete_cfm(FsmContext* context,
                                                  void* appHandle,
                                                  CsrUint8 physicalLinkHandle)
{
    PalCtrlLinkSupervisionTimeoutDeleteCfm_Evt* evt = (PalCtrlLinkSupervisionTimeoutDeleteCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkSupervisionTimeoutDeleteCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_SUPERVISION_TIMEOUT_DELETE_CFM_ID);

    evt->appHandle = appHandle;
    evt->physicalLinkHandle = physicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_supervision_timeout_modify_cfm(FsmContext* context,
                                                  void* appHandle,
                                                  CsrUint8 physicalLinkHandle)
{
    PalCtrlLinkSupervisionTimeoutModifyCfm_Evt* evt = (PalCtrlLinkSupervisionTimeoutModifyCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkSupervisionTimeoutModifyCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_SUPERVISION_TIMEOUT_MODIFY_CFM_ID);

    evt->appHandle = appHandle;
    evt->physicalLinkHandle = physicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_link_supervision_timeout_set_cfm(FsmContext* context,
                                               void* appHandle,
                                               CsrUint8 physicalLinkHandle)
{
    PalCtrlLinkSupervisionTimeoutSetCfm_Evt* evt = (PalCtrlLinkSupervisionTimeoutSetCfm_Evt*)CsrPmalloc(sizeof(PalCtrlLinkSupervisionTimeoutSetCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_LINK_SUPERVISION_TIMEOUT_SET_CFM_ID);

    evt->appHandle = appHandle;
    evt->physicalLinkHandle = physicalLinkHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}

void pal_ctrl_register_cfm(FsmContext* context,
                           void* appHandle)
{
    PalCtrlRegisterCfm_Evt* evt = (PalCtrlRegisterCfm_Evt*)CsrPmalloc(sizeof(PalCtrlRegisterCfm_Evt));

    INIT_EVENT_HEADER(evt, PAL_CTRL_REGISTER_CFM_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->palMgrFsmInstance, evt->common.id);
}


