/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef __PAL_CTRL_SAP_REMOTE_OUTPUT_INTERFACE_GEN_H__
#define __PAL_CTRL_SAP_REMOTE_OUTPUT_INTERFACE_GEN_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "abstractions/osa.h"
#ifdef IPC_IP
#include "ipc/ipc.h"
extern ipcConnection* get_pal_ctrl_ipc_connection(void* context);
#else
#ifdef IPC_CHARDEVICE
#include "ipc/ipc.h"
extern ipcConnection* get_pal_ctrl_ipc_connection(void* context);
#endif
#endif

#ifdef REMOTE_PAL_CTRL_SAP
extern CsrBool remote_pal_ctrl_signal_receive(FsmContext* context, CsrUint8* buffer, CsrUint16 size);
#else
#define remote_pal_ctrl_signal_receive(context, buffer, size) FALSE
#endif

#ifdef __cplusplus
}
#endif

#endif /* __PAL_CTRL_SAP_REMOTE_OUTPUT_INTERFACE_GEN_H__ */
