/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "paldata_top_level_fsm/paldata_top_level_fsm.h"
#include "event_pack_unpack/event_pack_unpack.h"

CsrUint16 serialise_pal_acl_data_ind(CsrUint8** resultBuffer, CsrUint16 dataLength, const CsrUint8 *data, CsrUint8 physicalLinkHandle, CsrUint16 aclOffset, unifi_FrameFreeFunction freeFunction)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    if (dataLength)
    {
        packedSize += dataLength;
    }
    packedSize += 1;
    packedSize += 2;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_ACL_DATA_IND_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, dataLength);
    if (dataLength)
    {
        packedLength += event_pack_buffer(&buffer, data, dataLength);
    }
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);
    packedLength += event_pack_CsrUint16(&buffer, aclOffset);
    packedLength += event_pack_CsrUint32(&buffer, 0);

    *resultBuffer = evt;
    return packedLength;
}


