/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef __BT_SAP_H__
#define __BT_SAP_H__

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------ */
extern void unifi_bt_acl_change_ind(FsmContext* context,
                                    const unifi_MACAddress *aclHandle,
                                    unifi_BtDeviceRole role,
                                    unifi_BtDeviceMode mode);

extern void unifi_bt_acl_channel_types_ind(FsmContext* context,
                                           const unifi_MACAddress *aclHandle,
                                           CsrUint16 logicalChannelTypeMask,
                                           CsrUint8 numberOfGuaranteedLogicalChannels);

extern void unifi_bt_acl_start_ind(FsmContext* context,
                                   const unifi_MACAddress *aclHandle,
                                   unifi_BtDeviceRole role,
                                   unifi_BtDeviceMode mode);

extern void unifi_bt_acl_stop_ind(FsmContext* context,
                                  const unifi_MACAddress *aclHandle);

extern void unifi_bt_bt_active_ind(FsmContext* context);

extern void unifi_bt_bt_inactive_ind(FsmContext* context);

extern void unifi_bt_sco_change_ind(FsmContext* context,
                                    const unifi_MACAddress *aclHandle,
                                    CsrUint16 scoHandle,
                                    CsrUint16 periodSlots,
                                    CsrUint16 durationMinSlots,
                                    CsrUint16 durationMaxSlots);

extern void unifi_bt_sco_start_ind(FsmContext* context,
                                   const unifi_MACAddress *aclHandle,
                                   CsrUint16 scoHandle,
                                   CsrUint16 periodSlots,
                                   CsrUint16 durationMinSlots,
                                   CsrUint16 durationMaxSlots);

extern void unifi_bt_sco_stop_ind(FsmContext* context,
                                  const unifi_MACAddress *aclHandle,
                                  CsrUint16 scoHandle);


/* ------------------------------------------ */
extern void unifi_bt_active_wifi_channel_req(void* context,
                                             CsrUint16 channelMhz,
                                             CsrUint16 bandwidthMhz);

extern void unifi_bt_wifi_active_req(void* context);

extern void unifi_bt_wifi_inactive_req(void* context);




#ifdef __cplusplus
}
#endif

#endif /* __BT_SAP_H__ */
