/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "event_pack_unpack/event_pack_unpack.h"
#include "sme_top_level_fsm/sme_top_level_fsm.h"

static void event_to_unifi_bt_acl_change_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtAclChangeInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);
    evt.role = (unifi_BtDeviceRole) event_unpack_CsrUint8(&buffer);
    evt.mode = (unifi_BtDeviceMode) event_unpack_CsrUint8(&buffer);

    unifi_bt_acl_change_ind(context, &evt.aclHandle, evt.role, evt.mode);

}

static void event_to_unifi_bt_acl_channel_types_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtAclChannelTypesInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);
    evt.logicalChannelTypeMask =  event_unpack_CsrUint16(&buffer);
    evt.numberOfGuaranteedLogicalChannels =  event_unpack_CsrUint8(&buffer);

    unifi_bt_acl_channel_types_ind(context, &evt.aclHandle, evt.logicalChannelTypeMask, evt.numberOfGuaranteedLogicalChannels);

}

static void event_to_unifi_bt_acl_start_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtAclStartInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);
    evt.role = (unifi_BtDeviceRole) event_unpack_CsrUint8(&buffer);
    evt.mode = (unifi_BtDeviceMode) event_unpack_CsrUint8(&buffer);

    unifi_bt_acl_start_ind(context, &evt.aclHandle, evt.role, evt.mode);

}

static void event_to_unifi_bt_acl_stop_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtAclStopInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);

    unifi_bt_acl_stop_ind(context, &evt.aclHandle);

}

static void event_to_unifi_bt_bt_active_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    unifi_bt_bt_active_ind(context);

}

static void event_to_unifi_bt_bt_inactive_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    unifi_bt_bt_inactive_ind(context);

}

static void event_to_unifi_bt_sco_change_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtScoChangeInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);
    evt.scoHandle =  event_unpack_CsrUint16(&buffer);
    evt.periodSlots =  event_unpack_CsrUint16(&buffer);
    evt.durationMinSlots =  event_unpack_CsrUint16(&buffer);
    evt.durationMaxSlots =  event_unpack_CsrUint16(&buffer);

    unifi_bt_sco_change_ind(context, &evt.aclHandle, evt.scoHandle, evt.periodSlots, evt.durationMinSlots, evt.durationMaxSlots);

}

static void event_to_unifi_bt_sco_start_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtScoStartInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);
    evt.scoHandle =  event_unpack_CsrUint16(&buffer);
    evt.periodSlots =  event_unpack_CsrUint16(&buffer);
    evt.durationMinSlots =  event_unpack_CsrUint16(&buffer);
    evt.durationMaxSlots =  event_unpack_CsrUint16(&buffer);

    unifi_bt_sco_start_ind(context, &evt.aclHandle, evt.scoHandle, evt.periodSlots, evt.durationMinSlots, evt.durationMaxSlots);

}

static void event_to_unifi_bt_sco_stop_ind(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiBtScoStopInd_Evt evt;

    event_unpack_buffer(&buffer, evt.aclHandle.data, 6);
    evt.scoHandle =  event_unpack_CsrUint16(&buffer);

    unifi_bt_sco_stop_ind(context, &evt.aclHandle, evt.scoHandle);

}



typedef void (*event_to_fn)(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 size);

static const event_to_fn fnlookup1[12] = {
        NULL,
        NULL,
        event_to_unifi_bt_bt_active_ind,
        event_to_unifi_bt_bt_inactive_ind,
        NULL,
        event_to_unifi_bt_acl_start_ind,
        event_to_unifi_bt_acl_change_ind,
        event_to_unifi_bt_acl_channel_types_ind,
        event_to_unifi_bt_acl_stop_ind,
        event_to_unifi_bt_sco_start_ind,
        event_to_unifi_bt_sco_change_ind,
        event_to_unifi_bt_sco_stop_ind,

};


CsrBool remote_bt_signal_receive(FsmContext* context, CsrUint8* buffer, CsrUint16 size)
{
    CsrUint8* tempbuffer = buffer;
    CsrUint16 id = event_unpack_CsrUint16(&tempbuffer);

    if (id >= 0x7001 &&
        id <= 0x700C)
    {
        if (fnlookup1[id - 0x7001])
        {
            (*fnlookup1[id - 0x7001])(context, buffer, size);
            return TRUE;
        }
    }

    return FALSE;
}
