/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#ifndef __BT_SAP_SERIALIZE_H__
#define __BT_SAP_SERIALIZE_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "sme_top_level_fsm/sme_top_level_fsm.h"

CsrUint16 serialise_unifi_bt_active_wifi_channel_req(CsrUint8** resultBuffer, CsrUint16 channelMhz, CsrUint16 bandwidthMhz);
CsrUint16 serialise_unifi_bt_wifi_active_req(CsrUint8** resultBuffer);
CsrUint16 serialise_unifi_bt_wifi_inactive_req(CsrUint8** resultBuffer);


#ifdef __cplusplus
}
#endif

#endif /* __BT_SAP_SERIALIZE_H__ */
