
obj-$(CONFIG_SND_SUN4I_SOC_HDMIAUDIO) += sun4i-hdmiaudio.o
obj-$(CONFIG_SND_SUN4I_SOC_HDMIAUDIO) += sun4i-anx7150.o
obj-$(CONFIG_SND_SUN4I_SOC_HDMIAUDIO) += anx7150.o
obj-$(CONFIG_SND_SUN4I_SOC_HDMIAUDIO) += sun4i-hdmipcm.o
 
