/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef __PALDATA_ACL_SAP_H__
#define __PALDATA_ACL_SAP_H__

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------ */
extern void pal_acl_data_req(FsmContext* context,
                             CsrUint16 dataLength,
                             const CsrUint8 *data,
                             CsrUint16 logicalLinkHandle,
                             CsrUint16 aclOffset,
                             unifi_FrameFreeFunction freeFunction);


/* ------------------------------------------ */
extern void pal_acl_data_ind(void* context,
                             CsrUint16 dataLength,
                             const CsrUint8 *data,
                             CsrUint8 physicalLinkHandle,
                             CsrUint16 aclOffset,
                             unifi_FrameFreeFunction freeFunction);




#ifdef __cplusplus
}
#endif

#endif /* __PALDATA_ACL_SAP_H__ */
