/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

/* STANDARD INCLUDES *********************************************************/
#include "ie_utils/ie_utils.h"
#include "ie_access/ie_rsn.h"

/* PUBLIC FUNCTION DEFINITIONS ***********************************************/

ie_result ie_get_rsn(CsrUint8* elements, CsrUint32 length, ie_rsn* rsn)
{
    CsrUint8 *pBuf;
    CsrUint8 *pStart;

    ie_result result = ie_find(IE_ID_RSN, elements, length, &pBuf);

    if (result != ie_success)
    {
        return result;
    }

    pStart = pBuf; /* track the start of the IE as used to ensure we don't read pass the end of it*/
    rsn->header = (struct rsn_header*)pBuf;
    pBuf += sizeof(struct rsn_header);

    /* bytelength: pw_cipher_pair*/
    if ((pBuf - pStart) < rsn->header->length)
    {
        rsn->pwCipherPair = (struct rsn_pwCipherPair *)pBuf;
        pBuf+=2;
        pBuf+= (ie_2_byte_array_to_csruint8(rsn->pwCipherPair->pwCipherCount) * 4);
        
    }
    else
    {
        rsn->pwCipherPair = NULL;
    }

    /* bytelength: AKM_cipher_pair*/
    if ((pBuf - pStart) < rsn->header->length)
    {
        rsn->akmCipherPair = (struct rsn_akmCipherPair *)pBuf;
        pBuf+=2;
        pBuf+= (ie_2_byte_array_to_csruint8(rsn->akmCipherPair->akmCipherCount) * 4);
        
    }
    else
    {
        rsn->akmCipherPair = NULL;
    }

    rsn->body1 = (struct rsn_body1 *)pBuf;
    pBuf+=2; /* set over body */

    /* bytelength: PMKID_pair*/
    if ((pBuf - pStart) < rsn->header->length)
    {
        rsn->pmkidPair = (struct rsn_pmkidPair *)pBuf;
        pBuf+=2;
        pBuf+= (ie_2_byte_array_to_csruint8(rsn->pmkidPair->pmkidCount) * 16);
        
    }
    else
    {
        rsn->pmkidPair = NULL;
    }


    return result;
}




