/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef IE_WMM_INFORMATION_H
#define IE_WMM_INFORMATION_H

#ifdef __cplusplus
extern "C" {
#endif

/* STANDARD INCLUDES *********************************************************/
#include "ie_utils/ie_utils.h"

/* COMPLEX TYPES DEFINITIONS *************************************************/
typedef struct ie_wmm_information
{
    CsrUint8  id;
    CsrUint8  length;
    CsrUint8  oui[3];
    CsrUint8  ouiType;
    CsrUint8  ouiSubType;
    CsrUint8  qosField;
}ie_wmm_information;


/* PUBLIC FUNCTION PROTOTYPES ************************************************/
#define ie_get_wmm_information(elements,length, wmm_information) ie_find_vendor_specific(ieWmmInformationOui, ieWmmInformationOuiSubtype, 0, elements, length, (CsrUint8**)&wmm_information);


/* SUBSIDARY ACCESSORS *******************************************************/
#define IE_WMM_INFORMATION__ID_SIZE                          1
#define IE_WMM_INFORMATION__LENGTH_SIZE                      1
#define IE_WMM_INFORMATION__OUI_SIZE                         3
#define IE_WMM_INFORMATION__OUI_TYPE_SIZE                    1
#define IE_WMM_INFORMATION__OUI_SUB_TYPE_SIZE                1
#define IE_WMM_INFORMATION__QOS_FIELD_SIZE                   1
#define IE_WMM_INFORMATION__TOTAL_SIZE                       8




#ifdef __cplusplus
}
#endif

#endif /* IE_WMM_INFORMATION_H */
