/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */


#include "fsm/fsm_internal.h"

#ifdef SME_TRACE_ENABLE
#ifndef SME_TRACE_NO_MSC

#include "nmeio/nmeio_trace_signals.h"


typedef void (*traceFn)(const char* text, const FsmContext* context, const FsmEvent* event);

static const traceFn fnlookup1[22] = {
    (traceFn)trace_NmeSecurityPreconnectReq,
    (traceFn)trace_NmeSecurityPreconnectCfm,
    (traceFn)trace_NmeSecurityStartReq,
    (traceFn)trace_NmeSecurityStartCfm,
    (traceFn)trace_NmeSecurityRestartReq,
    (traceFn)trace_NmeSecurityRestartCfm,
    (traceFn)trace_NmeSecurityStopReq,
    (traceFn)trace_NmeSecurityStopCfm,
    (traceFn)trace_NmeSecurityLibsetkeyInd,
    (traceFn)trace_NmeSecurityLibsetpacInd,
    (traceFn)trace_NmeSecurityLibsetsessionInd,
    (traceFn)trace_NmeSecurityLibsetcertificatevalidationInd,
    (traceFn)trace_NmeSecurityLibabortInd,
    (traceFn)trace_NmeSecurityLibwpsdoneInd,
    (traceFn)trace_NmeSecurityKeysInstalledInd,
    (traceFn)trace_NmeSecurityEapTimer,
    (traceFn)trace_NmeSecurityCompleteInd,
    (traceFn)trace_NmeSecurityAbortInd,
    (traceFn)trace_NmeSecurityPrewpsReq,
    (traceFn)trace_NmeSecurityPrewpsCfm,
    (traceFn)trace_NmeSecurityTerminateReq,
    (traceFn)trace_NmeSecurityTerminateCfm,
};
static const traceFn fnlookup2[20] = {
    (traceFn)trace_UnifiNmeProfileSetReq,
    (traceFn)trace_UnifiNmeProfileSetCfm,
    (traceFn)trace_UnifiNmeProfileDeleteReq,
    (traceFn)trace_UnifiNmeProfileDeleteCfm,
    (traceFn)trace_UnifiNmeProfileDeleteAllReq,
    (traceFn)trace_UnifiNmeProfileDeleteAllCfm,
    (traceFn)trace_UnifiNmeProfileOrderSetReq,
    (traceFn)trace_UnifiNmeProfileOrderSetCfm,
    (traceFn)trace_UnifiNmeProfileConnectReq,
    (traceFn)trace_UnifiNmeProfileConnectCfm,
    (traceFn)trace_UnifiNmeWpsReq,
    (traceFn)trace_UnifiNmeWpsCfm,
    (traceFn)trace_UnifiNmeWpsCancelReq,
    (traceFn)trace_UnifiNmeWpsCancelCfm,
    (traceFn)trace_UnifiNmeConnectionStatusGetReq,
    (traceFn)trace_UnifiNmeConnectionStatusGetCfm,
    (traceFn)trace_UnifiNmeCertificateValidateInd,
    (traceFn)trace_UnifiNmeCertificateValidateRsp,
    (traceFn)trace_UnifiNmeProfileUpdateInd,
    (traceFn)trace_UnifiNmeProfileDisconnectInd,
};
static const traceFn fnlookup3[4] = {
    (traceFn)trace_NmeCoreStartReq,
    (traceFn)trace_NmeCoreStartCfm,
    (traceFn)trace_NmeCoreStopReq,
    (traceFn)trace_NmeCoreStopCfm,
};
static const traceFn fnlookup4[4] = {
    (traceFn)trace_NmeConnMgrDisconnectReq,
    (traceFn)trace_NmeConnMgrDisconnectCfm,
    (traceFn)trace_NmeConnMgrTerminateReq,
    (traceFn)trace_NmeConnMgrTerminateCfm,
};
static const traceFn fnlookup5[3] = {
    (traceFn)trace_NmeWpsTerminateReq,
    (traceFn)trace_NmeWpsTerminateCfm,
    (traceFn)trace_NmeWpsDelayScanExpiryTimer,
};


CsrBool trace_nmeio_fsm_event(const char* text, const FsmContext* context, const FsmEvent *event)
{
    CsrUint16 id = event->id;
    if (id >= 0x6301 && id <= 0x6316){ (*fnlookup1[id - 0x6301])("", context, event); return TRUE;}
    if (id >= 0xa001 && id <= 0xa014){ (*fnlookup2[id - 0xa001])("", context, event); return TRUE;}
    if (id >= 0x6101 && id <= 0x6104){ (*fnlookup3[id - 0x6101])("", context, event); return TRUE;}
    if (id >= 0x6201 && id <= 0x6204){ (*fnlookup4[id - 0x6201])("", context, event); return TRUE;}
    if (id >= 0x6501 && id <= 0x6503){ (*fnlookup5[id - 0x6501])("", context, event); return TRUE;}
    if (id == 0x6401){ trace_NmeNsConnectInd(text, context, (NmeNsConnectInd_Evt*)event); return TRUE;}
    if (id == 0x6402){ trace_NmeNsDisconnectInd(text, context, (NmeNsDisconnectInd_Evt*)event); return TRUE;}


    return FALSE;
}

#endif /* SME_TRACE_NO_MSC */
#endif /* SME_TRACE_ENABLE */
