/* This is an autogenerated file from from sme__fsm_signal_trace_c.pl */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */


#include "nmeio/nmeio_trace_types.h"

#ifdef SME_TRACE_ENABLE


/* nmeio_signals.xml */
const char *trace_unifi_CertificateStatus(unifi_CertificateStatus typeIndex)
{
    switch (typeIndex)
    {
    case unifi_CertificateValid:
        return "unifi_CertificateValid";
    case unifi_CertificateUnsupported:
        return "unifi_CertificateUnsupported";
    case unifi_CertificateRevoked:
        return "unifi_CertificateRevoked";
    case unifi_CertificateExpired:
        return "unifi_CertificateExpired";
    case unifi_CertificateUnknown:
        return "unifi_CertificateUnknown";
    default:
        return "ERROR: unrecognised unifi_CertificateStatus code";
    }
}

const char *trace_unifi_ConnectionStatus(unifi_ConnectionStatus typeIndex)
{
    switch (typeIndex)
    {
    case unifi_ConnectionStatusDisconnected:
        return "unifi_ConnectionStatusDisconnected";
    case unifi_ConnectionStatusConnecting:
        return "unifi_ConnectionStatusConnecting";
    case unifi_ConnectionStatusAuthenticating:
        return "unifi_ConnectionStatusAuthenticating";
    case unifi_ConnectionStatusConnected:
        return "unifi_ConnectionStatusConnected";
    case unifi_ConnectionStatusDisconnecting:
        return "unifi_ConnectionStatusDisconnecting";
    default:
        return "ERROR: unrecognised unifi_ConnectionStatus code";
    }
}

const char *trace_unifi_CredentialType(unifi_CredentialType typeIndex)
{
    switch (typeIndex)
    {
    case unifi_CredentialTypeOpenSystem:
        return "unifi_CredentialTypeOpenSystem";
    case unifi_CredentialTypeWep64:
        return "unifi_CredentialTypeWep64";
    case unifi_CredentialTypeWep128:
        return "unifi_CredentialTypeWep128";
    case unifi_CredentialTypeWpaPsk:
        return "unifi_CredentialTypeWpaPsk";
    case unifi_CredentialTypeWpaPassphrase:
        return "unifi_CredentialTypeWpaPassphrase";
    case unifi_CredentialTypeWpa2Psk:
        return "unifi_CredentialTypeWpa2Psk";
    case unifi_CredentialTypeWpa2Passphrase:
        return "unifi_CredentialTypeWpa2Passphrase";
    case unifi_CredentialType8021xTls:
        return "unifi_CredentialType8021xTls";
    case unifi_CredentialType8021xTtls:
        return "unifi_CredentialType8021xTtls";
    case unifi_CredentialType8021xPeapGtc:
        return "unifi_CredentialType8021xPeapGtc";
    case unifi_CredentialType8021xPeapMschapv2:
        return "unifi_CredentialType8021xPeapMschapv2";
    case unifi_CredentialType8021xLeap:
        return "unifi_CredentialType8021xLeap";
    case unifi_CredentialType8021xFast:
        return "unifi_CredentialType8021xFast";
    case unifi_CredentialTypeWapiPsk:
        return "unifi_CredentialTypeWapiPsk";
    case unifi_CredentialTypeWapiPassphrase:
        return "unifi_CredentialTypeWapiPassphrase";
    case unifi_CredentialTypeWapi:
        return "unifi_CredentialTypeWapi";
    default:
        return "ERROR: unrecognised unifi_CredentialType code";
    }
}

const char *trace_unifi_NmeIndicationsMask(unifi_NmeIndicationsMask typeIndex)
{
    switch (typeIndex)
    {
    case unifi_IndProfileDisconnect:
        return "unifi_IndProfileDisconnect";
    case unifi_IndProfileUpdate:
        return "unifi_IndProfileUpdate";
    case unifi_IndCertificateValidate:
        return "unifi_IndCertificateValidate";
    default:
        return "ERROR: unrecognised unifi_NmeIndicationsMask code";
    }
}

const char *trace_unifi_SecError(unifi_SecError typeIndex)
{
    switch (typeIndex)
    {
    case unifi_SecErrorUnknown:
        return "unifi_SecErrorUnknown";
    default:
        return "ERROR: unrecognised unifi_SecError code";
    }
}


/* nme_core_signals.xml */

/* nme_security_manager_signals.xml */
const char *trace_nme_SecurityResultCode(nme_SecurityResultCode typeIndex)
{
    switch (typeIndex)
    {
    case nme_SecurityResultCodeSuccess:
        return "nme_SecurityResultCodeSuccess";
    case nme_SecurityResultCodeSubscriptionFailed:
        return "nme_SecurityResultCodeSubscriptionFailed";
    case nme_SecurityResultCodeFailed:
        return "nme_SecurityResultCodeFailed";
    case nme_SecurityResultCodeTimeOut:
        return "nme_SecurityResultCodeTimeOut";
    case nme_SecurityResultCodeUnknownCredentialType:
        return "nme_SecurityResultCodeUnknownCredentialType";
    case nme_SecurityResultCodeUnsupportedCredentialType:
        return "nme_SecurityResultCodeUnsupportedCredentialType";
    case nme_SecurityResultCodeNoPacSupplied:
        return "nme_SecurityResultCodeNoPacSupplied";
    case nme_SecurityResultCodeSecondMicFailure:
        return "nme_SecurityResultCodeSecondMicFailure";
    default:
        return "ERROR: unrecognised nme_SecurityResultCode code";
    }
}


/* nme_connection_manager_signals.xml */
const char *trace_unifi_ConnMgrDisconnectReason(unifi_ConnMgrDisconnectReason typeIndex)
{
    switch (typeIndex)
    {
    case unifi_ConnMgrDisconnectReasonCancelled:
        return "unifi_ConnMgrDisconnectReasonCancelled";
    case unifi_ConnMgrDisconnectReasonSecurityAborted:
        return "unifi_ConnMgrDisconnectReasonSecurityAborted";
    default:
        return "ERROR: unrecognised unifi_ConnMgrDisconnectReason code";
    }
}


/* nme_wps_signals.xml */

/* nme_network_selector_signals.xml */

#endif /* SME_TRACE_ENABLE */

