/* This is an autogenerated */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#ifndef NMEIO_TYPE_TRACE_H
#define NMEIO_TYPE_TRACE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "abstractions/osa.h"

#ifdef SME_TRACE_TYPES_ENABLE
#ifdef SME_TRACE_ENABLE

#include "sme_trace/sme_trace_utils.h"

#include "nme_top_level_fsm/nme_top_level_fsm.h"



/* nmeio_signals.xml */
extern const char *trace_unifi_CertificateStatus(unifi_CertificateStatus index);
extern const char *trace_unifi_ConnectionStatus(unifi_ConnectionStatus index);
extern const char *trace_unifi_CredentialType(unifi_CredentialType index);
extern const char *trace_unifi_NmeIndicationsMask(unifi_NmeIndicationsMask index);
extern const char *trace_unifi_SecError(unifi_SecError index);

/* nme_core_signals.xml */

/* nme_security_manager_signals.xml */
extern const char *trace_nme_SecurityResultCode(nme_SecurityResultCode index);

/* nme_connection_manager_signals.xml */
extern const char *trace_unifi_ConnMgrDisconnectReason(unifi_ConnMgrDisconnectReason index);

/* nme_wps_signals.xml */

/* nme_network_selector_signals.xml */


#endif /* SME_TRACE_ENABLE */
#endif /* SME_TRACE_TYPES_ENABLE */

#ifdef __cplusplus
}
#endif

#endif /* NMEIO_TYPE_TRACE_H */

