/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */


#include "nme_top_level_fsm/nme_top_level_fsm.h"

void unifi_nme_association_complete_ind(void* context,
                                        CsrUint16 appHandlesCount,
                                        void* *appHandles,
                                        unifi_Status status,
                                        const unifi_ConnectionInfo *connectionInfo,
                                        unifi_IEEE80211Reason deauthReason)
{
}

void unifi_nme_association_start_ind(void* context,
                                     CsrUint16 appHandlesCount,
                                     void* *appHandles,
                                     const unifi_MACAddress *address,
                                     const unifi_SSID *ssid)
{
}

void unifi_nme_blacklist_cfm(void* context,
                             void* appHandle,
                             unifi_Status status,
                             unifi_ListAction action,
                             CsrUint8 getAddressCount,
                             const unifi_MACAddress *getAddresses)
{
}

void unifi_nme_certificate_validate_ind(void* context,
                                        CsrUint16 appHandlesCount,
                                        void* *appHandles,
                                        CsrUint8 validationId,
                                        CsrUint32 certificateLength,
                                        const CsrUint8 *certificate)
{
}

void unifi_nme_connect_cfm(void* context,
                           void* appHandle,
                           unifi_Status status)
{
}

void unifi_nme_connection_quality_ind(void* context,
                                      CsrUint16 appHandlesCount,
                                      void* *appHandles,
                                      const unifi_LinkQuality *linkQuality)
{
}

void unifi_nme_connection_status_get_cfm(void* context,
                                         void* appHandle,
                                         unifi_Status status,
                                         unifi_ConnectionStatus connectionStatus)
{
}

void unifi_nme_disconnect_cfm(void* context,
                              void* appHandle,
                              unifi_Status status)
{
}

void unifi_nme_event_mask_set_cfm(void* context,
                                  void* appHandle,
                                  unifi_Status status)
{
}

void unifi_nme_get_value_cfm(void* context,
                             void* appHandle,
                             unifi_Status status,
                             const unifi_AppValue *appValue)
{
}

void unifi_nme_ibss_station_ind(void* context,
                                CsrUint16 appHandlesCount,
                                void* *appHandles,
                                const unifi_MACAddress *address,
                                CsrBool isconnected)
{
}

void unifi_nme_key_cfm(void* context,
                       void* appHandle,
                       unifi_Status status,
                       unifi_ListAction action)
{
}

void unifi_nme_media_status_ind(void* context,
                                CsrUint16 appHandlesCount,
                                void* *appHandles,
                                unifi_MediaStatus mediaStatus,
                                const unifi_ConnectionInfo *connectionInfo,
                                unifi_IEEE80211Reason disassocReason,
                                unifi_IEEE80211Reason deauthReason)
{
}

void unifi_nme_mib_get_cfm(void* context,
                           void* appHandle,
                           unifi_Status status,
                           CsrUint16 mibAttributeLength,
                           const CsrUint8 *mibAttribute)
{
}

void unifi_nme_mib_get_next_cfm(void* context,
                                void* appHandle,
                                unifi_Status status,
                                CsrUint16 mibAttributeLength,
                                const CsrUint8 *mibAttribute)
{
}

void unifi_nme_mib_set_cfm(void* context,
                           void* appHandle,
                           unifi_Status status)
{
}

void unifi_nme_mic_failure_ind(void* context,
                               CsrUint16 appHandlesCount,
                               void* *appHandles,
                               CsrBool secondFailure,
                               CsrUint16 count,
                               const unifi_MACAddress *address,
                               unifi_KeyType keyType,
                               CsrUint16 keyId,
                               const CsrUint16 *tsc)
{
}

void unifi_nme_multicast_address_cfm(void* context,
                                     void* appHandle,
                                     unifi_Status status,
                                     unifi_ListAction action,
                                     CsrUint8 getAddressesCount,
                                     const unifi_MACAddress *getAddresses)
{
}

void unifi_nme_packet_filter_set_cfm(void* context,
                                     void* appHandle,
                                     unifi_Status status)
{
}

void unifi_nme_pmkid_cfm(void* context,
                         void* appHandle,
                         unifi_Status status,
                         unifi_ListAction action,
                         CsrUint8 getPmkidsCount,
                         const unifi_Pmkid *getPmkids)
{
}

void unifi_nme_pmkid_candidate_list_ind(void* context,
                                        CsrUint16 appHandlesCount,
                                        void* *appHandles,
                                        CsrUint8 pmkidCandidatesCount,
                                        const unifi_PmkidCandidate *pmkidCandidates)
{
}

void unifi_nme_profile_connect_cfm(void* context,
                                   void* appHandle,
                                   unifi_Status status,
                                   CsrUint8 connectAttemptsCount,
                                   const unifi_ConnectAttempt *connectAttempts)
{
}

void unifi_nme_profile_delete_cfm(void* context,
                                  void* appHandle,
                                  unifi_Status status)
{
}

void unifi_nme_profile_delete_all_cfm(void* context,
                                      void* appHandle,
                                      unifi_Status status)
{
}

void unifi_nme_profile_disconnect_ind(void* context,
                                      CsrUint16 appHandlesCount,
                                      void* *appHandles,
                                      CsrUint8 connectAttemptsCount,
                                      const unifi_ConnectAttempt *connectAttempts)
{
}

void unifi_nme_profile_order_set_cfm(void* context,
                                     void* appHandle,
                                     unifi_Status status)
{
}

void unifi_nme_profile_set_cfm(void* context,
                               void* appHandle,
                               unifi_Status status)
{
}

void unifi_nme_profile_update_ind(void* context,
                                  CsrUint16 appHandlesCount,
                                  void* *appHandles,
                                  const unifi_Profile *profile)
{
}

void unifi_nme_restricted_access_disable_cfm(void* context,
                                             void* appHandle,
                                             unifi_Status status)
{
}

void unifi_nme_restricted_access_enable_cfm(void* context,
                                            void* appHandle,
                                            unifi_Status status)
{
}

void unifi_nme_roam_complete_ind(void* context,
                                 CsrUint16 appHandlesCount,
                                 void* *appHandles,
                                 unifi_Status status)
{
}

void unifi_nme_roam_start_ind(void* context,
                              CsrUint16 appHandlesCount,
                              void* *appHandles,
                              unifi_RoamReason roamReason,
                              unifi_IEEE80211Reason reason80211)
{
}

void unifi_nme_scan_full_cfm(void* context,
                             void* appHandle,
                             unifi_Status status)
{
}

void unifi_nme_scan_result_ind(void* context,
                               CsrUint16 appHandlesCount,
                               void* *appHandles,
                               const unifi_ScanResult *result)
{
}

void unifi_nme_scan_results_flush_cfm(void* context,
                                      void* appHandle,
                                      unifi_Status status)
{
}

void unifi_nme_scan_results_get_cfm(void* context,
                                    void* appHandle,
                                    unifi_Status status,
                                    CsrUint16 scanResultsCount,
                                    const unifi_ScanResult *scanResults)
{
}

void unifi_nme_set_value_cfm(void* context,
                             void* appHandle,
                             unifi_Status status,
                             unifi_AppValueId appValueId)
{
}

void unifi_nme_tspec_ind(void* context,
                         CsrUint16 appHandlesCount,
                         void* *appHandles,
                         CsrUint32 transactionId,
                         unifi_TspecResultCode tspecResultCode,
                         CsrUint16 tspecLength,
                         const CsrUint8 *tspec)
{
}

void unifi_nme_tspec_cfm(void* context,
                         void* appHandle,
                         unifi_Status status,
                         CsrUint32 transactionId,
                         unifi_TspecResultCode tspecResultCode,
                         CsrUint16 tspecLength,
                         const CsrUint8 *tspec)
{
}

void unifi_nme_wifi_flightmode_cfm(void* context,
                                   void* appHandle,
                                   unifi_Status status)
{
}

void unifi_nme_wifi_off_ind(void* context,
                            CsrUint16 appHandlesCount,
                            void* *appHandles,
                            unifi_ControlIndication controlIndication)
{
}

void unifi_nme_wifi_off_cfm(void* context,
                            void* appHandle,
                            unifi_Status status)
{
}

void unifi_nme_wifi_on_cfm(void* context,
                           void* appHandle,
                           unifi_Status status)
{
}

void unifi_nme_wps_cfm(void* context,
                       void* appHandle,
                       unifi_Status status,
                       const unifi_Profile *profile)
{
}

void unifi_nme_wps_cancel_cfm(void* context,
                              void* appHandle,
                              unifi_Status status)
{
}


