/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "bluezsniffer_top_level_fsm/bluezsniffer_top_level_fsm.h"
#include "bt_sap_serialise.h"
#include "event_pack_unpack/event_pack_unpack.h"
#include "ipc/ipc.h"

extern ipcConnection* get_bt_ipc_connection(FsmContext* context);

#ifndef CUSTOM_UNIFI_BT_ACL_CHANGE_IND
void unifi_bt_acl_change_ind(void* context, const unifi_MACAddress *aclHandle, unifi_BtDeviceRole role, unifi_BtDeviceMode mode)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_acl_change_ind(&evt, aclHandle, role, mode);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_ACL_CHANGE_IND */

#ifndef CUSTOM_UNIFI_BT_ACL_CHANNEL_TYPES_IND
void unifi_bt_acl_channel_types_ind(void* context, const unifi_MACAddress *aclHandle, CsrUint16 logicalChannelTypeMask, CsrUint8 numberOfGuaranteedLogicalChannels)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_acl_channel_types_ind(&evt, aclHandle, logicalChannelTypeMask, numberOfGuaranteedLogicalChannels);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_ACL_CHANNEL_TYPES_IND */

#ifndef CUSTOM_UNIFI_BT_ACL_START_IND
void unifi_bt_acl_start_ind(void* context, const unifi_MACAddress *aclHandle, unifi_BtDeviceRole role, unifi_BtDeviceMode mode)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_acl_start_ind(&evt, aclHandle, role, mode);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_ACL_START_IND */

#ifndef CUSTOM_UNIFI_BT_ACL_STOP_IND
void unifi_bt_acl_stop_ind(void* context, const unifi_MACAddress *aclHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_acl_stop_ind(&evt, aclHandle);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_ACL_STOP_IND */

#ifndef CUSTOM_UNIFI_BT_BT_ACTIVE_IND
void unifi_bt_bt_active_ind(void* context)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_bt_active_ind(&evt);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_BT_ACTIVE_IND */

#ifndef CUSTOM_UNIFI_BT_BT_INACTIVE_IND
void unifi_bt_bt_inactive_ind(void* context)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_bt_inactive_ind(&evt);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_BT_INACTIVE_IND */

#ifndef CUSTOM_UNIFI_BT_SCO_CHANGE_IND
void unifi_bt_sco_change_ind(void* context, const unifi_MACAddress *aclHandle, CsrUint16 scoHandle, CsrUint16 periodSlots, CsrUint16 durationMinSlots, CsrUint16 durationMaxSlots)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_sco_change_ind(&evt, aclHandle, scoHandle, periodSlots, durationMinSlots, durationMaxSlots);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_SCO_CHANGE_IND */

#ifndef CUSTOM_UNIFI_BT_SCO_START_IND
void unifi_bt_sco_start_ind(void* context, const unifi_MACAddress *aclHandle, CsrUint16 scoHandle, CsrUint16 periodSlots, CsrUint16 durationMinSlots, CsrUint16 durationMaxSlots)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_sco_start_ind(&evt, aclHandle, scoHandle, periodSlots, durationMinSlots, durationMaxSlots);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_SCO_START_IND */

#ifndef CUSTOM_UNIFI_BT_SCO_STOP_IND
void unifi_bt_sco_stop_ind(void* context, const unifi_MACAddress *aclHandle, CsrUint16 scoHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_bt_sco_stop_ind(&evt, aclHandle, scoHandle);

    (void)ipc_message_send(get_bt_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_BT_SCO_STOP_IND */


