/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef POWER_MANAGER_XML_SIGNALS_H
#define POWER_MANAGER_XML_SIGNALS_H

#ifdef __cplusplus
extern "C" {
#endif

#define POW_SUSPEND_POWER_SAVING_REQ_ID                              0x3E05
#define POW_SUSPEND_POWER_SAVING_CFM_ID                              0x3E06
#define POW_RESUME_POWER_SAVING_REQ_ID                               0x3E07
#define POW_RESUME_POWER_SAVING_CFM_ID                               0x3E08
#define POW_UPDATE_POWER_SAVING_REQ_ID                               0x3E09


/* -------------------------- pow_resume_power_saving_req -------------------------- */
typedef struct PowResumePowerSavingReq_Evt
{
    FsmEvent                        common;
} PowResumePowerSavingReq_Evt;

#define send_pow_resume_power_saving_req(context, pid) \
{ \
    PowResumePowerSavingReq_Evt *evt = (PowResumePowerSavingReq_Evt*) CsrPmalloc(sizeof(PowResumePowerSavingReq_Evt)); \
    fsm_send_event(context, (FsmEvent*)evt, pid, POW_RESUME_POWER_SAVING_REQ_ID); \
}

#define send_pow_resume_power_saving_req_external(context, pid) \
{ \
    PowResumePowerSavingReq_Evt *evt = (PowResumePowerSavingReq_Evt*) CsrPmalloc(sizeof(PowResumePowerSavingReq_Evt)); \
    fsm_send_event_external(context, (FsmEvent*)evt, pid, POW_RESUME_POWER_SAVING_REQ_ID); \
}

/* -------------------------- pow_resume_power_saving_cfm -------------------------- */
typedef struct PowResumePowerSavingCfm_Evt
{
    FsmEvent                        common;
    unifi_Status                    status;
} PowResumePowerSavingCfm_Evt;

#define send_pow_resume_power_saving_cfm(context, pid, p_status) \
{ \
    PowResumePowerSavingCfm_Evt *evt = (PowResumePowerSavingCfm_Evt*) CsrPmalloc(sizeof(PowResumePowerSavingCfm_Evt)); \
    evt->status               = p_status; \
    fsm_send_event(context, (FsmEvent*)evt, pid, POW_RESUME_POWER_SAVING_CFM_ID); \
}

#define send_pow_resume_power_saving_cfm_external(context, pid, p_status) \
{ \
    PowResumePowerSavingCfm_Evt *evt = (PowResumePowerSavingCfm_Evt*) CsrPmalloc(sizeof(PowResumePowerSavingCfm_Evt)); \
    evt->status               = p_status; \
    fsm_send_event_external(context, (FsmEvent*)evt, pid, POW_RESUME_POWER_SAVING_CFM_ID); \
}

/* -------------------------- pow_suspend_power_saving_req -------------------------- */
typedef struct PowSuspendPowerSavingReq_Evt
{
    FsmEvent                        common;
} PowSuspendPowerSavingReq_Evt;

#define send_pow_suspend_power_saving_req(context, pid) \
{ \
    PowSuspendPowerSavingReq_Evt *evt = (PowSuspendPowerSavingReq_Evt*) CsrPmalloc(sizeof(PowSuspendPowerSavingReq_Evt)); \
    fsm_send_event(context, (FsmEvent*)evt, pid, POW_SUSPEND_POWER_SAVING_REQ_ID); \
}

#define send_pow_suspend_power_saving_req_external(context, pid) \
{ \
    PowSuspendPowerSavingReq_Evt *evt = (PowSuspendPowerSavingReq_Evt*) CsrPmalloc(sizeof(PowSuspendPowerSavingReq_Evt)); \
    fsm_send_event_external(context, (FsmEvent*)evt, pid, POW_SUSPEND_POWER_SAVING_REQ_ID); \
}

/* -------------------------- pow_suspend_power_saving_cfm -------------------------- */
typedef struct PowSuspendPowerSavingCfm_Evt
{
    FsmEvent                        common;
    unifi_Status                    status;
} PowSuspendPowerSavingCfm_Evt;

#define send_pow_suspend_power_saving_cfm(context, pid, p_status) \
{ \
    PowSuspendPowerSavingCfm_Evt *evt = (PowSuspendPowerSavingCfm_Evt*) CsrPmalloc(sizeof(PowSuspendPowerSavingCfm_Evt)); \
    evt->status               = p_status; \
    fsm_send_event(context, (FsmEvent*)evt, pid, POW_SUSPEND_POWER_SAVING_CFM_ID); \
}

#define send_pow_suspend_power_saving_cfm_external(context, pid, p_status) \
{ \
    PowSuspendPowerSavingCfm_Evt *evt = (PowSuspendPowerSavingCfm_Evt*) CsrPmalloc(sizeof(PowSuspendPowerSavingCfm_Evt)); \
    evt->status               = p_status; \
    fsm_send_event_external(context, (FsmEvent*)evt, pid, POW_SUSPEND_POWER_SAVING_CFM_ID); \
}

/* -------------------------- pow_update_power_saving_req -------------------------- */
typedef struct PowUpdatePowerSavingReq_Evt
{
    FsmEvent                        common;
} PowUpdatePowerSavingReq_Evt;

#define send_pow_update_power_saving_req(context, pid) \
{ \
    PowUpdatePowerSavingReq_Evt *evt = (PowUpdatePowerSavingReq_Evt*) CsrPmalloc(sizeof(PowUpdatePowerSavingReq_Evt)); \
    fsm_send_event(context, (FsmEvent*)evt, pid, POW_UPDATE_POWER_SAVING_REQ_ID); \
}

#define send_pow_update_power_saving_req_external(context, pid) \
{ \
    PowUpdatePowerSavingReq_Evt *evt = (PowUpdatePowerSavingReq_Evt*) CsrPmalloc(sizeof(PowUpdatePowerSavingReq_Evt)); \
    fsm_send_event_external(context, (FsmEvent*)evt, pid, POW_UPDATE_POWER_SAVING_REQ_ID); \
}





#ifdef __cplusplus
}
#endif

#endif /* POWER_MANAGER_XML_SIGNALS_H */
