/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

/* STANDARD INCLUDES *********************************************************/
#include "ie_utils/ie_utils.h"
#include "ie_access_trace/lib_info_element_trace_fields.h"

/* PUBLIC FUNCTION DEFINITIONS ***********************************************/

#ifdef LIB_INFO_ELEMENT_TRACE_ENABLE

CsrUint8* ie_trace_country(CsrUint8 traceLevel, CsrUint8 *pBuf)
{
    CsrUint32 value;
    CsrUint8 ieSize = ie_len(pBuf)+2;
    CsrUint32 bytesLeft = ieSize;
    CsrUint32 numElement;

    ie_CsrUint8(pBuf, value);         CsrLog(traceLevel, (CsrString*)"", (CsrString*)"id:                        0x%.2x", value );
    bytesLeft -= 1; if (bytesLeft==0) return pBuf;
    ie_CsrUint8(pBuf, value);         CsrLog(traceLevel, (CsrString*)"", (CsrString*)"length:                    0x%.2x", value );
    bytesLeft -= 1; if (bytesLeft==0) return pBuf;
    CsrLog(traceLevel, (CsrString*)"", (CsrString*)"    countryString 0x%.2x 0x%.2x 0x%.2x", pBuf[0], pBuf[1], pBuf[2]);
    pBuf += 3;
    bytesLeft -= 3; if (bytesLeft==0) return pBuf;
    
    /* Variable length field(s): fieldSize =  3 */
    numElement  = bytesLeft /  3;
    for(; numElement > 0 ;numElement--)
    {
        pBuf = ie_trace_channel_spec(traceLevel, pBuf);
    }
    bytesLeft -= 3; if (bytesLeft==0) return pBuf;

    return pBuf;
}


#endif /* LIB_INFO_ELEMENT_TRACE_ENABLE */




