/***************************************************************************
 *
 * This is an AUTOGENERATED file from genio_pack_interface_c.pl
 *
 *    CONFIDENTIAL
 *    Copyright (C) Cambridge Silicon Radio Ltd 2007. All rights reserved.
 */

/***************************************************************************
 * Description:
 *       The following functions are used to convert primitives, commands or
 *       in a packed stream of bytes and send it to a choosen destination.
 *
 * Options used to generate this file:
 * perl genio_pack_interface_c.pl
 *       -o /home/bfsw/host/releases/unifi_hostsoftware_212/build/unifi-driver-212/host/unifi_helper/unifi_sme/../common/saps_impl/pal_hci_sap/ipc/pal_hci_sap_remoteserver_from_pal_interface.c
 *       -x ../../common/hciio/../amp_hci/bt_amp_hci.xml
 *       -d up
 *       -c Event_Code
 *       -i PAL_HCI
 *       -h HCI_Event_Header
 *
 ***************************************************************************/
#include "fsm/csr_wifi_fsm.h" 
#include "sme_trace/sme_trace.h"
#include "sme_trace/sme_pbc.h"
#include "pal_hci_sap/pal_hci_sap_types.h" 
#include "pal_hci_sap/pal_hci_sap_signals.h" 
#include "event_pack_unpack/event_pack_unpack.h"
#include "ipc/ipc.h"
#include "pal_hci_sap/pal_hci_sap_types_trace.h"
#include "pal_hci_sap/pal_hci_sap_signals_trace.h" 
#include "pal_hci_sap_serialise.h" 

extern ipcConnection *get_pal_hci_ipc_connection(FsmContext* context);

#ifndef CUSTOM_HCI_COMMAND_COMPLETE_EVT
void hci_command_complete_evt(void* context, CsrUint8 numHciCommandPackets, const ReturnParameters* returnParameters)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_command_complete_evt(&evt, numHciCommandPackets, returnParameters);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_COMMAND_COMPLETE_EVT */

#ifndef CUSTOM_HCI_COMMAND_STATUS_EVT
void hci_command_status_evt(void* context, HciStatusCode status, CsrUint8 numHciCommandPackets, HciOpcode commandOpcode)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_command_status_evt(&evt, status, numHciCommandPackets, commandOpcode);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_COMMAND_STATUS_EVT */

#ifndef CUSTOM_HCI_HARDWARE_ERROR_EVT
void hci_hardware_error_evt(void* context, CsrUint8 hardwareCode)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_hardware_error_evt(&evt, hardwareCode);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_HARDWARE_ERROR_EVT */

#ifndef CUSTOM_HCI_FLUSH_OCCURRED_EVT
void hci_flush_occurred_evt(void* context, CsrUint16 handle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_flush_occurred_evt(&evt, handle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_FLUSH_OCCURRED_EVT */

#ifndef CUSTOM_HCI_LOOPBACK_COMMAND_EVT
void hci_loopback_command_evt(void* context, HciCommandPacket hciCommandPacket)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_loopback_command_evt(&evt, hciCommandPacket);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_LOOPBACK_COMMAND_EVT */

#ifndef CUSTOM_HCI_DATA_BUFFER_OVERFLOW_EVT
void hci_data_buffer_overflow_evt(void* context, HciLinkType linkType)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_data_buffer_overflow_evt(&evt, linkType);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_DATA_BUFFER_OVERFLOW_EVT */

#ifndef CUSTOM_HCI_QOS_VIOLATION_EVT
void hci_qos_violation_evt(void* context, CsrUint16 handle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_qos_violation_evt(&evt, handle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_QOS_VIOLATION_EVT */

#ifndef CUSTOM_HCI_ENHANCED_FLUSH_COMPLETE_EVT
void hci_enhanced_flush_complete_evt(void* context, CsrUint16 handle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_enhanced_flush_complete_evt(&evt, handle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_ENHANCED_FLUSH_COMPLETE_EVT */

#ifndef CUSTOM_HCI_PHYSICAL_LINK_COMPLETE_EVT
void hci_physical_link_complete_evt(void* context, HciStatusCode status, CsrUint8 physicalLinkHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_physical_link_complete_evt(&evt, status, physicalLinkHandle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_PHYSICAL_LINK_COMPLETE_EVT */

#ifndef CUSTOM_HCI_CHANNEL_SELECT_EVT
void hci_channel_select_evt(void* context, CsrUint8 physicalLinkHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_channel_select_evt(&evt, physicalLinkHandle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_CHANNEL_SELECT_EVT */

#ifndef CUSTOM_HCI_DISCONNECT_PHYSICAL_LINK_COMPLETE_EVT
void hci_disconnect_physical_link_complete_evt(void* context, HciStatusCode status, CsrUint8 physicalLinkHandle, CsrUint8 reason)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_disconnect_physical_link_complete_evt(&evt, status, physicalLinkHandle, reason);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_DISCONNECT_PHYSICAL_LINK_COMPLETE_EVT */

#ifndef CUSTOM_HCI_PHYSICAL_LINK_LOSS_EARLY_WARNING_EVT
void hci_physical_link_loss_early_warning_evt(void* context, CsrUint8 physicalLinkHandle, LinkLossReasonCode linkLossReason)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_physical_link_loss_early_warning_evt(&evt, physicalLinkHandle, linkLossReason);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_PHYSICAL_LINK_LOSS_EARLY_WARNING_EVT */

#ifndef CUSTOM_HCI_PHYSICAL_LINK_RECOVERY_EVT
void hci_physical_link_recovery_evt(void* context, CsrUint8 physicalLinkHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_physical_link_recovery_evt(&evt, physicalLinkHandle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_PHYSICAL_LINK_RECOVERY_EVT */

#ifndef CUSTOM_HCI_LOGICAL_LINK_COMPLETE_EVT
void hci_logical_link_complete_evt(void* context, HciStatusCode status, CsrUint16 logicalLinkHandle, CsrUint8 physicalLinkHandle, CsrUint8 txFlowSpecId)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_logical_link_complete_evt(&evt, status, logicalLinkHandle, physicalLinkHandle, txFlowSpecId);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_LOGICAL_LINK_COMPLETE_EVT */

#ifndef CUSTOM_HCI_DISCONNECT_LOGICAL_LINK_COMPLETE_EVT
void hci_disconnect_logical_link_complete_evt(void* context, HciStatusCode status, CsrUint16 logicalLinkHandle, CsrUint8 reason)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_disconnect_logical_link_complete_evt(&evt, status, logicalLinkHandle, reason);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_DISCONNECT_LOGICAL_LINK_COMPLETE_EVT */

#ifndef CUSTOM_HCI_FLOW_SPEC_MODIFY_COMPLETE_EVT
void hci_flow_spec_modify_complete_evt(void* context, HciStatusCode status, CsrUint16 handle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_flow_spec_modify_complete_evt(&evt, status, handle);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_FLOW_SPEC_MODIFY_COMPLETE_EVT */

#ifndef CUSTOM_HCI_NUMBER_OF_COMPLETED_DATA_BLOCKS_EVT
void hci_number_of_completed_data_blocks_evt(void* context, CsrUint16 totalNumDataBlocks, CsrUint8 numberOfHandles, CsrUint16 handle, CsrUint16 numberOfCompletedPackets, CsrUint16 numberOfCompletedBlocks)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_number_of_completed_data_blocks_evt(&evt, totalNumDataBlocks, numberOfHandles, handle, numberOfCompletedPackets, numberOfCompletedBlocks);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_NUMBER_OF_COMPLETED_DATA_BLOCKS_EVT */

#ifndef CUSTOM_HCI_SHORT_RANGE_MODE_CHANGE_COMPLETE_EVT
void hci_short_range_mode_change_complete_evt(void* context, HciStatusCode status, CsrUint8 physicalLinkHandle, ShortRangeMode shortRangeModeState)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_short_range_mode_change_complete_evt(&evt, status, physicalLinkHandle, shortRangeModeState);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_SHORT_RANGE_MODE_CHANGE_COMPLETE_EVT */

#ifndef CUSTOM_HCI_AMP_STATUS_CHANGE_EVT
void hci_amp_status_change_evt(void* context, HciStatusCode status, AmpStatus ampStatus)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_amp_status_change_evt(&evt, status, ampStatus);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_AMP_STATUS_CHANGE_EVT */

#ifndef CUSTOM_HCI_GENERIC_AMP_LINK_KEY_NT
void hci_generic_amp_link_key_nt(void* context, const BdAddr* bdAddr, const GenericAmpLinkKey* genericAmpLinkKey, LinkKeyType keyType)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_hci_generic_amp_link_key_nt(&evt, bdAddr, genericAmpLinkKey, keyType);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_HCI_GENERIC_AMP_LINK_KEY_NT */

#ifndef CUSTOM_AMP_TRANSMIT_POWER_EVT
void amp_transmit_power_evt(void* context, HciStatusCode status, PowerLevel powerLevel)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_amp_transmit_power_evt(&evt, status, powerLevel);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_AMP_TRANSMIT_POWER_EVT */

#ifndef CUSTOM_AMP_RECEIVER_REPORT_EVT
void amp_receiver_report_evt(void* context, CsrUint8 ampReport)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_amp_receiver_report_evt(&evt, ampReport);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_AMP_RECEIVER_REPORT_EVT */

#ifndef CUSTOM_AMP_START_TRANSMITTER_TEST_EVT
void amp_start_transmitter_test_evt(void* context, HciStatusCode status, CsrUint8 powerLevel)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_amp_start_transmitter_test_evt(&evt, status, powerLevel);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_AMP_START_TRANSMITTER_TEST_EVT */

#ifndef CUSTOM_AMP_START_RECEIVER_TEST_EVT
void amp_start_receiver_test_evt(void* context, HciStatusCode status)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_amp_start_receiver_test_evt(&evt, status);
    (void)ipc_message_send(get_pal_hci_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_AMP_START_RECEIVER_TEST_EVT */

