/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#ifndef __PAL_CTRL_SAP_SERIALIZE_H__
#define __PAL_CTRL_SAP_SERIALIZE_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "sme_top_level_fsm/sme_top_level_fsm.h"

CsrUint16 serialise_pal_ctrl_activate_req(CsrUint8** resultBuffer, void* appHandle);
CsrUint16 serialise_pal_ctrl_deactivate_req(CsrUint8** resultBuffer, void* appHandle);
CsrUint16 serialise_pal_ctrl_event_mask_set_req(CsrUint8** resultBuffer, void* appHandle, CsrUint32 indMask);
CsrUint16 serialise_pal_ctrl_failed_contact_counter_read_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle);
CsrUint16 serialise_pal_ctrl_failed_contact_counter_reset_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle);
CsrUint16 serialise_pal_ctrl_link_alive_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle);
CsrUint16 serialise_pal_ctrl_link_create_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle, CsrUint8 physicalLinkHandle, CsrUint16 userPriority, const unifi_MACAddress *remoteMacAddress, const unifi_MACAddress *localMacAddress, const unifi_AmpFlowSpec *txFlowSpec);
CsrUint16 serialise_pal_ctrl_link_delete_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle, CsrUint8 physicalLinkHandle);
CsrUint16 serialise_pal_ctrl_link_flush_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle);
CsrUint16 serialise_pal_ctrl_link_modify_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle, const unifi_AmpFlowSpec *txFlowSpec);
CsrUint16 serialise_pal_ctrl_link_supervision_timeout_delete_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle);
CsrUint16 serialise_pal_ctrl_link_supervision_timeout_modify_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle, CsrUint16 linkSupervisionTimeout);
CsrUint16 serialise_pal_ctrl_link_supervision_timeout_set_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle, CsrUint16 linkSupervisionTimeout);
CsrUint16 serialise_pal_ctrl_register_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 ampId, CsrUint16 dataQid);


#ifdef __cplusplus
}
#endif

#endif /* __PAL_CTRL_SAP_SERIALIZE_H__ */
