/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "sme_top_level_fsm/sme_top_level_fsm.h"
#include "event_pack_unpack/event_pack_unpack.h"

CsrUint16 serialise_pal_ctrl_activate_req(CsrUint8** resultBuffer, void* appHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_ACTIVATE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_deactivate_req(CsrUint8** resultBuffer, void* appHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_DEACTIVATE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_event_mask_set_req(CsrUint8** resultBuffer, void* appHandle, CsrUint32 indMask)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_EVENT_MASK_SET_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint32(&buffer, indMask);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_failed_contact_counter_read_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_FAILED_CONTACT_COUNTER_READ_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint16(&buffer, logicalLinkHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_failed_contact_counter_reset_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_FAILED_CONTACT_COUNTER_RESET_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint16(&buffer, logicalLinkHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_alive_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_ALIVE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_create_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle, CsrUint8 physicalLinkHandle, CsrUint16 userPriority, const unifi_MACAddress *remoteMacAddress, const unifi_MACAddress *localMacAddress, const unifi_AmpFlowSpec *txFlowSpec)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 2;
    packedSize += 1;
    packedSize += 2;
    packedSize += 6;
    packedSize += 6;
    packedSize += 1;
    packedSize += 2;
    packedSize += 4;
    packedSize += 4;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_CREATE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint16(&buffer, logicalLinkHandle);
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);
    packedLength += event_pack_CsrUint16(&buffer, userPriority);
    packedLength += event_pack_buffer(&buffer, remoteMacAddress->data, 6);
    packedLength += event_pack_buffer(&buffer, localMacAddress->data, 6);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)txFlowSpec->serviceType);
    packedLength += event_pack_CsrUint16(&buffer, txFlowSpec->maximumSduSize);
    packedLength += event_pack_CsrUint32(&buffer, txFlowSpec->sduInterArrivalTime);
    packedLength += event_pack_CsrUint32(&buffer, txFlowSpec->accessLatency);
    packedLength += event_pack_CsrUint32(&buffer, txFlowSpec->flushTimeout);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_delete_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle, CsrUint8 physicalLinkHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 2;
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_DELETE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint16(&buffer, logicalLinkHandle);
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_flush_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_FLUSH_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint16(&buffer, logicalLinkHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_modify_req(CsrUint8** resultBuffer, void* appHandle, CsrUint16 logicalLinkHandle, const unifi_AmpFlowSpec *txFlowSpec)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 2;
    packedSize += 1;
    packedSize += 2;
    packedSize += 4;
    packedSize += 4;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_MODIFY_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint16(&buffer, logicalLinkHandle);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)txFlowSpec->serviceType);
    packedLength += event_pack_CsrUint16(&buffer, txFlowSpec->maximumSduSize);
    packedLength += event_pack_CsrUint32(&buffer, txFlowSpec->sduInterArrivalTime);
    packedLength += event_pack_CsrUint32(&buffer, txFlowSpec->accessLatency);
    packedLength += event_pack_CsrUint32(&buffer, txFlowSpec->flushTimeout);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_supervision_timeout_delete_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_SUPERVISION_TIMEOUT_DELETE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_supervision_timeout_modify_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle, CsrUint16 linkSupervisionTimeout)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_SUPERVISION_TIMEOUT_MODIFY_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);
    packedLength += event_pack_CsrUint16(&buffer, linkSupervisionTimeout);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_link_supervision_timeout_set_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 physicalLinkHandle, CsrUint16 linkSupervisionTimeout)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_LINK_SUPERVISION_TIMEOUT_SET_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, physicalLinkHandle);
    packedLength += event_pack_CsrUint16(&buffer, linkSupervisionTimeout);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_pal_ctrl_register_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 ampId, CsrUint16 dataQid)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, PAL_CTRL_REGISTER_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, ampId);
    packedLength += event_pack_CsrUint16(&buffer, dataQid);

    *resultBuffer = evt;
    return packedLength;
}


