/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#include "fsm/fsm_internal.h"
#include "sme_top_level_fsm/sme_top_level_fsm.h"

/*lint -e725 */

#define INIT_EVENT_HEADER(event,evtid) \
    event->common.id = evtid; \
    event->common.destination = 0; \
    event->common.sender_ = FSM_ENV


void unifi_sys_capabilities_cfm(FsmContext* context,
                                void* appHandle,
                                CsrUint16 commandQueueSize,
                                CsrUint16 trafficQueueSize)
{
    UnifiSysCapabilitiesCfm_Evt* evt = (UnifiSysCapabilitiesCfm_Evt*)CsrPmalloc(sizeof(UnifiSysCapabilitiesCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_CAPABILITIES_CFM_ID);

    evt->appHandle = appHandle;
    evt->commandQueueSize = commandQueueSize;
    evt->trafficQueueSize = trafficQueueSize;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_eapol_cfm(FsmContext* context,
                         void* appHandle,
                         unifi_EapolRc result)
{
    UnifiSysEapolCfm_Evt* evt = (UnifiSysEapolCfm_Evt*)CsrPmalloc(sizeof(UnifiSysEapolCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_EAPOL_CFM_ID);

    evt->appHandle = appHandle;
    evt->result = result;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_ip_configured_ind(FsmContext* context,
                                 CsrBool ipConfigured)
{
    UnifiSysIpConfiguredInd_Evt* evt = (UnifiSysIpConfiguredInd_Evt*)CsrPmalloc(sizeof(UnifiSysIpConfiguredInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_IP_CONFIGURED_IND_ID);

    evt->ipConfigured = ipConfigured;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->coexInstance, evt->common.id);
}

void unifi_sys_m4_transmitted_ind(FsmContext* context)
{
    UnifiSysM4TransmittedInd_Evt* evt = (UnifiSysM4TransmittedInd_Evt*)CsrPmalloc(sizeof(UnifiSysM4TransmittedInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_M4_TRANSMITTED_IND_ID);


    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_ma_unitdata_ind(FsmContext* context,
                               void* appHandle,
                               CsrUint8 subscriptionHandle,
                               CsrUint16 frameLength,
                               const CsrUint8 *frame,
                               unifi_FrameFreeFunction freeFunction,
                               unifi_ReceptionStatus receptionStatus,
                               unifi_Priority priority,
                               unifi_ServiceClass serviceClass)
{
    UnifiSysMaUnitdataInd_Evt* evt = (UnifiSysMaUnitdataInd_Evt*)CsrPmalloc(sizeof(UnifiSysMaUnitdataInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_MA_UNITDATA_IND_ID);

    evt->appHandle = appHandle;
    evt->subscriptionHandle = subscriptionHandle;
    evt->frameLength = frameLength;
    evt->frame = NULL;
    if (frameLength)
    {
        evt->frame = (CsrUint8*)CsrPmalloc(frameLength);
        CsrMemCpy(evt->frame, frame, frameLength);
    }
    evt->freeFunction = freeFunction;
    evt->receptionStatus = receptionStatus;
    evt->priority = priority;
    evt->serviceClass = serviceClass;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_ma_unitdata_cfm(FsmContext* context,
                               void* appHandle,
                               unifi_Status result,
                               unifi_TransmissionStatus transmissionStatus,
                               unifi_Priority providedPriority,
                               unifi_ServiceClass providedServiceClass,
                               CsrUint32 reqIdentifier)
{
    UnifiSysMaUnitdataCfm_Evt* evt = (UnifiSysMaUnitdataCfm_Evt*)CsrPmalloc(sizeof(UnifiSysMaUnitdataCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_MA_UNITDATA_CFM_ID);

    evt->appHandle = appHandle;
    evt->result = result;
    evt->transmissionStatus = transmissionStatus;
    evt->providedPriority = providedPriority;
    evt->providedServiceClass = providedServiceClass;
    evt->reqIdentifier = reqIdentifier;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_ma_unitdata_subscribe_cfm(FsmContext* context,
                                         void* appHandle,
                                         CsrUint8 subscriptionHandle,
                                         unifi_SubscriptionResult status,
                                         CsrUint16 allocOffset)
{
    UnifiSysMaUnitdataSubscribeCfm_Evt* evt = (UnifiSysMaUnitdataSubscribeCfm_Evt*)CsrPmalloc(sizeof(UnifiSysMaUnitdataSubscribeCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_MA_UNITDATA_SUBSCRIBE_CFM_ID);

    evt->appHandle = appHandle;
    evt->subscriptionHandle = subscriptionHandle;
    evt->status = status;
    evt->allocOffset = allocOffset;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_ma_unitdata_unsubscribe_cfm(FsmContext* context,
                                           void* appHandle,
                                           unifi_SubscriptionResult status)
{
    UnifiSysMaUnitdataUnsubscribeCfm_Evt* evt = (UnifiSysMaUnitdataUnsubscribeCfm_Evt*)CsrPmalloc(sizeof(UnifiSysMaUnitdataUnsubscribeCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_MA_UNITDATA_UNSUBSCRIBE_CFM_ID);

    evt->appHandle = appHandle;
    evt->status = status;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_multicast_address_ind(FsmContext* context,
                                     unifi_ListAction action,
                                     CsrUint8 setAddressesCount,
                                     const unifi_MACAddress *setAddresses)
{
    UnifiSysMulticastAddressInd_Evt* evt = (UnifiSysMulticastAddressInd_Evt*)CsrPmalloc(sizeof(UnifiSysMulticastAddressInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_MULTICAST_ADDRESS_IND_ID);

    evt->action = action;
    evt->setAddressesCount = setAddressesCount;
    evt->setAddresses = NULL;
    if (setAddressesCount)
    {
        CsrUint16 i1;
        evt->setAddresses = (unifi_MACAddress*)CsrPmalloc(sizeof(unifi_MACAddress) * setAddressesCount);
        for(i1 = 0; i1 < setAddressesCount; i1++)
        {
            CsrMemCpy(evt->setAddresses[i1].data, setAddresses[i1].data, 6);
        }
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_sys_port_configure_cfm(FsmContext* context,
                                  unifi_Status status,
                                  const unifi_MACAddress *macAddress)
{
    UnifiSysPortConfigureCfm_Evt* evt = (UnifiSysPortConfigureCfm_Evt*)CsrPmalloc(sizeof(UnifiSysPortConfigureCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_PORT_CONFIGURE_CFM_ID);

    evt->status = status;
    CsrMemCpy(evt->macAddress.data, macAddress->data, 6);

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_qos_control_cfm(FsmContext* context,
                               unifi_Status status)
{
    UnifiSysQosControlCfm_Evt* evt = (UnifiSysQosControlCfm_Evt*)CsrPmalloc(sizeof(UnifiSysQosControlCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_QOS_CONTROL_CFM_ID);

    evt->status = status;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->hipProxyInstance, evt->common.id);
}

void unifi_sys_resume_ind(FsmContext* context,
                          CsrBool powerMaintained)
{
    UnifiSysResumeInd_Evt* evt = (UnifiSysResumeInd_Evt*)CsrPmalloc(sizeof(UnifiSysResumeInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_RESUME_IND_ID);

    evt->powerMaintained = powerMaintained;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeCoreInstance, evt->common.id);
}

void unifi_sys_suspend_ind(FsmContext* context,
                           CsrBool hardSuspend,
                           CsrBool d3Suspend)
{
    UnifiSysSuspendInd_Evt* evt = (UnifiSysSuspendInd_Evt*)CsrPmalloc(sizeof(UnifiSysSuspendInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_SUSPEND_IND_ID);

    evt->hardSuspend = hardSuspend;
    evt->d3Suspend = d3Suspend;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeCoreInstance, evt->common.id);
}

void unifi_sys_tclas_add_cfm(FsmContext* context,
                             unifi_Status status)
{
    UnifiSysTclasAddCfm_Evt* evt = (UnifiSysTclasAddCfm_Evt*)CsrPmalloc(sizeof(UnifiSysTclasAddCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_TCLAS_ADD_CFM_ID);

    evt->status = status;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->qosInstance, evt->common.id);
}

void unifi_sys_tclas_del_cfm(FsmContext* context,
                             unifi_Status status)
{
    UnifiSysTclasDelCfm_Evt* evt = (UnifiSysTclasDelCfm_Evt*)CsrPmalloc(sizeof(UnifiSysTclasDelCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_TCLAS_DEL_CFM_ID);

    evt->status = status;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->qosInstance, evt->common.id);
}

void unifi_sys_traffic_protocol_ind(FsmContext* context,
                                    unifi_TrafficPacketType packetType,
                                    unifi_ProtocolDirection direction,
                                    const unifi_MACAddress *srcAddress)
{
    UnifiSysTrafficProtocolInd_Evt* evt = (UnifiSysTrafficProtocolInd_Evt*)CsrPmalloc(sizeof(UnifiSysTrafficProtocolInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_TRAFFIC_PROTOCOL_IND_ID);

    evt->packetType = packetType;
    evt->direction = direction;
    CsrMemCpy(evt->srcAddress.data, srcAddress->data, 6);

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->coexInstance, evt->common.id);
}

void unifi_sys_traffic_sample_ind(FsmContext* context,
                                  const unifi_TrafficStats *stats)
{
    UnifiSysTrafficSampleInd_Evt* evt = (UnifiSysTrafficSampleInd_Evt*)CsrPmalloc(sizeof(UnifiSysTrafficSampleInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_TRAFFIC_SAMPLE_IND_ID);

    evt->stats.rxMeanRate = stats->rxMeanRate;
    evt->stats.rxFramesNum = stats->rxFramesNum;
    evt->stats.txFramesNum = stats->txFramesNum;
    evt->stats.rxBytesCount = stats->rxBytesCount;
    evt->stats.txBytesCount = stats->txBytesCount;
    CsrMemCpy(evt->stats.intervals, stats->intervals, 11);

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->coexInstance, evt->common.id);
}

void unifi_sys_wifi_off_ind(FsmContext* context,
                            unifi_ControlIndication controlIndication)
{
    UnifiSysWifiOffInd_Evt* evt = (UnifiSysWifiOffInd_Evt*)CsrPmalloc(sizeof(UnifiSysWifiOffInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_WIFI_OFF_IND_ID);

    evt->controlIndication = controlIndication;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->unifiDriverInstance, evt->common.id);
}

void unifi_sys_wifi_off_cfm(FsmContext* context)
{
    UnifiSysWifiOffCfm_Evt* evt = (UnifiSysWifiOffCfm_Evt*)CsrPmalloc(sizeof(UnifiSysWifiOffCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_WIFI_OFF_CFM_ID);


    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->unifiDriverInstance, evt->common.id);
}

void unifi_sys_wifi_on_ind(FsmContext* context,
                           unifi_Status status,
                           const unifi_DriverVersions *driverVersions)
{
    UnifiSysWifiOnInd_Evt* evt = (UnifiSysWifiOnInd_Evt*)CsrPmalloc(sizeof(UnifiSysWifiOnInd_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_WIFI_ON_IND_ID);

    evt->status = status;
    evt->driverVersions.chipId = driverVersions->chipId;
    evt->driverVersions.chipVersion = driverVersions->chipVersion;
    evt->driverVersions.firmwareBuild = driverVersions->firmwareBuild;
    evt->driverVersions.firmwareHip = driverVersions->firmwareHip;
    evt->driverVersions.driverBuild = driverVersions->driverBuild;
    evt->driverVersions.driverHip = driverVersions->driverHip;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->unifiDriverInstance, evt->common.id);
}

void unifi_sys_wifi_on_cfm(FsmContext* context,
                           unifi_Status status)
{
    UnifiSysWifiOnCfm_Evt* evt = (UnifiSysWifiOnCfm_Evt*)CsrPmalloc(sizeof(UnifiSysWifiOnCfm_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_SYS_WIFI_ON_CFM_ID);

    evt->status = status;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->unifiDriverInstance, evt->common.id);
}


