/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "sme_top_level_fsm/sme_top_level_fsm.h"
#include "event_pack_unpack/event_pack_unpack.h"

CsrUint16 serialise_unifi_sys_capabilities_req(CsrUint8** resultBuffer, void* appHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_CAPABILITIES_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_configure_power_mode_req(CsrUint8** resultBuffer, unifi_LowPowerMode mode, CsrBool wakeHost)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_CONFIGURE_POWER_MODE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)mode);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)wakeHost);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_eapol_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 subscriptionHandle, CsrUint16 frameLength, const CsrUint8 *frame, unifi_FrameFreeFunction freeFunction)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;
    packedSize += 2;
    if (frameLength)
    {
        packedSize += frameLength;
    }
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_EAPOL_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, subscriptionHandle);
    packedLength += event_pack_CsrUint16(&buffer, frameLength);
    if (frameLength)
    {
        packedLength += event_pack_buffer(&buffer, frame, frameLength);
    }
    packedLength += event_pack_CsrUint32(&buffer, 0);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_hip_req(CsrUint8** resultBuffer, CsrUint16 mlmeCommandLength, const CsrUint8 *mlmeCommand, CsrUint16 dataRef1Length, const CsrUint8 *dataRef1, CsrUint16 dataRef2Length, const CsrUint8 *dataRef2)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    if (mlmeCommandLength)
    {
        packedSize += mlmeCommandLength;
    }
    packedSize += 2;
    if (dataRef1Length)
    {
        packedSize += dataRef1Length;
    }
    packedSize += 2;
    if (dataRef2Length)
    {
        packedSize += dataRef2Length;
    }

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_HIP_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, mlmeCommandLength);
    if (mlmeCommandLength)
    {
        packedLength += event_pack_buffer(&buffer, mlmeCommand, mlmeCommandLength);
    }
    packedLength += event_pack_CsrUint16(&buffer, dataRef1Length);
    if (dataRef1Length)
    {
        packedLength += event_pack_buffer(&buffer, dataRef1, dataRef1Length);
    }
    packedLength += event_pack_CsrUint16(&buffer, dataRef2Length);
    if (dataRef2Length)
    {
        packedLength += event_pack_buffer(&buffer, dataRef2, dataRef2Length);
    }

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_m4_transmit_req(CsrUint8** resultBuffer)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_M4_TRANSMIT_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_ma_unitdata_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 subscriptionHandle, CsrUint16 frameLength, const CsrUint8 *frame, unifi_FrameFreeFunction freeFunction, unifi_Priority priority, unifi_ServiceClass serviceClass, CsrUint32 reqIdentifier)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;
    packedSize += 2;
    if (frameLength)
    {
        packedSize += frameLength;
    }
    packedSize += 4;
    packedSize += 2;
    packedSize += 2;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_MA_UNITDATA_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, subscriptionHandle);
    packedLength += event_pack_CsrUint16(&buffer, frameLength);
    if (frameLength)
    {
        packedLength += event_pack_buffer(&buffer, frame, frameLength);
    }
    packedLength += event_pack_CsrUint32(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)priority);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)serviceClass);
    packedLength += event_pack_CsrUint32(&buffer, reqIdentifier);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_ma_unitdata_rsp(CsrUint8** resultBuffer, CsrUint8 subscriptionHandle, unifi_Status result)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_MA_UNITDATA_RSP_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, subscriptionHandle);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)result);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_ma_unitdata_subscribe_req(CsrUint8** resultBuffer, void* appHandle, unifi_Encapsulation encapsulation, CsrUint16 protocol, CsrUint32 oui)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;
    packedSize += 2;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_MA_UNITDATA_SUBSCRIBE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)encapsulation);
    packedLength += event_pack_CsrUint16(&buffer, protocol);
    packedLength += event_pack_CsrUint32(&buffer, oui);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_ma_unitdata_unsubscribe_req(CsrUint8** resultBuffer, void* appHandle, CsrUint8 subscriptionHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_MA_UNITDATA_UNSUBSCRIBE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);
    packedLength += event_pack_CsrUint8(&buffer, subscriptionHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_media_status_req(CsrUint8** resultBuffer, unifi_MediaStatus mediaStatus, CsrUint32 mediaTypeMask)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_MEDIA_STATUS_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)mediaStatus);
    packedLength += event_pack_CsrUint32(&buffer, mediaTypeMask);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_multicast_address_rsp(CsrUint8** resultBuffer, unifi_Status status, unifi_ListAction action, CsrUint8 getAddressesCount, const unifi_MACAddress *getAddresses)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;
    packedSize += 1;
    packedSize += 1;
    if (getAddressesCount)
    {
        CsrUint16 i1;
        for(i1 = 0; i1 < getAddressesCount; i1++)
        {
            packedSize += 6;
        }
    }

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_MULTICAST_ADDRESS_RSP_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)status);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)action);
    packedLength += event_pack_CsrUint8(&buffer, getAddressesCount);
    if (getAddressesCount)
    {
        CsrUint16 i1;
        for(i1 = 0; i1 < getAddressesCount; i1++)
        {
            packedLength += event_pack_buffer(&buffer, getAddresses[i1].data, 6);
        }
    }

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_port_configure_req(CsrUint8** resultBuffer, unifi_PortAction uncontrolledPortAction, unifi_PortAction controlledPortAction, const unifi_MACAddress *macAddress)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    packedSize += 2;
    packedSize += 6;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_PORT_CONFIGURE_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)uncontrolledPortAction);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)controlledPortAction);
    packedLength += event_pack_buffer(&buffer, macAddress->data, 6);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_qos_control_req(CsrUint8** resultBuffer, unifi_QoSControl control)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_QOS_CONTROL_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)control);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_resume_rsp(CsrUint8** resultBuffer, unifi_Status status)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_RESUME_RSP_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)status);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_suspend_rsp(CsrUint8** resultBuffer, unifi_Status status)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_SUSPEND_RSP_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)status);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_tclas_add_req(CsrUint8** resultBuffer, CsrUint16 tclasLength, const CsrUint8 *tclas)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    if (tclasLength)
    {
        packedSize += tclasLength;
    }

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_TCLAS_ADD_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, tclasLength);
    if (tclasLength)
    {
        packedLength += event_pack_buffer(&buffer, tclas, tclasLength);
    }

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_tclas_del_req(CsrUint8** resultBuffer, CsrUint16 tclasLength, const CsrUint8 *tclas)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    if (tclasLength)
    {
        packedSize += tclasLength;
    }

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_TCLAS_DEL_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, tclasLength);
    if (tclasLength)
    {
        packedLength += event_pack_buffer(&buffer, tclas, tclasLength);
    }

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_traffic_classification_req(CsrUint8** resultBuffer, unifi_TrafficType trafficType, CsrUint16 period)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_TRAFFIC_CLASSIFICATION_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)trafficType);
    packedLength += event_pack_CsrUint16(&buffer, period);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_traffic_config_req(CsrUint8** resultBuffer, unifi_TrafficConfigType trafficConfigType, const unifi_TrafficConfig *config)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 2;
    packedSize += 2;
    packedSize += 4;
    packedSize += 1;
    packedSize += 4;
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_TRAFFIC_CONFIG_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)trafficConfigType);
    packedLength += event_pack_CsrUint16(&buffer, config->packetFilter);
    packedLength += event_pack_CsrUint32(&buffer, config->customFilter.etherType);
    packedLength += event_pack_CsrUint8(&buffer, config->customFilter.ipType);
    packedLength += event_pack_CsrUint32(&buffer, config->customFilter.udpSourcePort);
    packedLength += event_pack_CsrUint32(&buffer, config->customFilter.udpDestPort);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_wifi_off_req(CsrUint8** resultBuffer, void* appHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_WIFI_OFF_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_wifi_off_rsp(CsrUint8** resultBuffer)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_WIFI_OFF_RSP_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_wifi_on_req(CsrUint8** resultBuffer, void* appHandle)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 4;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_WIFI_ON_REQ_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint32(&buffer, (CsrUint32)appHandle);

    *resultBuffer = evt;
    return packedLength;
}

CsrUint16 serialise_unifi_sys_wifi_on_rsp(CsrUint8** resultBuffer, unifi_Status status, const unifi_MACAddress *stationMacAddress, const unifi_SmeVersions *smeVersions, CsrBool scheduledInterrupt)
{
    CsrUint16 packedLength = 0;
    CsrUint32 packedSize = 6;
    CsrUint8* evt;
    CsrUint8* buffer;

    /* Calc Dymanic Size */
    packedSize += 1;
    packedSize += 6;
    packedSize += 4;
    packedSize += 4;
    packedSize += 4;
    packedSize += 4;
    packedSize += (CsrUint16)(CsrStrLen(smeVersions->smeIdString) + 3);
    packedSize += 2;

    evt = (CsrUint8*)CsrPmalloc(packedSize);
    buffer = evt;
    packedLength += event_pack_CsrUint16(&buffer, UNIFI_SYS_WIFI_ON_RSP_ID);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint16(&buffer, 0);
    packedLength += event_pack_CsrUint8(&buffer, (CsrUint8)status);
    packedLength += event_pack_buffer(&buffer, stationMacAddress->data, 6);
    packedLength += event_pack_CsrUint32(&buffer, smeVersions->firmwarePatch);
    packedLength += event_pack_CsrUint32(&buffer, smeVersions->smeBuild);
    packedLength += event_pack_CsrUint32(&buffer, smeVersions->smeVariant);
    packedLength += event_pack_CsrUint32(&buffer, smeVersions->smeHip);
    packedLength += event_pack_string(&buffer, smeVersions->smeIdString);
    packedLength += event_pack_CsrUint16(&buffer, (CsrUint16)scheduledInterrupt);

    *resultBuffer = evt;
    return packedLength;
}


