/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "sme_top_level_fsm/sme_top_level_fsm.h"
#include "sys_sap_serialise.h"
#include "event_pack_unpack/event_pack_unpack.h"
#include "ipc/ipc.h"

extern ipcConnection* get_sys_ipc_connection(FsmContext* context);

#ifndef CUSTOM_UNIFI_SYS_CAPABILITIES_REQ
void unifi_sys_capabilities_req(void* context, void* appHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_capabilities_req(&evt, appHandle);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_CAPABILITIES_REQ */

#ifndef CUSTOM_UNIFI_SYS_CONFIGURE_POWER_MODE_REQ
void unifi_sys_configure_power_mode_req(void* context, unifi_LowPowerMode mode, CsrBool wakeHost)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_configure_power_mode_req(&evt, mode, wakeHost);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_CONFIGURE_POWER_MODE_REQ */

#ifndef CUSTOM_UNIFI_SYS_EAPOL_REQ
void unifi_sys_eapol_req(void* context, void* appHandle, CsrUint8 subscriptionHandle, CsrUint16 frameLength, const CsrUint8 *frame, unifi_FrameFreeFunction freeFunction)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_eapol_req(&evt, appHandle, subscriptionHandle, frameLength, frame, freeFunction);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_EAPOL_REQ */

#ifndef CUSTOM_UNIFI_SYS_HIP_REQ
void unifi_sys_hip_req(void* context, CsrUint16 mlmeCommandLength, const CsrUint8 *mlmeCommand, CsrUint16 dataRef1Length, const CsrUint8 *dataRef1, CsrUint16 dataRef2Length, const CsrUint8 *dataRef2)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_hip_req(&evt, mlmeCommandLength, mlmeCommand, dataRef1Length, dataRef1, dataRef2Length, dataRef2);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_HIP_REQ */

#ifndef CUSTOM_UNIFI_SYS_M4_TRANSMIT_REQ
void unifi_sys_m4_transmit_req(void* context)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_m4_transmit_req(&evt);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_M4_TRANSMIT_REQ */

#ifndef CUSTOM_UNIFI_SYS_MA_UNITDATA_REQ
void unifi_sys_ma_unitdata_req(void* context, void* appHandle, CsrUint8 subscriptionHandle, CsrUint16 frameLength, const CsrUint8 *frame, unifi_FrameFreeFunction freeFunction, unifi_Priority priority, unifi_ServiceClass serviceClass, CsrUint32 reqIdentifier)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_ma_unitdata_req(&evt, appHandle, subscriptionHandle, frameLength, frame, freeFunction, priority, serviceClass, reqIdentifier);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_MA_UNITDATA_REQ */

#ifndef CUSTOM_UNIFI_SYS_MA_UNITDATA_RSP
void unifi_sys_ma_unitdata_rsp(void* context, CsrUint8 subscriptionHandle, unifi_Status result)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_ma_unitdata_rsp(&evt, subscriptionHandle, result);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_MA_UNITDATA_RSP */

#ifndef CUSTOM_UNIFI_SYS_MA_UNITDATA_SUBSCRIBE_REQ
void unifi_sys_ma_unitdata_subscribe_req(void* context, void* appHandle, unifi_Encapsulation encapsulation, CsrUint16 protocol, CsrUint32 oui)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_ma_unitdata_subscribe_req(&evt, appHandle, encapsulation, protocol, oui);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_MA_UNITDATA_SUBSCRIBE_REQ */

#ifndef CUSTOM_UNIFI_SYS_MA_UNITDATA_UNSUBSCRIBE_REQ
void unifi_sys_ma_unitdata_unsubscribe_req(void* context, void* appHandle, CsrUint8 subscriptionHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_ma_unitdata_unsubscribe_req(&evt, appHandle, subscriptionHandle);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_MA_UNITDATA_UNSUBSCRIBE_REQ */

#ifndef CUSTOM_UNIFI_SYS_MEDIA_STATUS_REQ
void unifi_sys_media_status_req(void* context, unifi_MediaStatus mediaStatus, CsrUint32 mediaTypeMask)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_media_status_req(&evt, mediaStatus, mediaTypeMask);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_MEDIA_STATUS_REQ */

#ifndef CUSTOM_UNIFI_SYS_MULTICAST_ADDRESS_RSP
void unifi_sys_multicast_address_rsp(void* context, unifi_Status status, unifi_ListAction action, CsrUint8 getAddressesCount, const unifi_MACAddress *getAddresses)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_multicast_address_rsp(&evt, status, action, getAddressesCount, getAddresses);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_MULTICAST_ADDRESS_RSP */

#ifndef CUSTOM_UNIFI_SYS_PORT_CONFIGURE_REQ
void unifi_sys_port_configure_req(void* context, unifi_PortAction uncontrolledPortAction, unifi_PortAction controlledPortAction, const unifi_MACAddress *macAddress)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_port_configure_req(&evt, uncontrolledPortAction, controlledPortAction, macAddress);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_PORT_CONFIGURE_REQ */

#ifndef CUSTOM_UNIFI_SYS_QOS_CONTROL_REQ
void unifi_sys_qos_control_req(void* context, unifi_QoSControl control)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_qos_control_req(&evt, control);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_QOS_CONTROL_REQ */

#ifndef CUSTOM_UNIFI_SYS_RESUME_RSP
void unifi_sys_resume_rsp(void* context, unifi_Status status)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_resume_rsp(&evt, status);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_RESUME_RSP */

#ifndef CUSTOM_UNIFI_SYS_SUSPEND_RSP
void unifi_sys_suspend_rsp(void* context, unifi_Status status)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_suspend_rsp(&evt, status);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_SUSPEND_RSP */

#ifndef CUSTOM_UNIFI_SYS_TCLAS_ADD_REQ
void unifi_sys_tclas_add_req(void* context, CsrUint16 tclasLength, const CsrUint8 *tclas)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_tclas_add_req(&evt, tclasLength, tclas);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_TCLAS_ADD_REQ */

#ifndef CUSTOM_UNIFI_SYS_TCLAS_DEL_REQ
void unifi_sys_tclas_del_req(void* context, CsrUint16 tclasLength, const CsrUint8 *tclas)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_tclas_del_req(&evt, tclasLength, tclas);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_TCLAS_DEL_REQ */

#ifndef CUSTOM_UNIFI_SYS_TRAFFIC_CLASSIFICATION_REQ
void unifi_sys_traffic_classification_req(void* context, unifi_TrafficType trafficType, CsrUint16 period)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_traffic_classification_req(&evt, trafficType, period);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_TRAFFIC_CLASSIFICATION_REQ */

#ifndef CUSTOM_UNIFI_SYS_TRAFFIC_CONFIG_REQ
void unifi_sys_traffic_config_req(void* context, unifi_TrafficConfigType trafficConfigType, const unifi_TrafficConfig *config)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_traffic_config_req(&evt, trafficConfigType, config);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_TRAFFIC_CONFIG_REQ */

#ifndef CUSTOM_UNIFI_SYS_WIFI_OFF_REQ
void unifi_sys_wifi_off_req(void* context, void* appHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_wifi_off_req(&evt, appHandle);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_WIFI_OFF_REQ */

#ifndef CUSTOM_UNIFI_SYS_WIFI_OFF_RSP
void unifi_sys_wifi_off_rsp(void* context)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_wifi_off_rsp(&evt);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_WIFI_OFF_RSP */

#ifndef CUSTOM_UNIFI_SYS_WIFI_ON_REQ
void unifi_sys_wifi_on_req(void* context, void* appHandle)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_wifi_on_req(&evt, appHandle);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_WIFI_ON_REQ */

#ifndef CUSTOM_UNIFI_SYS_WIFI_ON_RSP
void unifi_sys_wifi_on_rsp(void* context, unifi_Status status, const unifi_MACAddress *stationMacAddress, const unifi_SmeVersions *smeVersions, CsrBool scheduledInterrupt)
{
    CsrUint8* evt;
    CsrUint16 packedLength = serialise_unifi_sys_wifi_on_rsp(&evt, status, stationMacAddress, smeVersions, scheduledInterrupt);

    (void)ipc_message_send(get_sys_ipc_connection(context), evt, packedLength);
    CsrPfree(evt);
}
#endif /* CUSTOM_UNIFI_SYS_WIFI_ON_RSP */


