/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef LINK_QUALITY_XML_TYPES_H
#define LINK_QUALITY_XML_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum unifi_RoamingBand
{
    unifi_RoamingBand1                                      = 0x0000,
    unifi_RoamingBand2                                      = 0x0001,
    unifi_RoamingBand3                                      = 0x0002
} unifi_RoamingBand;











#ifdef __cplusplus
}
#endif

#endif /* LINK_QUALITY_XML_TYPES_H */
