

obj-y += ccmu/ccm_mod_clk.o \
         ccmu/ccm_sys_clk.o \
         ccmu/ccm.o \
         ccmu/pll_cfg_tbl.o \
         ccmu/ccu_dbg.o \
         clock.o
obj-$(CONFIG_NO_HZ) +=aw_clocksrc.o
obj-$(CONFIG_RTC_DRV_SUN4I) +=sun4i_rtc.o

