/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#include "event_pack_unpack/event_pack_unpack.h"
#include "sme_top_level_fsm/sme_top_level_fsm.h"

static void event_to_unifi_mgt_blacklist_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtBlacklistReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.action = (unifi_ListAction) event_unpack_CsrUint8(&buffer);
    evt.setAddressCount =  event_unpack_CsrUint8(&buffer);
    evt.setAddresses = NULL;
    if (evt.setAddressCount)
    {
        CsrUint16 i1;
        evt.setAddresses = (unifi_MACAddress*)CsrPmalloc(sizeof(unifi_MACAddress) * evt.setAddressCount);
        for(i1 = 0; i1 < evt.setAddressCount; i1++)
        {
            event_unpack_buffer(&buffer, evt.setAddresses[i1].data, 6);
        }
    }

    unifi_mgt_blacklist_req(context, evt.appHandle, evt.action, evt.setAddressCount, evt.setAddresses);

    CsrPfree(evt.setAddresses);
}

static void event_to_unifi_mgt_connect_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtConnectReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    event_unpack_buffer(&buffer, evt.connectionConfig.ssid.ssid, 32);
    evt.connectionConfig.ssid.length =  event_unpack_CsrUint8(&buffer);
    event_unpack_buffer(&buffer, evt.connectionConfig.bssid.data, 6);
    evt.connectionConfig.bssType = (unifi_BSSType) event_unpack_CsrUint8(&buffer);
    evt.connectionConfig.ifIndex = (unifi_RadioIF) event_unpack_CsrUint8(&buffer);
    evt.connectionConfig.privacyMode = (unifi_80211PrivacyMode) event_unpack_CsrUint8(&buffer);
    evt.connectionConfig.authModeMask =  event_unpack_CsrUint16(&buffer);
    evt.connectionConfig.encryptionModeMask =  event_unpack_CsrUint16(&buffer);
    evt.connectionConfig.mlmeAssociateReqInformationElementsLength =  event_unpack_CsrUint16(&buffer);
    evt.connectionConfig.mlmeAssociateReqInformationElements = NULL;
    if (evt.connectionConfig.mlmeAssociateReqInformationElementsLength)
    {
        evt.connectionConfig.mlmeAssociateReqInformationElements = (CsrUint8*)CsrPmalloc(evt.connectionConfig.mlmeAssociateReqInformationElementsLength);
        event_unpack_buffer(&buffer, evt.connectionConfig.mlmeAssociateReqInformationElements, evt.connectionConfig.mlmeAssociateReqInformationElementsLength);
    }
    evt.connectionConfig.wmmQosInfo =  event_unpack_CsrUint8(&buffer);
    evt.connectionConfig.adhocJoinOnly = (CsrBool) event_unpack_CsrUint16(&buffer);
    evt.connectionConfig.adhocChannel =  event_unpack_CsrUint8(&buffer);

    unifi_mgt_connect_req(context, evt.appHandle, &evt.connectionConfig);

    CsrPfree(evt.connectionConfig.mlmeAssociateReqInformationElements);
}

static void event_to_unifi_mgt_disconnect_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtDisconnectReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);

    unifi_mgt_disconnect_req(context, evt.appHandle);

}

static void event_to_unifi_mgt_event_mask_set_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtEventMaskSetReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.indMask =  event_unpack_CsrUint32(&buffer);

    unifi_mgt_event_mask_set_req(context, evt.appHandle, evt.indMask);

}

static void event_to_unifi_mgt_get_value_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtGetValueReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.appValueId = (unifi_AppValueId) event_unpack_CsrUint8(&buffer);

    unifi_mgt_get_value_req(context, evt.appHandle, evt.appValueId);

}

static void event_to_unifi_mgt_key_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtKeyReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.action = (unifi_ListAction) event_unpack_CsrUint8(&buffer);
    evt.key.keyType = (unifi_KeyType) event_unpack_CsrUint8(&buffer);
    evt.key.keyIndex =  event_unpack_CsrUint8(&buffer);
    evt.key.wepTxKey = (CsrBool) event_unpack_CsrUint16(&buffer);
    {
    CsrUint16 i2;
    for(i2 = 0; i2 < 8; i2++)
    {
        evt.key.keyRsc[i2] =  event_unpack_CsrUint16(&buffer);
    }
    }
    evt.key.authenticator = (CsrBool) event_unpack_CsrUint16(&buffer);
    event_unpack_buffer(&buffer, evt.key.address.data, 6);
    evt.key.keyLength =  event_unpack_CsrUint8(&buffer);
    event_unpack_buffer(&buffer, evt.key.key, 32);

    unifi_mgt_key_req(context, evt.appHandle, evt.action, &evt.key);

}

static void event_to_unifi_mgt_mib_get_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtMibGetReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.mibAttributeLength =  event_unpack_CsrUint16(&buffer);
    evt.mibAttribute = NULL;
    if (evt.mibAttributeLength)
    {
        evt.mibAttribute = (CsrUint8*)CsrPmalloc(evt.mibAttributeLength);
        event_unpack_buffer(&buffer, evt.mibAttribute, evt.mibAttributeLength);
    }

    unifi_mgt_mib_get_req(context, evt.appHandle, evt.mibAttributeLength, evt.mibAttribute);

    CsrPfree(evt.mibAttribute);
}

static void event_to_unifi_mgt_mib_get_next_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtMibGetNextReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.mibAttributeLength =  event_unpack_CsrUint16(&buffer);
    evt.mibAttribute = NULL;
    if (evt.mibAttributeLength)
    {
        evt.mibAttribute = (CsrUint8*)CsrPmalloc(evt.mibAttributeLength);
        event_unpack_buffer(&buffer, evt.mibAttribute, evt.mibAttributeLength);
    }

    unifi_mgt_mib_get_next_req(context, evt.appHandle, evt.mibAttributeLength, evt.mibAttribute);

    CsrPfree(evt.mibAttribute);
}

static void event_to_unifi_mgt_mib_set_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtMibSetReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.mibAttributeLength =  event_unpack_CsrUint16(&buffer);
    evt.mibAttribute = NULL;
    if (evt.mibAttributeLength)
    {
        evt.mibAttribute = (CsrUint8*)CsrPmalloc(evt.mibAttributeLength);
        event_unpack_buffer(&buffer, evt.mibAttribute, evt.mibAttributeLength);
    }

    unifi_mgt_mib_set_req(context, evt.appHandle, evt.mibAttributeLength, evt.mibAttribute);

    CsrPfree(evt.mibAttribute);
}

static void event_to_unifi_mgt_multicast_address_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtMulticastAddressReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.action = (unifi_ListAction) event_unpack_CsrUint8(&buffer);
    evt.setAddressesCount =  event_unpack_CsrUint8(&buffer);
    evt.setAddresses = NULL;
    if (evt.setAddressesCount)
    {
        CsrUint16 i1;
        evt.setAddresses = (unifi_MACAddress*)CsrPmalloc(sizeof(unifi_MACAddress) * evt.setAddressesCount);
        for(i1 = 0; i1 < evt.setAddressesCount; i1++)
        {
            event_unpack_buffer(&buffer, evt.setAddresses[i1].data, 6);
        }
    }

    unifi_mgt_multicast_address_req(context, evt.appHandle, evt.action, evt.setAddressesCount, evt.setAddresses);

    CsrPfree(evt.setAddresses);
}

static void event_to_unifi_mgt_packet_filter_set_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtPacketFilterSetReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.filterLength =  event_unpack_CsrUint16(&buffer);
    evt.filter = NULL;
    if (evt.filterLength)
    {
        evt.filter = (CsrUint8*)CsrPmalloc(evt.filterLength);
        event_unpack_buffer(&buffer, evt.filter, evt.filterLength);
    }
    evt.mode = (unifi_PacketFilterMode) event_unpack_CsrUint8(&buffer);
    event_unpack_buffer(&buffer, evt.arpFilterAddress.a, 4);

    unifi_mgt_packet_filter_set_req(context, evt.appHandle, evt.filterLength, evt.filter, evt.mode, &evt.arpFilterAddress);

    CsrPfree(evt.filter);
}

static void event_to_unifi_mgt_pmkid_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtPmkidReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.action = (unifi_ListAction) event_unpack_CsrUint8(&buffer);
    evt.setPmkidsCount =  event_unpack_CsrUint8(&buffer);
    evt.setPmkids = NULL;
    if (evt.setPmkidsCount)
    {
        CsrUint16 i1;
        evt.setPmkids = (unifi_Pmkid*)CsrPmalloc(sizeof(unifi_Pmkid) * evt.setPmkidsCount);
        for(i1 = 0; i1 < evt.setPmkidsCount; i1++)
        {
            event_unpack_buffer(&buffer, evt.setPmkids[i1].bssid.data, 6);
            event_unpack_buffer(&buffer, evt.setPmkids[i1].pmkid, 16);
        }
    }

    unifi_mgt_pmkid_req(context, evt.appHandle, evt.action, evt.setPmkidsCount, evt.setPmkids);

    CsrPfree(evt.setPmkids);
}

static void event_to_unifi_mgt_restricted_access_disable_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtRestrictedAccessDisableReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);

    unifi_mgt_restricted_access_disable_req(context, evt.appHandle);

}

static void event_to_unifi_mgt_restricted_access_enable_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtRestrictedAccessEnableReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);

    unifi_mgt_restricted_access_enable_req(context, evt.appHandle);

}

static void event_to_unifi_mgt_scan_full_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtScanFullReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.ssidCount =  event_unpack_CsrUint8(&buffer);
    evt.ssid = NULL;
    if (evt.ssidCount)
    {
        CsrUint16 i1;
        evt.ssid = (unifi_SSID*)CsrPmalloc(sizeof(unifi_SSID) * evt.ssidCount);
        for(i1 = 0; i1 < evt.ssidCount; i1++)
        {
            event_unpack_buffer(&buffer, evt.ssid[i1].ssid, 32);
            evt.ssid[i1].length =  event_unpack_CsrUint8(&buffer);
        }
    }
    event_unpack_buffer(&buffer, evt.bssid.data, 6);
    evt.forceScan = (CsrBool) event_unpack_CsrUint16(&buffer);
    evt.bssType = (unifi_BSSType) event_unpack_CsrUint8(&buffer);
    evt.scanType = (unifi_ScanType) event_unpack_CsrUint8(&buffer);
    evt.channelListCount =  event_unpack_CsrUint16(&buffer);
    evt.channelList = NULL;
    if (evt.channelListCount)
    {
        evt.channelList = (CsrUint8*)CsrPmalloc(evt.channelListCount);
        event_unpack_buffer(&buffer, evt.channelList, evt.channelListCount);
    }
    evt.probeIeLength =  event_unpack_CsrUint16(&buffer);
    evt.probeIe = NULL;
    if (evt.probeIeLength)
    {
        evt.probeIe = (CsrUint8*)CsrPmalloc(evt.probeIeLength);
        event_unpack_buffer(&buffer, evt.probeIe, evt.probeIeLength);
    }

    unifi_mgt_scan_full_req(context, evt.appHandle, evt.ssidCount, evt.ssid, &evt.bssid, evt.forceScan, evt.bssType, evt.scanType, evt.channelListCount, evt.channelList, evt.probeIeLength, evt.probeIe);

    CsrPfree(evt.ssid);
    CsrPfree(evt.channelList);
    CsrPfree(evt.probeIe);
}

static void event_to_unifi_mgt_scan_results_flush_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtScanResultsFlushReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);

    unifi_mgt_scan_results_flush_req(context, evt.appHandle);

}

static void event_to_unifi_mgt_scan_results_get_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtScanResultsGetReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);

    unifi_mgt_scan_results_get_req(context, evt.appHandle);

}

static void event_to_unifi_mgt_set_value_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtSetValueReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.appValue.id = (unifi_AppValueId) event_unpack_CsrUint8(&buffer);
    switch(evt.appValue.id)
    {
    case unifi_CloakedSsidConfigValue:
        evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsidsCount =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsids = NULL;
        if (evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsidsCount)
        {
            CsrUint16 i4;
            evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsids = (unifi_SSID*)CsrPmalloc(sizeof(unifi_SSID) * evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsidsCount);
            for(i4 = 0; i4 < evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsidsCount; i4++)
            {
                event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsids[i4].ssid, 32);
                evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsids[i4].length =  event_unpack_CsrUint8(&buffer);
            }
        }
        break;
    case unifi_ScanConfigValue:
        {
        CsrUint16 i4;
        for(i4 = 0; i4 < 4; i4++)
        {
            evt.appValue.unifi_Value_union.scanConfig.scanCfg[i4].intervalSeconds =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.scanConfig.scanCfg[i4].validitySeconds =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.scanConfig.scanCfg[i4].minActiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.scanConfig.scanCfg[i4].maxActiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.scanConfig.scanCfg[i4].minPassiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.scanConfig.scanCfg[i4].maxPassiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
        }
        }
        evt.appValue.unifi_Value_union.scanConfig.disableAutonomousScans = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.maxResults =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.highRSSIThreshold =  event_unpack_CsrInt8(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.lowRSSIThreshold =  event_unpack_CsrInt8(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.deltaRSSIThreshold =  event_unpack_CsrInt8(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.highSNRThreshold =  event_unpack_CsrInt8(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.lowSNRThreshold =  event_unpack_CsrInt8(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.deltaSNRThreshold =  event_unpack_CsrInt8(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.passiveChannelListCount =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.scanConfig.passiveChannelList = NULL;
        if (evt.appValue.unifi_Value_union.scanConfig.passiveChannelListCount)
        {
            evt.appValue.unifi_Value_union.scanConfig.passiveChannelList = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.scanConfig.passiveChannelListCount);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.scanConfig.passiveChannelList, evt.appValue.unifi_Value_union.scanConfig.passiveChannelListCount);
        }
        break;
    case unifi_RegulatoryDomainInfoValue:
        evt.appValue.unifi_Value_union.regDomInfo.dot11MultiDomainCapabilityImplemented = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.regDomInfo.dot11MultiDomainCapabilityEnabled = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.regDomInfo.currentRegulatoryDomain = (unifi_RegulatoryDomain) event_unpack_CsrUint8(&buffer);
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.regDomInfo.currentCountryCode, 2);
        break;
    case unifi_SmeConfigValue:
        evt.appValue.unifi_Value_union.smeConfig.connectionQualityRssiChangeTrigger =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.connectionQualitySnrChangeTrigger =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.trustLevel = (unifi_80211dTrustLevel) event_unpack_CsrUint8(&buffer);
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.smeConfig.countryCode, 2);
        evt.appValue.unifi_Value_union.smeConfig.wmmModeMask =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.ifIndex = (unifi_RadioIF) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.firmwareDriverInterface = (unifi_FirmwareDriverInterface) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.allowUnicastUseGroupCipher = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.enableRestrictedAccess = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.enableStrictDraftN = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.smeConfig.enableOpportunisticKeyCaching = (CsrBool) event_unpack_CsrUint16(&buffer);
        break;
    case unifi_VersionsValue:
        evt.appValue.unifi_Value_union.versions.chipId =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.chipVersion =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.firmwareBuild =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.firmwarePatch =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.firmwareHip =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.driverBuild =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.driverHip =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.smeBuild =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.smeVariant =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.smeHip =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.versions.smeIdString = event_unpack_string(&buffer);
        break;
    case unifi_CoexConfigValue:
        evt.appValue.unifi_Value_union.coexConfig.coexEnable = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexAfhChannelEnable = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexAdvancedEnable = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexEnableSchemeManagement = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexDirection = (unifi_CoexDirection) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexPeriodicWakeHost = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexTrafficBurstyLatencyMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexTrafficContinuousLatencyMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexObexBlackoutDurationMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexObexBlackoutPeriodMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexA2dpBlackoutDurationMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexConfig.coexA2dpBlackoutPeriodMs =  event_unpack_CsrUint16(&buffer);
        break;
    case unifi_LinkQualityValue:
        evt.appValue.unifi_Value_union.linkQuality.unifiRssi =  event_unpack_CsrInt16(&buffer);
        evt.appValue.unifi_Value_union.linkQuality.unifiSnr =  event_unpack_CsrInt16(&buffer);
        break;
    case unifi_StationMACAddressValue:
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.stationMacAddress.data, 6);
        break;
    case unifi_MibConfigValue:
        evt.appValue.unifi_Value_union.mibConfig.unifiFixMaxTxDataRate = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.mibConfig.unifiFixTxDataRate =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.mibConfig.dot11RtsThreshold =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.mibConfig.dot11FragmentationThreshold =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.mibConfig.dot11CurrentTxPowerLevel =  event_unpack_CsrUint16(&buffer);
        break;
    case unifi_PermanentMACAddressValue:
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.permanentMacAddress.data, 6);
        break;
    case unifi_ConnectionStatsValue:
        evt.appValue.unifi_Value_union.connectionStats.unifiTxDataRate =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.unifiRxDataRate =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RetryCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11MultipleRetryCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11AckFailureCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11FrameDuplicateCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11FcsErrorCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RtsSuccessCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RtsFailureCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11FailedCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11TransmittedFragmentCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11TransmittedFrameCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11WEPExcludedCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11WEPICVErrorCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11WEPUndecryptableCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11MulticastReceivedFrameCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11MulticastTransmittedFrameCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11ReceivedFragmentCount =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNA4WayHandshakeFailures =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNATKIPCounterMeasuresInvoked =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNAStatsTKIPLocalMICFailures =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNAStatsTKIPReplays =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNAStatsTKIPICVErrors =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNAStatsCCMPReplays =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.connectionStats.dot11RSNAStatsCCMPDecryptErrors =  event_unpack_CsrUint32(&buffer);
        break;
    case unifi_RoamingConfigValue:
        {
        CsrUint16 i4;
        for(i4 = 0; i4 < 3; i4++)
        {
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].rssiHighThreshold =  event_unpack_CsrInt16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].rssiLowThreshold =  event_unpack_CsrInt16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].snrHighThreshold =  event_unpack_CsrInt16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].snrLowThreshold =  event_unpack_CsrInt16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].monitorInterval =  event_unpack_CsrUint32(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].monitorWindow =  event_unpack_CsrUint32(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11RetryRatio =  event_unpack_CsrUint8(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11MultipleRetryRatio =  event_unpack_CsrUint8(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11AckFailureRatio =  event_unpack_CsrUint8(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11FcsErrorRatio =  event_unpack_CsrUint8(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11RtsFailureRatio =  event_unpack_CsrUint8(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamingBands[i4].beaconLossThreshold =  event_unpack_CsrUint8(&buffer);
        }
        }
        evt.appValue.unifi_Value_union.roamingConfig.lowQualHystWindow =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.roamingConfig.apBlockTimeMs =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.roamingConfig.roamMonitorPeriodMs =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.roamingConfig.roamNumMaxTh =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.roamingConfig.disableRoamScans = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.roamingConfig.reconnectLimit =  event_unpack_CsrUint8(&buffer);
        {
        CsrUint16 i4;
        for(i4 = 0; i4 < 3; i4++)
        {
            evt.appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].intervalSeconds =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].validitySeconds =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].minActiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].maxActiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].minPassiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
            evt.appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].maxPassiveChannelTimeTu =  event_unpack_CsrUint16(&buffer);
        }
        }
        break;
    case unifi_AdHocConfigValue:
        evt.appValue.unifi_Value_union.adHocConfig.atimWindowTu =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.adHocConfig.beaconPeriodTu =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.adHocConfig.joinOnlyAttempts =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.adHocConfig.joinAttemptIntervalMs =  event_unpack_CsrUint16(&buffer);
        break;
    case unifi_ConnectionInfoValue:
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.ssid.ssid, 32);
        evt.appValue.unifi_Value_union.connectionInfo.ssid.length =  event_unpack_CsrUint8(&buffer);
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.bssid.data, 6);
        evt.appValue.unifi_Value_union.connectionInfo.networkType80211 = (unifi_80211NetworkType) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.channelNumber =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.channelFrequency =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.authMode = (unifi_AuthMode) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.pairwiseCipher = (unifi_EncryptionMode) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.groupCipher = (unifi_EncryptionMode) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.ifIndex = (unifi_RadioIF) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.atimWindowTu =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.beaconPeriodTu =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.reassociation = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.beaconFrameLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.beaconFrame = NULL;
        if (evt.appValue.unifi_Value_union.connectionInfo.beaconFrameLength)
        {
            evt.appValue.unifi_Value_union.connectionInfo.beaconFrame = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionInfo.beaconFrameLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.beaconFrame, evt.appValue.unifi_Value_union.connectionInfo.beaconFrameLength);
        }
        evt.appValue.unifi_Value_union.connectionInfo.associationReqFrameLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.associationReqFrame = NULL;
        if (evt.appValue.unifi_Value_union.connectionInfo.associationReqFrameLength)
        {
            evt.appValue.unifi_Value_union.connectionInfo.associationReqFrame = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionInfo.associationReqFrameLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.associationReqFrame, evt.appValue.unifi_Value_union.connectionInfo.associationReqFrameLength);
        }
        evt.appValue.unifi_Value_union.connectionInfo.associationRspFrameLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.associationRspFrame = NULL;
        if (evt.appValue.unifi_Value_union.connectionInfo.associationRspFrameLength)
        {
            evt.appValue.unifi_Value_union.connectionInfo.associationRspFrame = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionInfo.associationRspFrameLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.associationRspFrame, evt.appValue.unifi_Value_union.connectionInfo.associationRspFrameLength);
        }
        evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElementsLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElements = NULL;
        if (evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElementsLength)
        {
            evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElements = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElementsLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElements, evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElementsLength);
        }
        evt.appValue.unifi_Value_union.connectionInfo.assocReqCapabilities =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocReqListenIntervalBeacons =  event_unpack_CsrUint16(&buffer);
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.assocReqApAddress.data, 6);
        evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElementsLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElements = NULL;
        if (evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElementsLength)
        {
            evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElements = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElementsLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElements, evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElementsLength);
        }
        evt.appValue.unifi_Value_union.connectionInfo.assocRspResult = (unifi_IEEE80211Result) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocRspCapabilityInfo =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocRspAssociationId =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElementsLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElements = NULL;
        if (evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElementsLength)
        {
            evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElements = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElementsLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElements, evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElementsLength);
        }
        break;
    case unifi_CoexInfoValue:
        evt.appValue.unifi_Value_union.coexInfo.hasTrafficData = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentTrafficType = (unifi_TrafficType) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentPeriodMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentPowerSave = (unifi_PowerSaveLevel) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentCoexPeriodMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentCoexLatencyMs =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.hasBtDevice = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentBlackoutDurationUs =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentBlackoutPeriodUs =  event_unpack_CsrUint32(&buffer);
        evt.appValue.unifi_Value_union.coexInfo.currentCoexScheme = (unifi_CoexScheme) event_unpack_CsrUint8(&buffer);
        break;
    case unifi_CalibrationDataValue:
        evt.appValue.unifi_Value_union.calibrationData.length =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.calibrationData.data = NULL;
        if (evt.appValue.unifi_Value_union.calibrationData.length)
        {
            evt.appValue.unifi_Value_union.calibrationData.data = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.calibrationData.length);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.calibrationData.data, evt.appValue.unifi_Value_union.calibrationData.length);
        }
        break;
    case unifi_ConnectionConfigValue:
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionConfig.ssid.ssid, 32);
        evt.appValue.unifi_Value_union.connectionConfig.ssid.length =  event_unpack_CsrUint8(&buffer);
        event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionConfig.bssid.data, 6);
        evt.appValue.unifi_Value_union.connectionConfig.bssType = (unifi_BSSType) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.ifIndex = (unifi_RadioIF) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.privacyMode = (unifi_80211PrivacyMode) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.authModeMask =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.encryptionModeMask =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements = NULL;
        if (evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength)
        {
            evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements = (CsrUint8*)CsrPmalloc(evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength);
            event_unpack_buffer(&buffer, evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements, evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength);
        }
        evt.appValue.unifi_Value_union.connectionConfig.wmmQosInfo =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.adhocJoinOnly = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.connectionConfig.adhocChannel =  event_unpack_CsrUint8(&buffer);
        break;
    case unifi_CcxConfigValue:
        evt.appValue.unifi_Value_union.ccxConfig.keepAliveTimeMs =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.ccxConfig.apRoamingEnabled = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.ccxConfig.measurementsMask =  event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.ccxConfig.ccxRadioMgtEnabled = (CsrBool) event_unpack_CsrUint16(&buffer);
        break;
    case unifi_PowerConfigValue:
        evt.appValue.unifi_Value_union.powerConfig.powerSaveLevel = (unifi_PowerSaveLevel) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.powerConfig.listenIntervalBeacons =  event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.powerConfig.rxDtims = (CsrBool) event_unpack_CsrUint16(&buffer);
        evt.appValue.unifi_Value_union.powerConfig.d3AutoScanMode = (unifi_D3AutoScanMode) event_unpack_CsrUint8(&buffer);
        break;
    case unifi_HostConfigValue:
        evt.appValue.unifi_Value_union.hostConfig.powerMode = (unifi_HostPowerMode) event_unpack_CsrUint8(&buffer);
        evt.appValue.unifi_Value_union.hostConfig.applicationDataPeriodMs =  event_unpack_CsrUint16(&buffer);
        break;
    default:
        break;
    };

    unifi_mgt_set_value_req(context, evt.appHandle, &evt.appValue);

    switch(evt.appValue.id)
    {
    case unifi_CloakedSsidConfigValue:
        CsrPfree(evt.appValue.unifi_Value_union.cloakedSsids.cloakedSsids);
        break;
    case unifi_ScanConfigValue:
        CsrPfree(evt.appValue.unifi_Value_union.scanConfig.passiveChannelList);
        break;
    case unifi_VersionsValue:
        CsrPfree(evt.appValue.unifi_Value_union.versions.smeIdString);
        break;
    case unifi_ConnectionInfoValue:
        CsrPfree(evt.appValue.unifi_Value_union.connectionInfo.beaconFrame);
        CsrPfree(evt.appValue.unifi_Value_union.connectionInfo.associationReqFrame);
        CsrPfree(evt.appValue.unifi_Value_union.connectionInfo.associationRspFrame);
        CsrPfree(evt.appValue.unifi_Value_union.connectionInfo.assocScanInfoElements);
        CsrPfree(evt.appValue.unifi_Value_union.connectionInfo.assocReqInfoElements);
        CsrPfree(evt.appValue.unifi_Value_union.connectionInfo.assocRspInfoElements);
        break;
    case unifi_CalibrationDataValue:
        CsrPfree(evt.appValue.unifi_Value_union.calibrationData.data);
        break;
    case unifi_ConnectionConfigValue:
        CsrPfree(evt.appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements);
        break;
    default:
        break;
    };
}

static void event_to_unifi_mgt_tspec_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtTspecReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    evt.action = (unifi_ListAction) event_unpack_CsrUint8(&buffer);
    evt.transactionId =  event_unpack_CsrUint32(&buffer);
    evt.strict = (CsrBool) event_unpack_CsrUint16(&buffer);
    evt.ctrlMask =  event_unpack_CsrUint8(&buffer);
    evt.tspecLength =  event_unpack_CsrUint16(&buffer);
    evt.tspec = NULL;
    if (evt.tspecLength)
    {
        evt.tspec = (CsrUint8*)CsrPmalloc(evt.tspecLength);
        event_unpack_buffer(&buffer, evt.tspec, evt.tspecLength);
    }
    evt.tclasLength =  event_unpack_CsrUint16(&buffer);
    evt.tclas = NULL;
    if (evt.tclasLength)
    {
        evt.tclas = (CsrUint8*)CsrPmalloc(evt.tclasLength);
        event_unpack_buffer(&buffer, evt.tclas, evt.tclasLength);
    }

    unifi_mgt_tspec_req(context, evt.appHandle, evt.action, evt.transactionId, evt.strict, evt.ctrlMask, evt.tspecLength, evt.tspec, evt.tclasLength, evt.tclas);

    CsrPfree(evt.tspec);
    CsrPfree(evt.tclas);
}

static void event_to_unifi_mgt_wifi_flightmode_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtWifiFlightmodeReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    event_unpack_buffer(&buffer, evt.address.data, 6);
    evt.mibFilesCount =  event_unpack_CsrUint16(&buffer);
    evt.mibFiles = NULL;
    if (evt.mibFilesCount)
    {
        CsrUint16 i1;
        evt.mibFiles = (unifi_DataBlock*)CsrPmalloc(sizeof(unifi_DataBlock) * evt.mibFilesCount);
        for(i1 = 0; i1 < evt.mibFilesCount; i1++)
        {
            evt.mibFiles[i1].length =  event_unpack_CsrUint16(&buffer);
            evt.mibFiles[i1].data = NULL;
            if (evt.mibFiles[i1].length)
            {
                evt.mibFiles[i1].data = (CsrUint8*)CsrPmalloc(evt.mibFiles[i1].length);
                event_unpack_buffer(&buffer, evt.mibFiles[i1].data, evt.mibFiles[i1].length);
            }
        }
    }

    unifi_mgt_wifi_flightmode_req(context, evt.appHandle, &evt.address, evt.mibFilesCount, evt.mibFiles);

    {
        CsrUint16 i1;
        for(i1 = 0; i1 < evt.mibFilesCount; i1++)
        {
            CsrPfree(evt.mibFiles[i1].data);
        }
    }
    CsrPfree(evt.mibFiles);
}

static void event_to_unifi_mgt_wifi_off_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtWifiOffReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);

    unifi_mgt_wifi_off_req(context, evt.appHandle);

}

static void event_to_unifi_mgt_wifi_on_req(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 length)
{
    CsrUint8* buffer = &inputbuffer[6];
    UnifiMgtWifiOnReq_Evt evt;

    evt.appHandle = (void*) event_unpack_CsrUint32(&buffer);
    event_unpack_buffer(&buffer, evt.address.data, 6);
    evt.mibFilesCount =  event_unpack_CsrUint16(&buffer);
    evt.mibFiles = NULL;
    if (evt.mibFilesCount)
    {
        CsrUint16 i1;
        evt.mibFiles = (unifi_DataBlock*)CsrPmalloc(sizeof(unifi_DataBlock) * evt.mibFilesCount);
        for(i1 = 0; i1 < evt.mibFilesCount; i1++)
        {
            evt.mibFiles[i1].length =  event_unpack_CsrUint16(&buffer);
            evt.mibFiles[i1].data = NULL;
            if (evt.mibFiles[i1].length)
            {
                evt.mibFiles[i1].data = (CsrUint8*)CsrPmalloc(evt.mibFiles[i1].length);
                event_unpack_buffer(&buffer, evt.mibFiles[i1].data, evt.mibFiles[i1].length);
            }
        }
    }

    unifi_mgt_wifi_on_req(context, evt.appHandle, &evt.address, evt.mibFilesCount, evt.mibFiles);

    {
        CsrUint16 i1;
        for(i1 = 0; i1 < evt.mibFilesCount; i1++)
        {
            CsrPfree(evt.mibFiles[i1].data);
        }
    }
    CsrPfree(evt.mibFiles);
}



typedef void (*event_to_fn)(FsmContext* context, CsrUint8* inputbuffer, CsrUint16 size);

static const event_to_fn fnlookup1[56] = {
        event_to_unifi_mgt_wifi_on_req,
        NULL,
        event_to_unifi_mgt_wifi_off_req,
        NULL,
        NULL,
        event_to_unifi_mgt_wifi_flightmode_req,
        NULL,
        event_to_unifi_mgt_set_value_req,
        NULL,
        event_to_unifi_mgt_get_value_req,
        NULL,
        event_to_unifi_mgt_mib_set_req,
        NULL,
        event_to_unifi_mgt_mib_get_req,
        NULL,
        event_to_unifi_mgt_mib_get_next_req,
        NULL,
        event_to_unifi_mgt_scan_full_req,
        NULL,
        event_to_unifi_mgt_scan_results_get_req,
        NULL,
        NULL,
        event_to_unifi_mgt_connect_req,
        NULL,
        NULL,
        NULL,
        event_to_unifi_mgt_disconnect_req,
        NULL,
        event_to_unifi_mgt_multicast_address_req,
        NULL,
        NULL,
        NULL,
        event_to_unifi_mgt_pmkid_req,
        NULL,
        event_to_unifi_mgt_key_req,
        NULL,
        event_to_unifi_mgt_packet_filter_set_req,
        NULL,
        event_to_unifi_mgt_tspec_req,
        NULL,
        NULL,
        event_to_unifi_mgt_scan_results_flush_req,
        NULL,
        event_to_unifi_mgt_blacklist_req,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        event_to_unifi_mgt_event_mask_set_req,
        NULL,
        event_to_unifi_mgt_restricted_access_enable_req,
        NULL,
        event_to_unifi_mgt_restricted_access_disable_req,
        NULL,

};


CsrBool remote_mgt_signal_receive(FsmContext* context, CsrUint8* buffer, CsrUint16 size)
{
    CsrUint8* tempbuffer = buffer;
    CsrUint16 id = event_unpack_CsrUint16(&tempbuffer);

    if (id >= 0x9001 &&
        id <= 0x9038)
    {
        if (fnlookup1[id - 0x9001])
        {
            (*fnlookup1[id - 0x9001])(context, buffer, size);
            return TRUE;
        }
    }

    return FALSE;
}
