/**
* $Id: pmc_registers.h 9119 2008-06-09 11:50:52Z joda $
*/

#include <arch-uniphier2m/uniphier2m_addr.h>

#ifndef SDIOBLK_H
#define SDIOBLK_H


#define reg_prbsl          ((volatile uint16_t*) PMICOM0_PRBSL)

/*
 * GPIO registers
 */
#define reg_gpio6  ((volatile uint32_t*) PMICOM0_GPIOC6CTRL)
#define reg_gpio7  ((volatile uint32_t*) PMICOM0_GPIOC7CTRL)


/*
 * Registers described in "SD Card Interface (SDIO)"
 */
#define reg_sd_cmd          ((volatile uint16_t*) PSTREAM_SD_CMD)
#define reg_sd_portsel      ((volatile uint16_t*) PSTREAM_SD_PORTSEL)

/* TODO */
#define reg_sd_arg          ((volatile uint32_t*) PSTREAM_SD_ARG0)
#define reg_sd_arg0         ((volatile uint16_t*) PSTREAM_SD_ARG0)
#define reg_sd_arg1         ((volatile uint16_t*) PSTREAM_SD_ARG1)
#define reg_sd_stop         ((volatile uint16_t*) PSTREAM_SD_STOP)
#define reg_sd_seccnt       ((volatile uint16_t*) PSTREAM_SD_SECCNT)
#define reg_sd_rsp0         ((volatile uint16_t*) PSTREAM_SD_RSP0)
#define reg_sd_rsp1         ((volatile uint16_t*) PSTREAM_SD_RSP1)
#define reg_sd_rsp2         ((volatile uint16_t*) PSTREAM_SD_RSP2)
#define reg_sd_rsp3         ((volatile uint16_t*) PSTREAM_SD_RSP3)
#define reg_sd_rsp4         ((volatile uint16_t*) PSTREAM_SD_RSP4)
#define reg_sd_rsp5         ((volatile uint16_t*) PSTREAM_SD_RSP5)
#define reg_sd_rsp6         ((volatile uint16_t*) PSTREAM_SD_RSP6)
#define reg_sd_rsp7         ((volatile uint16_t*) PSTREAM_SD_RSP7)
#define reg_sd_info1        ((volatile uint16_t*) PSTREAM_SD_INFO1)

#define reg_sd_info2        ((volatile uint16_t*) PSTREAM_SD_INFO2)
# define BIT_CBSY 14
# define BIT_BWE 9
# define BIT_BRE 8
#define reg_sd_info1_mask   ((volatile uint16_t*) PSTREAM_SD_INFO1_MASK)
#define reg_sd_info2_mask   ((volatile uint16_t*) PSTREAM_SD_INFO2_MASK)
#define reg_sd_clk_ctrl     ((volatile uint16_t*) PSTREAM_SD_CLK_CTRL)
#define reg_sd_size         ((volatile uint16_t*) PSTREAM_SD_SIZE)
#define reg_sd_option       ((volatile uint16_t*) PSTREAM_SD_OPTION)

#define reg_sd_err_sts1     ((volatile uint16_t*) PSTREAM_SD_ERR_STS1)
#define reg_sd_err_sts2     ((volatile uint16_t*) PSTREAM_SD_ERR_STS2)
#define reg_sd_buf0         ((volatile uint16_t*) PSTREAM_SD_BUF0)

#define reg_sdio_mode       ((volatile uint16_t*) PSTREAM_SDIO_MODE)
#define reg_sdio_info1      ((volatile uint16_t*) PSTREAM_SDIO_INFO1)
#define reg_sdio_info1_mask ((volatile uint16_t*) PSTREAM_SDIO_INFO1_MASK)

#define reg_cc_ext_mode     ((volatile uint16_t*) PSTREAM_CC_EXT_MODE)

#define reg_soft_rst        ((volatile uint16_t*) PSTREAM_SOFT_RST)
#define reg_version         ((volatile uint16_t*) PSTREAM_VERSION)

#define reg_sd_pwr          ((volatile uint16_t*) PSTREAM_SD_PWR)
#define reg_ext_sdio        ((volatile uint16_t*) PSTREAM_EXT_SDIO)
#define reg_ext_wp          ((volatile uint16_t*) PSTREAM_EXT_WP)
#define reg_ext_cd          ((volatile uint16_t*) PSTREAM_EXT_CD)
#define reg_sd_cd_dat3      ((volatile uint16_t*) PSTREAM_EXT_DAT3)
#define reg_sd_cd_mask      ((volatile uint16_t*) PSTREAM_EXT_CD_MASK)
#define reg_sd_cd_dat3_mask ((volatile uint16_t*) PSTREAM_EXT_CD_DAT3_MASK)


/*
 * Registers described in "Explanation of some Register"
 */
#define reg_clkenreg7  ((volatile uint16_t*) PMICOM0_CLKENREG7)
# define BIT_CEN_BSSI1 0
# define BIT_CEN_BSSI2 1
# define BIT_CEN_SDIO1 2
# define BIT_CEN_USB   4
# define BIT_CEN_SDMA  5
#define reg_rstctl61   ((volatile uint16_t*) PMICOM0_RSTCTL61)
# define BIT_nSTRMCTL   0
# define BIT_nBSSICTL1  8
# define BIT_nBSSICTL2  9
# define BIT_nSDIOCTL  10
# define BIT_nUSBCTL   11
#define reg_ioadrvreg1 ((volatile uint32_t*) PMICOM0_IODRVREG0)
#define reg_iopupdreg0 ((volatile uint32_t*) PMICOM0_IOPUPDREG0)
# define BIT_IOREG_AB 18
# define BIT_IOREG_AC 19
#define reg_ioaodirreg ((volatile uint32_t*) PMICOM0_IOAODIRREG)
# define BIT_AODIR_M 2

#define reg_iodrvreg1 ((volatile uint32_t*)  PMICOM0_IODRVREG1)
# define BIT_IODRV_AJ 24

/*
 * Registers described in "Stream DMA"
 */
#define reg_sbuf_stadr0  ((volatile uint32_t*) PSTREAM_SBUF_STADRO)
#define reg_sbuf_width0  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH0)
#define reg_sbuf_in0     ((volatile uint32_t*) PSTREAM_SBUF_IN0)
#define reg_sbuf_out0    ((volatile uint32_t*) PSTREAM_SBUF_OUT0)
#define reg_sbuf_sh0     ((volatile uint32_t*) PSTREAM_SBUF_SH0)
#define reg_sbuf_wptr0   ((volatile uint32_t*) PSTREAM_SBUF_WPTR0)
#define reg_sbuf_rptr0   ((volatile uint32_t*) PSTREAM_SBUF_RPTR0)
#define reg_sbuf_stadr1  ((volatile uint32_t*) PSTREAM_SBUF_STADR1)
#define reg_sbuf_width1  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH1)
#define reg_sbuf_in1     ((volatile uint32_t*) PSTREAM_SBUF_IN1)
#define reg_sbuf_out1    ((volatile uint32_t*) PSTREAM_SBUF_OUT1)
#define reg_sbuf_sh1     ((volatile uint32_t*) PSTREAM_SBUF_SH1)
#define reg_sbuf_wptr1   ((volatile uint32_t*) PSTREAM_SBUF_WPTR1)
#define reg_sbuf_rptr1   ((volatile uint32_t*) PSTREAM_SBUF_RPTR1)
#define reg_sbuf_stadr2  ((volatile uint32_t*) PSTREAM_SBUF_STADR2)
#define reg_sbuf_width2  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH2)
#define reg_sbuf_in2     ((volatile uint32_t*) PSTREAM_SBUF_IN2)
#define reg_sbuf_out2    ((volatile uint32_t*) PSTREAM_SBUF_OUT2)
#define reg_sbuf_sh2     ((volatile uint32_t*) PSTREAM_SBUF_SH2)
#define reg_sbuf_wptr2   ((volatile uint32_t*) PSTREAM_SBUF_WPTR2)
#define reg_sbuf_rptr2   ((volatile uint32_t*) PSTREAM_SBUF_RPTR2)
#define reg_sbuf_stadr3  ((volatile uint32_t*) PSTREAM_SBUF_STADR3)
#define reg_sbuf_width3  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH3)
#define reg_sbuf_in3     ((volatile uint32_t*) PSTREAM_SBUF_IN3)
#define reg_sbuf_out3    ((volatile uint32_t*) PSTREAM_SBUF_OUT3)
#define reg_sbuf_sh3     ((volatile uint32_t*) PSTREAM_SBUF_SH3)
#define reg_sbuf_wptr3   ((volatile uint32_t*) PSTREAM_SBUF_WPTR3)
#define reg_sbuf_rptr3   ((volatile uint32_t*) PSTREAM_SBUF_RPTR3)
#define reg_sbuf_stadr4  ((volatile uint32_t*) PSTREAM_SBUF_STADR4)
#define reg_sbuf_width4  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH4)
#define reg_sbuf_in4     ((volatile uint32_t*) PSTREAM_SBUF_IN4)
#define reg_sbuf_out4    ((volatile uint32_t*) PSTREAM_SBUF_OUT4)
#define reg_sbuf_sh4     ((volatile uint32_t*) PSTREAM_SBUF_SH4)
#define reg_sbuf_wptr4   ((volatile uint32_t*) PSTREAM_SBUF_WPTR4)
#define reg_sbuf_rptr4   ((volatile uint32_t*) PSTREAM_SBUF_RPTR4)
#define reg_sbuf_stadr5  ((volatile uint32_t*) PSTREAM_SBUF_STADR5)
#define reg_sbuf_width5  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH5)
#define reg_sbuf_in5     ((volatile uint32_t*) PSTREAM_SBUF_IN5)
#define reg_sbuf_out5    ((volatile uint32_t*) PSTREAM_SBUF_OUT5)
#define reg_sbuf_sh5     ((volatile uint32_t*) PSTREAM_SBUF_SH5)
#define reg_sbuf_wptr5   ((volatile uint32_t*) PSTREAM_SBUF_WPTR5)
#define reg_sbuf_rptr5   ((volatile uint32_t*) PSTREAM_SBUF_RPTR5)
#define reg_sbuf_stadr6  ((volatile uint32_t*) PSTREAM_SBUF_STADR6)
#define reg_sbuf_width6  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH6)
#define reg_sbuf_in6     ((volatile uint32_t*) PSTREAM_SBUF_IN6)
#define reg_sbuf_out6    ((volatile uint32_t*) PSTREAM_SBUF_OUT6)
#define reg_sbuf_sh6     ((volatile uint32_t*) PSTREAM_SBUF_SH6)
#define reg_sbuf_wptr6   ((volatile uint32_t*) PSTREAM_SBUF_WPTR6)
#define reg_sbuf_rptr6   ((volatile uint32_t*) PSTREAM_SBUF_RPTR6)
#define reg_sbuf_stadr7  ((volatile uint32_t*) PSTREAM_SBUF_STADR7)
#define reg_sbuf_width7  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH7)
#define reg_sbuf_in7     ((volatile uint32_t*) PSTREAM_SBUF_IN7)
#define reg_sbuf_out7    ((volatile uint32_t*) PSTREAM_SBUF_OUT7)
#define reg_sbuf_sh7     ((volatile uint32_t*) PSTREAM_SBUF_SH7)
#define reg_sbuf_wptr7   ((volatile uint32_t*) PSTREAM_SBUF_WPTR7)
#define reg_sbuf_rptr7   ((volatile uint32_t*) PSTREAM_SBUF_RPTR7)
#define reg_sbuf_stadr8  ((volatile uint32_t*) PSTREAM_SBUF_STADR8)
#define reg_sbuf_width8  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH8)
#define reg_sbuf_in8     ((volatile uint32_t*) PSTREAM_SBUF_IN8)
#define reg_sbuf_out8    ((volatile uint32_t*) PSTREAM_SBUF_OUT8)
#define reg_sbuf_sh8     ((volatile uint32_t*) PSTREAM_SBUF_SH8)
#define reg_sbuf_wptr8   ((volatile uint32_t*) PSTREAM_SBUF_WPTR8)
#define reg_sbuf_rptr8   ((volatile uint32_t*) PSTREAM_SBUF_RPTR8)
#define reg_sbuf_stadr9  ((volatile uint32_t*) PSTREAM_SBUF_STADR9)
#define reg_sbuf_width9  ((volatile uint32_t*) PSTREAM_SBUF_WIDTH9)
#define reg_sbuf_in9     ((volatile uint32_t*) PSTREAM_SBUF_IN9)
#define reg_sbuf_out9    ((volatile uint32_t*) PSTREAM_SBUF_OUT9)
#define reg_sbuf_sh9     ((volatile uint32_t*) PSTREAM_SBUF_SH9)
#define reg_sbuf_wptr9   ((volatile uint32_t*) PSTREAM_SBUF_WPTR9)
#define reg_sbuf_rptr9   ((volatile uint32_t*) PSTREAM_SBUF_RPTR9)
#define reg_sbuf_stadr10 ((volatile uint32_t*) PSTREAM_SBUF_STADR10)
#define reg_sbuf_width10 ((volatile uint32_t*) PSTREAM_SBUF_WIDTH10)
#define reg_sbuf_in10    ((volatile uint32_t*) PSTREAM_SBUF_IN10)
#define reg_sbuf_out10   ((volatile uint32_t*) PSTREAM_SBUF_OUT10)
#define reg_sbuf_sh10    ((volatile uint32_t*) PSTREAM_SBUF_SH10)
#define reg_sbuf_wptr10  ((volatile uint32_t*) PSTREAM_SBUF_WPTR10)
#define reg_sbuf_rptr10  ((volatile uint32_t*) PSTREAM_SBUF_RPTR10)
#define reg_sbuf_stadr11 ((volatile uint32_t*) PSTREAM_SBUF_STADR11)
#define reg_sbuf_width11 ((volatile uint32_t*) PSTREAM_SBUF_WIDTH11)
#define reg_sbuf_in11    ((volatile uint32_t*) PSTREAM_SBUF_IN11)
#define reg_sbuf_out11   ((volatile uint32_t*) PSTREAM_SBUF_OUT11)
#define reg_sbuf_sh11    ((volatile uint32_t*) PSTREAM_SBUF_SH11)
#define reg_sbuf_wptr11  ((volatile uint32_t*) PSTREAM_SBUF_WPTR11)
#define reg_sbuf_rptr11  ((volatile uint32_t*) PSTREAM_SBUF_RPTR11)
#define reg_sbuf_stadr12 ((volatile uint32_t*) PSTREAM_SBUF_STADR12)
#define reg_sbuf_width12 ((volatile uint32_t*) PSTREAM_SBUF_WIDTH12)
#define reg_sbuf_in12    ((volatile uint32_t*) PSTREAM_SBUF_IN12)
#define reg_sbuf_out12   ((volatile uint32_t*) PSTREAM_SBUF_OUT12)
#define reg_sbuf_sh12    ((volatile uint32_t*) PSTREAM_SBUF_SH12)
#define reg_sbuf_wptr12  ((volatile uint32_t*) PSTREAM_SBUF_WPTR12)
#define reg_sbuf_rptr12  ((volatile uint32_t*) PSTREAM_SBUF_RPTR12)
#define reg_sbuf_stadr13 ((volatile uint32_t*) PSTREAM_SBUF_STADR13)
#define reg_sbuf_width13 ((volatile uint32_t*) PSTREAM_SBUF_WIDTH13)
#define reg_sbuf_in13    ((volatile uint32_t*) PSTREAM_SBUF_IN13)
#define reg_sbuf_out13   ((volatile uint32_t*) PSTREAM_SBUF_OUT13)
#define reg_sbuf_sh13    ((volatile uint32_t*) PSTREAM_SBUF_SH13)
#define reg_sbuf_wptr13  ((volatile uint32_t*) PSTREAM_SBUF_WPTR13)
#define reg_sbuf_rptr13  ((volatile uint32_t*) PSTREAM_SBUF_RPTR13)
#define reg_sbuf_data    ((volatile uint32_t*) PSTREAM_SBUF_DATA)
#define reg_sbuf_sel     ((volatile uint32_t*) PSTREAM_SBUF_SEL)
#define reg_sbuf_clr     ((volatile uint32_t*) PSTREAM_SBUF_CLR)
#define reg_dma_cnt0     ((volatile uint32_t*) PSTREAM_DMA_CNT0)
#define reg_dma_size0    ((volatile uint32_t*) PSTREAM_DMA_SIZE0)
#define reg_dma_trans0   ((volatile uint32_t*) PSTREAM_DMA_TRANS0)
#define reg_dma_intcnt0  ((volatile uint32_t*) PSTREAM_DMA_INTCNT0)
#define reg_dma_mrstrt0  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT0)
#define reg_dma_mrsize0  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE0)
#define reg_dma_mwstrt0  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT0)
#define reg_dma_mwsize0  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE0)
#define reg_dma_cnt1     ((volatile uint32_t*) PSTREAM_DMA_CNT1)
#define reg_dma_size1    ((volatile uint32_t*) PSTREAM_DMA_SIZE1)
#define reg_dma_trans1   ((volatile uint32_t*) PSTREAM_DMA_TRANS1)
#define reg_dma_intcnt1  ((volatile uint32_t*) PSTREAM_DMA_INTCNT1)
#define reg_dma_mrstrt1  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT1)
#define reg_dma_mrsize1  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE1)
#define reg_dma_mwstrt1  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT1)
#define reg_dma_mwsize1  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE1)
#define reg_dma_cnt2     ((volatile uint32_t*) PSTREAM_DMA_CNT2)
#define reg_dma_size2    ((volatile uint32_t*) PSTREAM_DMA_SIZE2)
#define reg_dma_trans2   ((volatile uint32_t*) PSTREAM_DMA_TRANS2)
#define reg_dma_intcnt2  ((volatile uint32_t*) PSTREAM_DMA_INTCNT2)
#define reg_dma_mrstrt2  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT2)
#define reg_dma_mrsize2  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE2)
#define reg_dma_mwstrt2  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT2)
#define reg_dma_mwsize2  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE2)
#define reg_dma_cnt3     ((volatile uint32_t*) PSTREAM_DMA_CNT3)
#define reg_dma_size3    ((volatile uint32_t*) PSTREAM_DMA_SIZE3)
#define reg_dma_trans3   ((volatile uint32_t*) PSTREAM_DMA_TRANS3)
#define reg_dma_intcnt3  ((volatile uint32_t*) PSTREAM_DMA_INTCNT3)
#define reg_dma_mrstrt3  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT3)
#define reg_dma_mrsize3  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE3)
#define reg_dma_mwstrt3  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT3)
#define reg_dma_mwsize3  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE3)
#define reg_dma_cnt4     ((volatile uint32_t*) PSTREAM_DMA_CNT4)
#define reg_dma_size4    ((volatile uint32_t*) PSTREAM_DMA_SIZE4)
#define reg_dma_trans4   ((volatile uint32_t*) PSTREAM_DMA_TRANS4)
#define reg_dma_intcnt4  ((volatile uint32_t*) PSTREAM_DMA_INTCNT4)
#define reg_dma_mrstrt4  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT4)
#define reg_dma_mrsize4  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE4)
#define reg_dma_mwstrt4  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT4)
#define reg_dma_mwsize4  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE4)
#define reg_dma_cnt5     ((volatile uint32_t*) PSTREAM_DMA_CNT5)
#define reg_dma_size5    ((volatile uint32_t*) PSTREAM_DMA_SIZE5)
#define reg_dma_trans5   ((volatile uint32_t*) PSTREAM_DMA_TRANS5)
#define reg_dma_intcnt5  ((volatile uint32_t*) PSTREAM_DMA_INTCNT5)
#define reg_dma_mrstrt5  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT5)
#define reg_dma_mrsize5  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE5)
#define reg_dma_mwstrt5  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT5)
#define reg_dma_mwsize5  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE5)
#define reg_dma_cnt6     ((volatile uint32_t*) PSTREAM_DMA_CNT6)
#define reg_dma_size6    ((volatile uint32_t*) PSTREAM_DMA_SIZE6)
#define reg_dma_trans6   ((volatile uint32_t*) PSTREAM_DMA_TRANS6)
#define reg_dma_intcnt6  ((volatile uint32_t*) PSTREAM_DMA_INTCNT6)
#define reg_dma_mrstrt6  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT6)
#define reg_dma_mrsize6  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE6)
#define reg_dma_mwstrt6  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT6)
#define reg_dma_mwsize6  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE6)
#define reg_dma_cnt7     ((volatile uint32_t*) PSTREAM_DMA_CNT7)
#define reg_dma_size7    ((volatile uint32_t*) PSTREAM_DMA_SIZE7)
#define reg_dma_trans7   ((volatile uint32_t*) PSTREAM_DMA_TRANS7)
#define reg_dma_intcnt7  ((volatile uint32_t*) PSTREAM_DMA_INTCNT7)
#define reg_dma_mrstrt7  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT7)
#define reg_dma_mrsize7  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE7)
#define reg_dma_mwstrt7  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT7)
#define reg_dma_mwsize7  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE7)
#define reg_dma_cnt8     ((volatile uint32_t*) PSTREAM_DMA_CNT8)
#define reg_dma_size8    ((volatile uint32_t*) PSTREAM_DMA_SIZE8)
#define reg_dma_trans8   ((volatile uint32_t*) PSTREAM_DMA_TRANS8)
#define reg_dma_intcnt8  ((volatile uint32_t*) PSTREAM_DMA_INTCNT8)
#define reg_dma_mrstrt8  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT8)
#define reg_dma_mrsize8  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE8)
#define reg_dma_mwstrt8  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT8)
#define reg_dma_mwsize8  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE8)
#define reg_dma_cnt9     ((volatile uint32_t*) PSTREAM_DMA_CNT9)
#define reg_dma_size9    ((volatile uint32_t*) PSTREAM_DMA_SIZE9)
#define reg_dma_trans9   ((volatile uint32_t*) PSTREAM_DMA_TRANS9)
#define reg_dma_intcnt9  ((volatile uint32_t*) PSTREAM_DMA_INTCNT9)
#define reg_dma_mrstrt9  ((volatile uint32_t*) PSTREAM_DMA_MRSTRT9)
#define reg_dma_mrsize9  ((volatile uint32_t*) PSTREAM_DMA_MRSIZE9)
#define reg_dma_mwstrt9  ((volatile uint32_t*) PSTREAM_DMA_MWSTRT9)
#define reg_dma_mwsize9  ((volatile uint32_t*) PSTREAM_DMA_MWSIZE9)
#define reg_dma_cnt10    ((volatile uint32_t*) PSTREAM_DMA_CNT10)
#define reg_dma_size10   ((volatile uint32_t*) PSTREAM_DMA_SIZE10)
#define reg_dma_trans10  ((volatile uint32_t*) PSTREAM_DMA_TRANS10)
#define reg_dma_intcnt10 ((volatile uint32_t*) PSTREAM_DMA_INTCNT10)
#define reg_dma_mrstrt10 ((volatile uint32_t*) PSTREAM_DMA_MRSTRT10)
#define reg_dma_mrsize10 ((volatile uint32_t*) PSTREAM_DMA_MRSIZE10)
#define reg_dma_mwstrt10 ((volatile uint32_t*) PSTREAM_DMA_MWSTRT10)
#define reg_dma_mwsize10 ((volatile uint32_t*) PSTREAM_DMA_MWSIZE10)
#define reg_dma_cnt11    ((volatile uint32_t*) PSTREAM_DMA_CNT11)
#define reg_dma_size11   ((volatile uint32_t*) PSTREAM_DMA_SIZE11)
#define reg_dma_trans11  ((volatile uint32_t*) PSTREAM_DMA_TRANS11)
#define reg_dma_intcnt11 ((volatile uint32_t*) PSTREAM_DMA_INTCNT11)
#define reg_dma_mrstrt11 ((volatile uint32_t*) PSTREAM_DMA_MRSTRT11)
#define reg_dma_mrsize11 ((volatile uint32_t*) PSTREAM_DMA_MRSIZE11)
#define reg_dma_mwstrt11 ((volatile uint32_t*) PSTREAM_DMA_MWSTRT11)
#define reg_dma_mwsize11 ((volatile uint32_t*) PSTREAM_DMA_MWSIZE11)
#define reg_dma_cnt12    ((volatile uint32_t*) PSTREAM_DMA_CNT12)
#define reg_dma_size12   ((volatile uint32_t*) PSTREAM_DMA_SIZE12)
#define reg_dma_trans12  ((volatile uint32_t*) PSTREAM_DMA_TRANS12)
#define reg_dma_intcnt12 ((volatile uint32_t*) PSTREAM_DMA_INTCNT12)
#define reg_dma_mrstrt12 ((volatile uint32_t*) PSTREAM_DMA_MRSTRT12)
#define reg_dma_mrsize12 ((volatile uint32_t*) PSTREAM_DMA_MRSIZE12)
#define reg_dma_mwstrt12 ((volatile uint32_t*) PSTREAM_DMA_MWSTRT12)
#define reg_dma_mwsize12 ((volatile uint32_t*) PSTREAM_DMA_MWSIZE12)
#define reg_dma_cnt13    ((volatile uint32_t*) PSTREAM_DMA_CNT13)
#define reg_dma_size13   ((volatile uint32_t*) PSTREAM_DMA_SIZE13)
#define reg_dma_trans13  ((volatile uint32_t*) PSTREAM_DMA_TRANS13)
#define reg_dma_intcnt13 ((volatile uint32_t*) PSTREAM_DMA_INTCNT13)
#define reg_dma_mrstrt13 ((volatile uint32_t*) PSTREAM_DMA_MRSTRT13)
#define reg_dma_mrsize13 ((volatile uint32_t*) PSTREAM_DMA_MRSIZE13)
#define reg_dma_mwstrt13 ((volatile uint32_t*) PSTREAM_DMA_MWSTRT13)
#define reg_dma_mwsize13 ((volatile uint32_t*) PSTREAM_DMA_MWSIZE13)
#define reg_dma_sts      ((volatile uint32_t*) PSTREAM_DMA_STS)
#define reg_soft_rst2    ((volatile uint32_t*) PSTREAM_SOFT_RST2)
#define reg_clk_ctrl     ((volatile uint32_t*) PSTREAM_CLK_CTRL)
#define reg_clk_ctrl2    ((volatile uint32_t*) PSTREAM_CLK_CTRL2)
#define reg_ch_event0    ((volatile uint32_t*) PSTREAM_CH_EVENT0)
#define reg_ch_event1    ((volatile uint32_t*) PSTREAM_CH_EVENT1)
#define reg_ch_event2    ((volatile uint32_t*) PSTREAM_CH_EVENT2)
#define reg_ch_event3    ((volatile uint32_t*) PSTREAM_CH_EVENT3)
#define reg_ch_event4    ((volatile uint32_t*) PSTREAM_CH_EVENT4)
#define reg_ch_event5    ((volatile uint32_t*) PSTREAM_CH_EVENT5)
#define reg_ch_event6    ((volatile uint32_t*) PSTREAM_CH_EVENT6)
#define reg_ch_event7    ((volatile uint32_t*) PSTREAM_CH_EVENT7)
#define reg_ch_event8    ((volatile uint32_t*) PSTREAM_CH_EVENT8)
#define reg_ch_event9    ((volatile uint32_t*) PSTREAM_CH_EVENT9)
#define reg_ch_event10   ((volatile uint32_t*) PSTREAM_CH_EVENT10)
#define reg_ch_event11   ((volatile uint32_t*) PSTREAM_CH_EVENT11)
#define reg_ch_event12   ((volatile uint32_t*) PSTREAM_CH_EVENT12)
#define reg_ch_event13   ((volatile uint32_t*) PSTREAM_CH_EVENT13)


#endif
