/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#include "fsm/fsm_internal.h"
#include "sme_top_level_fsm/sme_top_level_fsm.h"

/*lint -e725 */

#define INIT_EVENT_HEADER(event,evtid) \
    event->common.id = evtid; \
    event->common.destination = 0; \
    event->common.sender_ = FSM_ENV


void unifi_mgt_blacklist_req(FsmContext* context,
                             void* appHandle,
                             unifi_ListAction action,
                             CsrUint8 setAddressCount,
                             const unifi_MACAddress *setAddresses)
{
    UnifiMgtBlacklistReq_Evt* evt = (UnifiMgtBlacklistReq_Evt*)CsrPmalloc(sizeof(UnifiMgtBlacklistReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_BLACKLIST_REQ_ID);

    evt->appHandle = appHandle;
    evt->action = action;
    evt->setAddressCount = setAddressCount;
    evt->setAddresses = NULL;
    if (setAddressCount)
    {
        CsrUint16 i1;
        evt->setAddresses = (unifi_MACAddress*)CsrPmalloc(sizeof(unifi_MACAddress) * setAddressCount);
        for(i1 = 0; i1 < setAddressCount; i1++)
        {
            CsrMemCpy(evt->setAddresses[i1].data, setAddresses[i1].data, 6);
        }
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_connect_req(FsmContext* context,
                           void* appHandle,
                           const unifi_ConnectionConfig *connectionConfig)
{
    UnifiMgtConnectReq_Evt* evt = (UnifiMgtConnectReq_Evt*)CsrPmalloc(sizeof(UnifiMgtConnectReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_CONNECT_REQ_ID);

    evt->appHandle = appHandle;
    CsrMemCpy(evt->connectionConfig.ssid.ssid, connectionConfig->ssid.ssid, 32);
    evt->connectionConfig.ssid.length = connectionConfig->ssid.length;
    CsrMemCpy(evt->connectionConfig.bssid.data, connectionConfig->bssid.data, 6);
    evt->connectionConfig.bssType = connectionConfig->bssType;
    evt->connectionConfig.ifIndex = connectionConfig->ifIndex;
    evt->connectionConfig.privacyMode = connectionConfig->privacyMode;
    evt->connectionConfig.authModeMask = connectionConfig->authModeMask;
    evt->connectionConfig.encryptionModeMask = connectionConfig->encryptionModeMask;
    evt->connectionConfig.mlmeAssociateReqInformationElementsLength = connectionConfig->mlmeAssociateReqInformationElementsLength;
    evt->connectionConfig.mlmeAssociateReqInformationElements = NULL;
    if (connectionConfig->mlmeAssociateReqInformationElementsLength)
    {
        evt->connectionConfig.mlmeAssociateReqInformationElements = (CsrUint8*)CsrPmalloc(connectionConfig->mlmeAssociateReqInformationElementsLength);
        CsrMemCpy(evt->connectionConfig.mlmeAssociateReqInformationElements, connectionConfig->mlmeAssociateReqInformationElements, connectionConfig->mlmeAssociateReqInformationElementsLength);
    }
    evt->connectionConfig.wmmQosInfo = connectionConfig->wmmQosInfo;
    evt->connectionConfig.adhocJoinOnly = connectionConfig->adhocJoinOnly;
    evt->connectionConfig.adhocChannel = connectionConfig->adhocChannel;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->networkSelectorInstance, evt->common.id);
}

void unifi_mgt_disconnect_req(FsmContext* context,
                              void* appHandle)
{
    UnifiMgtDisconnectReq_Evt* evt = (UnifiMgtDisconnectReq_Evt*)CsrPmalloc(sizeof(UnifiMgtDisconnectReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_DISCONNECT_REQ_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->networkSelectorInstance, evt->common.id);
}

void unifi_mgt_event_mask_set_req(FsmContext* context,
                                  void* appHandle,
                                  CsrUint32 indMask)
{
    UnifiMgtEventMaskSetReq_Evt* evt = (UnifiMgtEventMaskSetReq_Evt*)CsrPmalloc(sizeof(UnifiMgtEventMaskSetReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_EVENT_MASK_SET_REQ_ID);

    evt->appHandle = appHandle;
    evt->indMask = indMask;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_get_value_req(FsmContext* context,
                             void* appHandle,
                             unifi_AppValueId appValueId)
{
    UnifiMgtGetValueReq_Evt* evt = (UnifiMgtGetValueReq_Evt*)CsrPmalloc(sizeof(UnifiMgtGetValueReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_GET_VALUE_REQ_ID);

    evt->appHandle = appHandle;
    evt->appValueId = appValueId;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_key_req(FsmContext* context,
                       void* appHandle,
                       unifi_ListAction action,
                       const unifi_Key *key)
{
    UnifiMgtKeyReq_Evt* evt = (UnifiMgtKeyReq_Evt*)CsrPmalloc(sizeof(UnifiMgtKeyReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_KEY_REQ_ID);

    evt->appHandle = appHandle;
    evt->action = action;
    evt->key.keyType = key->keyType;
    evt->key.keyIndex = key->keyIndex;
    evt->key.wepTxKey = key->wepTxKey;
    {
    CsrUint16 i2;
    for(i2 = 0; i2 < 8; i2++)
    {
        evt->key.keyRsc[i2] = key->keyRsc[i2];
    }
    }
    evt->key.authenticator = key->authenticator;
    CsrMemCpy(evt->key.address.data, key->address.data, 6);
    evt->key.keyLength = key->keyLength;
    CsrMemCpy(evt->key.key, key->key, 32);

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_mib_get_req(FsmContext* context,
                           void* appHandle,
                           CsrUint16 mibAttributeLength,
                           const CsrUint8 *mibAttribute)
{
    UnifiMgtMibGetReq_Evt* evt = (UnifiMgtMibGetReq_Evt*)CsrPmalloc(sizeof(UnifiMgtMibGetReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_MIB_GET_REQ_ID);

    evt->appHandle = appHandle;
    evt->mibAttributeLength = mibAttributeLength;
    evt->mibAttribute = NULL;
    if (mibAttributeLength)
    {
        evt->mibAttribute = (CsrUint8*)CsrPmalloc(mibAttributeLength);
        CsrMemCpy(evt->mibAttribute, mibAttribute, mibAttributeLength);
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->mibAccessInstance, evt->common.id);
}

void unifi_mgt_mib_get_next_req(FsmContext* context,
                                void* appHandle,
                                CsrUint16 mibAttributeLength,
                                const CsrUint8 *mibAttribute)
{
    UnifiMgtMibGetNextReq_Evt* evt = (UnifiMgtMibGetNextReq_Evt*)CsrPmalloc(sizeof(UnifiMgtMibGetNextReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_MIB_GET_NEXT_REQ_ID);

    evt->appHandle = appHandle;
    evt->mibAttributeLength = mibAttributeLength;
    evt->mibAttribute = NULL;
    if (mibAttributeLength)
    {
        evt->mibAttribute = (CsrUint8*)CsrPmalloc(mibAttributeLength);
        CsrMemCpy(evt->mibAttribute, mibAttribute, mibAttributeLength);
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->mibAccessInstance, evt->common.id);
}

void unifi_mgt_mib_set_req(FsmContext* context,
                           void* appHandle,
                           CsrUint16 mibAttributeLength,
                           const CsrUint8 *mibAttribute)
{
    UnifiMgtMibSetReq_Evt* evt = (UnifiMgtMibSetReq_Evt*)CsrPmalloc(sizeof(UnifiMgtMibSetReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_MIB_SET_REQ_ID);

    evt->appHandle = appHandle;
    evt->mibAttributeLength = mibAttributeLength;
    evt->mibAttribute = NULL;
    if (mibAttributeLength)
    {
        evt->mibAttribute = (CsrUint8*)CsrPmalloc(mibAttributeLength);
        CsrMemCpy(evt->mibAttribute, mibAttribute, mibAttributeLength);
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->mibAccessInstance, evt->common.id);
}

void unifi_mgt_multicast_address_req(FsmContext* context,
                                     void* appHandle,
                                     unifi_ListAction action,
                                     CsrUint8 setAddressesCount,
                                     const unifi_MACAddress *setAddresses)
{
    UnifiMgtMulticastAddressReq_Evt* evt = (UnifiMgtMulticastAddressReq_Evt*)CsrPmalloc(sizeof(UnifiMgtMulticastAddressReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_MULTICAST_ADDRESS_REQ_ID);

    evt->appHandle = appHandle;
    evt->action = action;
    evt->setAddressesCount = setAddressesCount;
    evt->setAddresses = NULL;
    if (setAddressesCount)
    {
        CsrUint16 i1;
        evt->setAddresses = (unifi_MACAddress*)CsrPmalloc(sizeof(unifi_MACAddress) * setAddressesCount);
        for(i1 = 0; i1 < setAddressesCount; i1++)
        {
            CsrMemCpy(evt->setAddresses[i1].data, setAddresses[i1].data, 6);
        }
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_packet_filter_set_req(FsmContext* context,
                                     void* appHandle,
                                     CsrUint16 filterLength,
                                     const CsrUint8 *filter,
                                     unifi_PacketFilterMode mode,
                                     const unifi_IPV4Address *arpFilterAddress)
{
    UnifiMgtPacketFilterSetReq_Evt* evt = (UnifiMgtPacketFilterSetReq_Evt*)CsrPmalloc(sizeof(UnifiMgtPacketFilterSetReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_PACKET_FILTER_SET_REQ_ID);

    evt->appHandle = appHandle;
    evt->filterLength = filterLength;
    evt->filter = NULL;
    if (filterLength)
    {
        evt->filter = (CsrUint8*)CsrPmalloc(filterLength);
        CsrMemCpy(evt->filter, filter, filterLength);
    }
    evt->mode = mode;
    CsrMemCpy(evt->arpFilterAddress.a, arpFilterAddress->a, 4);

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->coexInstance, evt->common.id);
}

void unifi_mgt_pmkid_req(FsmContext* context,
                         void* appHandle,
                         unifi_ListAction action,
                         CsrUint8 setPmkidsCount,
                         const unifi_Pmkid *setPmkids)
{
    UnifiMgtPmkidReq_Evt* evt = (UnifiMgtPmkidReq_Evt*)CsrPmalloc(sizeof(UnifiMgtPmkidReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_PMKID_REQ_ID);

    evt->appHandle = appHandle;
    evt->action = action;
    evt->setPmkidsCount = setPmkidsCount;
    evt->setPmkids = NULL;
    if (setPmkidsCount)
    {
        CsrUint16 i1;
        evt->setPmkids = (unifi_Pmkid*)CsrPmalloc(sizeof(unifi_Pmkid) * setPmkidsCount);
        for(i1 = 0; i1 < setPmkidsCount; i1++)
        {
            CsrMemCpy(evt->setPmkids[i1].bssid.data, setPmkids[i1].bssid.data, 6);
            CsrMemCpy(evt->setPmkids[i1].pmkid, setPmkids[i1].pmkid, 16);
        }
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_restricted_access_disable_req(FsmContext* context,
                                             void* appHandle)
{
    UnifiMgtRestrictedAccessDisableReq_Evt* evt = (UnifiMgtRestrictedAccessDisableReq_Evt*)CsrPmalloc(sizeof(UnifiMgtRestrictedAccessDisableReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_RESTRICTED_ACCESS_DISABLE_REQ_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_restricted_access_enable_req(FsmContext* context,
                                            void* appHandle)
{
    UnifiMgtRestrictedAccessEnableReq_Evt* evt = (UnifiMgtRestrictedAccessEnableReq_Evt*)CsrPmalloc(sizeof(UnifiMgtRestrictedAccessEnableReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_RESTRICTED_ACCESS_ENABLE_REQ_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_scan_full_req(FsmContext* context,
                             void* appHandle,
                             CsrUint8 ssidCount,
                             const unifi_SSID *ssid,
                             const unifi_MACAddress *bssid,
                             CsrBool forceScan,
                             unifi_BSSType bssType,
                             unifi_ScanType scanType,
                             CsrUint16 channelListCount,
                             const CsrUint8 *channelList,
                             CsrUint16 probeIeLength,
                             const CsrUint8 *probeIe)
{
    UnifiMgtScanFullReq_Evt* evt = (UnifiMgtScanFullReq_Evt*)CsrPmalloc(sizeof(UnifiMgtScanFullReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_SCAN_FULL_REQ_ID);

    evt->appHandle = appHandle;
    evt->ssidCount = ssidCount;
    evt->ssid = NULL;
    if (ssidCount)
    {
        CsrUint16 i1;
        evt->ssid = (unifi_SSID*)CsrPmalloc(sizeof(unifi_SSID) * ssidCount);
        for(i1 = 0; i1 < ssidCount; i1++)
        {
            CsrMemCpy(evt->ssid[i1].ssid, ssid[i1].ssid, 32);
            evt->ssid[i1].length = ssid[i1].length;
        }
    }
    CsrMemCpy(evt->bssid.data, bssid->data, 6);
    evt->forceScan = forceScan;
    evt->bssType = bssType;
    evt->scanType = scanType;
    evt->channelListCount = channelListCount;
    evt->channelList = NULL;
    if (channelListCount)
    {
        evt->channelList = (CsrUint8*)CsrPmalloc(channelListCount);
        CsrMemCpy(evt->channelList, channelList, channelListCount);
    }
    evt->probeIeLength = probeIeLength;
    evt->probeIe = NULL;
    if (probeIeLength)
    {
        evt->probeIe = (CsrUint8*)CsrPmalloc(probeIeLength);
        CsrMemCpy(evt->probeIe, probeIe, probeIeLength);
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->scanManagerInstance, evt->common.id);
}

void unifi_mgt_scan_results_flush_req(FsmContext* context,
                                      void* appHandle)
{
    UnifiMgtScanResultsFlushReq_Evt* evt = (UnifiMgtScanResultsFlushReq_Evt*)CsrPmalloc(sizeof(UnifiMgtScanResultsFlushReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_SCAN_RESULTS_FLUSH_REQ_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->scanManagerInstance, evt->common.id);
}

void unifi_mgt_scan_results_get_req(FsmContext* context,
                                    void* appHandle)
{
    UnifiMgtScanResultsGetReq_Evt* evt = (UnifiMgtScanResultsGetReq_Evt*)CsrPmalloc(sizeof(UnifiMgtScanResultsGetReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_SCAN_RESULTS_GET_REQ_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->scanManagerInstance, evt->common.id);
}

void unifi_mgt_set_value_req(FsmContext* context,
                             void* appHandle,
                             const unifi_AppValue *appValue)
{
    UnifiMgtSetValueReq_Evt* evt = (UnifiMgtSetValueReq_Evt*)CsrPmalloc(sizeof(UnifiMgtSetValueReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_SET_VALUE_REQ_ID);

    evt->appHandle = appHandle;
    evt->appValue.id = appValue->id;
    switch(evt->appValue.id)
    {
    case unifi_CloakedSsidConfigValue:
        evt->appValue.unifi_Value_union.cloakedSsids.cloakedSsidsCount = appValue->unifi_Value_union.cloakedSsids.cloakedSsidsCount;
        evt->appValue.unifi_Value_union.cloakedSsids.cloakedSsids = NULL;
        if (appValue->unifi_Value_union.cloakedSsids.cloakedSsidsCount)
        {
            CsrUint16 i4;
            evt->appValue.unifi_Value_union.cloakedSsids.cloakedSsids = (unifi_SSID*)CsrPmalloc(sizeof(unifi_SSID) * appValue->unifi_Value_union.cloakedSsids.cloakedSsidsCount);
            for(i4 = 0; i4 < appValue->unifi_Value_union.cloakedSsids.cloakedSsidsCount; i4++)
            {
                CsrMemCpy(evt->appValue.unifi_Value_union.cloakedSsids.cloakedSsids[i4].ssid, appValue->unifi_Value_union.cloakedSsids.cloakedSsids[i4].ssid, 32);
                evt->appValue.unifi_Value_union.cloakedSsids.cloakedSsids[i4].length = appValue->unifi_Value_union.cloakedSsids.cloakedSsids[i4].length;
            }
        }
    break;
    case unifi_ScanConfigValue:
        {
        CsrUint16 i4;
        for(i4 = 0; i4 < 4; i4++)
        {
            evt->appValue.unifi_Value_union.scanConfig.scanCfg[i4].intervalSeconds = appValue->unifi_Value_union.scanConfig.scanCfg[i4].intervalSeconds;
            evt->appValue.unifi_Value_union.scanConfig.scanCfg[i4].validitySeconds = appValue->unifi_Value_union.scanConfig.scanCfg[i4].validitySeconds;
            evt->appValue.unifi_Value_union.scanConfig.scanCfg[i4].minActiveChannelTimeTu = appValue->unifi_Value_union.scanConfig.scanCfg[i4].minActiveChannelTimeTu;
            evt->appValue.unifi_Value_union.scanConfig.scanCfg[i4].maxActiveChannelTimeTu = appValue->unifi_Value_union.scanConfig.scanCfg[i4].maxActiveChannelTimeTu;
            evt->appValue.unifi_Value_union.scanConfig.scanCfg[i4].minPassiveChannelTimeTu = appValue->unifi_Value_union.scanConfig.scanCfg[i4].minPassiveChannelTimeTu;
            evt->appValue.unifi_Value_union.scanConfig.scanCfg[i4].maxPassiveChannelTimeTu = appValue->unifi_Value_union.scanConfig.scanCfg[i4].maxPassiveChannelTimeTu;
        }
        }
        evt->appValue.unifi_Value_union.scanConfig.disableAutonomousScans = appValue->unifi_Value_union.scanConfig.disableAutonomousScans;
        evt->appValue.unifi_Value_union.scanConfig.maxResults = appValue->unifi_Value_union.scanConfig.maxResults;
        evt->appValue.unifi_Value_union.scanConfig.highRSSIThreshold = appValue->unifi_Value_union.scanConfig.highRSSIThreshold;
        evt->appValue.unifi_Value_union.scanConfig.lowRSSIThreshold = appValue->unifi_Value_union.scanConfig.lowRSSIThreshold;
        evt->appValue.unifi_Value_union.scanConfig.deltaRSSIThreshold = appValue->unifi_Value_union.scanConfig.deltaRSSIThreshold;
        evt->appValue.unifi_Value_union.scanConfig.highSNRThreshold = appValue->unifi_Value_union.scanConfig.highSNRThreshold;
        evt->appValue.unifi_Value_union.scanConfig.lowSNRThreshold = appValue->unifi_Value_union.scanConfig.lowSNRThreshold;
        evt->appValue.unifi_Value_union.scanConfig.deltaSNRThreshold = appValue->unifi_Value_union.scanConfig.deltaSNRThreshold;
        evt->appValue.unifi_Value_union.scanConfig.passiveChannelListCount = appValue->unifi_Value_union.scanConfig.passiveChannelListCount;
        evt->appValue.unifi_Value_union.scanConfig.passiveChannelList = NULL;
        if (appValue->unifi_Value_union.scanConfig.passiveChannelListCount)
        {
            evt->appValue.unifi_Value_union.scanConfig.passiveChannelList = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.scanConfig.passiveChannelListCount);
            CsrMemCpy(evt->appValue.unifi_Value_union.scanConfig.passiveChannelList, appValue->unifi_Value_union.scanConfig.passiveChannelList, appValue->unifi_Value_union.scanConfig.passiveChannelListCount);
        }
    break;
    case unifi_RegulatoryDomainInfoValue:
        evt->appValue.unifi_Value_union.regDomInfo.dot11MultiDomainCapabilityImplemented = appValue->unifi_Value_union.regDomInfo.dot11MultiDomainCapabilityImplemented;
        evt->appValue.unifi_Value_union.regDomInfo.dot11MultiDomainCapabilityEnabled = appValue->unifi_Value_union.regDomInfo.dot11MultiDomainCapabilityEnabled;
        evt->appValue.unifi_Value_union.regDomInfo.currentRegulatoryDomain = appValue->unifi_Value_union.regDomInfo.currentRegulatoryDomain;
        CsrMemCpy(evt->appValue.unifi_Value_union.regDomInfo.currentCountryCode, appValue->unifi_Value_union.regDomInfo.currentCountryCode, 2);
    break;
    case unifi_SmeConfigValue:
        evt->appValue.unifi_Value_union.smeConfig.connectionQualityRssiChangeTrigger = appValue->unifi_Value_union.smeConfig.connectionQualityRssiChangeTrigger;
        evt->appValue.unifi_Value_union.smeConfig.connectionQualitySnrChangeTrigger = appValue->unifi_Value_union.smeConfig.connectionQualitySnrChangeTrigger;
        evt->appValue.unifi_Value_union.smeConfig.trustLevel = appValue->unifi_Value_union.smeConfig.trustLevel;
        CsrMemCpy(evt->appValue.unifi_Value_union.smeConfig.countryCode, appValue->unifi_Value_union.smeConfig.countryCode, 2);
        evt->appValue.unifi_Value_union.smeConfig.wmmModeMask = appValue->unifi_Value_union.smeConfig.wmmModeMask;
        evt->appValue.unifi_Value_union.smeConfig.ifIndex = appValue->unifi_Value_union.smeConfig.ifIndex;
        evt->appValue.unifi_Value_union.smeConfig.firmwareDriverInterface = appValue->unifi_Value_union.smeConfig.firmwareDriverInterface;
        evt->appValue.unifi_Value_union.smeConfig.allowUnicastUseGroupCipher = appValue->unifi_Value_union.smeConfig.allowUnicastUseGroupCipher;
        evt->appValue.unifi_Value_union.smeConfig.enableRestrictedAccess = appValue->unifi_Value_union.smeConfig.enableRestrictedAccess;
        evt->appValue.unifi_Value_union.smeConfig.enableStrictDraftN = appValue->unifi_Value_union.smeConfig.enableStrictDraftN;
        evt->appValue.unifi_Value_union.smeConfig.enableOpportunisticKeyCaching = appValue->unifi_Value_union.smeConfig.enableOpportunisticKeyCaching;
    break;
    case unifi_VersionsValue:
        evt->appValue.unifi_Value_union.versions.chipId = appValue->unifi_Value_union.versions.chipId;
        evt->appValue.unifi_Value_union.versions.chipVersion = appValue->unifi_Value_union.versions.chipVersion;
        evt->appValue.unifi_Value_union.versions.firmwareBuild = appValue->unifi_Value_union.versions.firmwareBuild;
        evt->appValue.unifi_Value_union.versions.firmwarePatch = appValue->unifi_Value_union.versions.firmwarePatch;
        evt->appValue.unifi_Value_union.versions.firmwareHip = appValue->unifi_Value_union.versions.firmwareHip;
        evt->appValue.unifi_Value_union.versions.driverBuild = appValue->unifi_Value_union.versions.driverBuild;
        evt->appValue.unifi_Value_union.versions.driverHip = appValue->unifi_Value_union.versions.driverHip;
        evt->appValue.unifi_Value_union.versions.smeBuild = appValue->unifi_Value_union.versions.smeBuild;
        evt->appValue.unifi_Value_union.versions.smeVariant = appValue->unifi_Value_union.versions.smeVariant;
        evt->appValue.unifi_Value_union.versions.smeHip = appValue->unifi_Value_union.versions.smeHip;
        evt->appValue.unifi_Value_union.versions.smeIdString = (char*)CsrPmalloc(CsrStrLen(appValue->unifi_Value_union.versions.smeIdString) + 1);
        CsrStrCpy(evt->appValue.unifi_Value_union.versions.smeIdString, appValue->unifi_Value_union.versions.smeIdString);
    break;
    case unifi_CoexConfigValue:
        evt->appValue.unifi_Value_union.coexConfig.coexEnable = appValue->unifi_Value_union.coexConfig.coexEnable;
        evt->appValue.unifi_Value_union.coexConfig.coexAfhChannelEnable = appValue->unifi_Value_union.coexConfig.coexAfhChannelEnable;
        evt->appValue.unifi_Value_union.coexConfig.coexAdvancedEnable = appValue->unifi_Value_union.coexConfig.coexAdvancedEnable;
        evt->appValue.unifi_Value_union.coexConfig.coexEnableSchemeManagement = appValue->unifi_Value_union.coexConfig.coexEnableSchemeManagement;
        evt->appValue.unifi_Value_union.coexConfig.coexDirection = appValue->unifi_Value_union.coexConfig.coexDirection;
        evt->appValue.unifi_Value_union.coexConfig.coexPeriodicWakeHost = appValue->unifi_Value_union.coexConfig.coexPeriodicWakeHost;
        evt->appValue.unifi_Value_union.coexConfig.coexTrafficBurstyLatencyMs = appValue->unifi_Value_union.coexConfig.coexTrafficBurstyLatencyMs;
        evt->appValue.unifi_Value_union.coexConfig.coexTrafficContinuousLatencyMs = appValue->unifi_Value_union.coexConfig.coexTrafficContinuousLatencyMs;
        evt->appValue.unifi_Value_union.coexConfig.coexObexBlackoutDurationMs = appValue->unifi_Value_union.coexConfig.coexObexBlackoutDurationMs;
        evt->appValue.unifi_Value_union.coexConfig.coexObexBlackoutPeriodMs = appValue->unifi_Value_union.coexConfig.coexObexBlackoutPeriodMs;
        evt->appValue.unifi_Value_union.coexConfig.coexA2dpBlackoutDurationMs = appValue->unifi_Value_union.coexConfig.coexA2dpBlackoutDurationMs;
        evt->appValue.unifi_Value_union.coexConfig.coexA2dpBlackoutPeriodMs = appValue->unifi_Value_union.coexConfig.coexA2dpBlackoutPeriodMs;
    break;
    case unifi_LinkQualityValue:
        evt->appValue.unifi_Value_union.linkQuality.unifiRssi = appValue->unifi_Value_union.linkQuality.unifiRssi;
        evt->appValue.unifi_Value_union.linkQuality.unifiSnr = appValue->unifi_Value_union.linkQuality.unifiSnr;
    break;
    case unifi_StationMACAddressValue:
        CsrMemCpy(evt->appValue.unifi_Value_union.stationMacAddress.data, appValue->unifi_Value_union.stationMacAddress.data, 6);
    break;
    case unifi_MibConfigValue:
        evt->appValue.unifi_Value_union.mibConfig.unifiFixMaxTxDataRate = appValue->unifi_Value_union.mibConfig.unifiFixMaxTxDataRate;
        evt->appValue.unifi_Value_union.mibConfig.unifiFixTxDataRate = appValue->unifi_Value_union.mibConfig.unifiFixTxDataRate;
        evt->appValue.unifi_Value_union.mibConfig.dot11RtsThreshold = appValue->unifi_Value_union.mibConfig.dot11RtsThreshold;
        evt->appValue.unifi_Value_union.mibConfig.dot11FragmentationThreshold = appValue->unifi_Value_union.mibConfig.dot11FragmentationThreshold;
        evt->appValue.unifi_Value_union.mibConfig.dot11CurrentTxPowerLevel = appValue->unifi_Value_union.mibConfig.dot11CurrentTxPowerLevel;
    break;
    case unifi_PermanentMACAddressValue:
        CsrMemCpy(evt->appValue.unifi_Value_union.permanentMacAddress.data, appValue->unifi_Value_union.permanentMacAddress.data, 6);
    break;
    case unifi_ConnectionStatsValue:
        evt->appValue.unifi_Value_union.connectionStats.unifiTxDataRate = appValue->unifi_Value_union.connectionStats.unifiTxDataRate;
        evt->appValue.unifi_Value_union.connectionStats.unifiRxDataRate = appValue->unifi_Value_union.connectionStats.unifiRxDataRate;
        evt->appValue.unifi_Value_union.connectionStats.dot11RetryCount = appValue->unifi_Value_union.connectionStats.dot11RetryCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11MultipleRetryCount = appValue->unifi_Value_union.connectionStats.dot11MultipleRetryCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11AckFailureCount = appValue->unifi_Value_union.connectionStats.dot11AckFailureCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11FrameDuplicateCount = appValue->unifi_Value_union.connectionStats.dot11FrameDuplicateCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11FcsErrorCount = appValue->unifi_Value_union.connectionStats.dot11FcsErrorCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11RtsSuccessCount = appValue->unifi_Value_union.connectionStats.dot11RtsSuccessCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11RtsFailureCount = appValue->unifi_Value_union.connectionStats.dot11RtsFailureCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11FailedCount = appValue->unifi_Value_union.connectionStats.dot11FailedCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11TransmittedFragmentCount = appValue->unifi_Value_union.connectionStats.dot11TransmittedFragmentCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11TransmittedFrameCount = appValue->unifi_Value_union.connectionStats.dot11TransmittedFrameCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11WEPExcludedCount = appValue->unifi_Value_union.connectionStats.dot11WEPExcludedCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11WEPICVErrorCount = appValue->unifi_Value_union.connectionStats.dot11WEPICVErrorCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11WEPUndecryptableCount = appValue->unifi_Value_union.connectionStats.dot11WEPUndecryptableCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11MulticastReceivedFrameCount = appValue->unifi_Value_union.connectionStats.dot11MulticastReceivedFrameCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11MulticastTransmittedFrameCount = appValue->unifi_Value_union.connectionStats.dot11MulticastTransmittedFrameCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11ReceivedFragmentCount = appValue->unifi_Value_union.connectionStats.dot11ReceivedFragmentCount;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNA4WayHandshakeFailures = appValue->unifi_Value_union.connectionStats.dot11RSNA4WayHandshakeFailures;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNATKIPCounterMeasuresInvoked = appValue->unifi_Value_union.connectionStats.dot11RSNATKIPCounterMeasuresInvoked;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNAStatsTKIPLocalMICFailures = appValue->unifi_Value_union.connectionStats.dot11RSNAStatsTKIPLocalMICFailures;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNAStatsTKIPReplays = appValue->unifi_Value_union.connectionStats.dot11RSNAStatsTKIPReplays;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNAStatsTKIPICVErrors = appValue->unifi_Value_union.connectionStats.dot11RSNAStatsTKIPICVErrors;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNAStatsCCMPReplays = appValue->unifi_Value_union.connectionStats.dot11RSNAStatsCCMPReplays;
        evt->appValue.unifi_Value_union.connectionStats.dot11RSNAStatsCCMPDecryptErrors = appValue->unifi_Value_union.connectionStats.dot11RSNAStatsCCMPDecryptErrors;
    break;
    case unifi_RoamingConfigValue:
        {
        CsrUint16 i4;
        for(i4 = 0; i4 < 3; i4++)
        {
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].rssiHighThreshold = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].rssiHighThreshold;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].rssiLowThreshold = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].rssiLowThreshold;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].snrHighThreshold = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].snrHighThreshold;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].snrLowThreshold = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].snrLowThreshold;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].monitorInterval = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].monitorInterval;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].monitorWindow = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].monitorWindow;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11RetryRatio = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].dot11RetryRatio;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11MultipleRetryRatio = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].dot11MultipleRetryRatio;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11AckFailureRatio = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].dot11AckFailureRatio;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11FcsErrorRatio = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].dot11FcsErrorRatio;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].dot11RtsFailureRatio = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].dot11RtsFailureRatio;
            evt->appValue.unifi_Value_union.roamingConfig.roamingBands[i4].beaconLossThreshold = appValue->unifi_Value_union.roamingConfig.roamingBands[i4].beaconLossThreshold;
        }
        }
        evt->appValue.unifi_Value_union.roamingConfig.lowQualHystWindow = appValue->unifi_Value_union.roamingConfig.lowQualHystWindow;
        evt->appValue.unifi_Value_union.roamingConfig.apBlockTimeMs = appValue->unifi_Value_union.roamingConfig.apBlockTimeMs;
        evt->appValue.unifi_Value_union.roamingConfig.roamMonitorPeriodMs = appValue->unifi_Value_union.roamingConfig.roamMonitorPeriodMs;
        evt->appValue.unifi_Value_union.roamingConfig.roamNumMaxTh = appValue->unifi_Value_union.roamingConfig.roamNumMaxTh;
        evt->appValue.unifi_Value_union.roamingConfig.disableRoamScans = appValue->unifi_Value_union.roamingConfig.disableRoamScans;
        evt->appValue.unifi_Value_union.roamingConfig.reconnectLimit = appValue->unifi_Value_union.roamingConfig.reconnectLimit;
        {
        CsrUint16 i4;
        for(i4 = 0; i4 < 3; i4++)
        {
            evt->appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].intervalSeconds = appValue->unifi_Value_union.roamingConfig.roamScanCfg[i4].intervalSeconds;
            evt->appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].validitySeconds = appValue->unifi_Value_union.roamingConfig.roamScanCfg[i4].validitySeconds;
            evt->appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].minActiveChannelTimeTu = appValue->unifi_Value_union.roamingConfig.roamScanCfg[i4].minActiveChannelTimeTu;
            evt->appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].maxActiveChannelTimeTu = appValue->unifi_Value_union.roamingConfig.roamScanCfg[i4].maxActiveChannelTimeTu;
            evt->appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].minPassiveChannelTimeTu = appValue->unifi_Value_union.roamingConfig.roamScanCfg[i4].minPassiveChannelTimeTu;
            evt->appValue.unifi_Value_union.roamingConfig.roamScanCfg[i4].maxPassiveChannelTimeTu = appValue->unifi_Value_union.roamingConfig.roamScanCfg[i4].maxPassiveChannelTimeTu;
        }
        }
    break;
    case unifi_AdHocConfigValue:
        evt->appValue.unifi_Value_union.adHocConfig.atimWindowTu = appValue->unifi_Value_union.adHocConfig.atimWindowTu;
        evt->appValue.unifi_Value_union.adHocConfig.beaconPeriodTu = appValue->unifi_Value_union.adHocConfig.beaconPeriodTu;
        evt->appValue.unifi_Value_union.adHocConfig.joinOnlyAttempts = appValue->unifi_Value_union.adHocConfig.joinOnlyAttempts;
        evt->appValue.unifi_Value_union.adHocConfig.joinAttemptIntervalMs = appValue->unifi_Value_union.adHocConfig.joinAttemptIntervalMs;
    break;
    case unifi_ConnectionInfoValue:
        CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.ssid.ssid, appValue->unifi_Value_union.connectionInfo.ssid.ssid, 32);
        evt->appValue.unifi_Value_union.connectionInfo.ssid.length = appValue->unifi_Value_union.connectionInfo.ssid.length;
        CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.bssid.data, appValue->unifi_Value_union.connectionInfo.bssid.data, 6);
        evt->appValue.unifi_Value_union.connectionInfo.networkType80211 = appValue->unifi_Value_union.connectionInfo.networkType80211;
        evt->appValue.unifi_Value_union.connectionInfo.channelNumber = appValue->unifi_Value_union.connectionInfo.channelNumber;
        evt->appValue.unifi_Value_union.connectionInfo.channelFrequency = appValue->unifi_Value_union.connectionInfo.channelFrequency;
        evt->appValue.unifi_Value_union.connectionInfo.authMode = appValue->unifi_Value_union.connectionInfo.authMode;
        evt->appValue.unifi_Value_union.connectionInfo.pairwiseCipher = appValue->unifi_Value_union.connectionInfo.pairwiseCipher;
        evt->appValue.unifi_Value_union.connectionInfo.groupCipher = appValue->unifi_Value_union.connectionInfo.groupCipher;
        evt->appValue.unifi_Value_union.connectionInfo.ifIndex = appValue->unifi_Value_union.connectionInfo.ifIndex;
        evt->appValue.unifi_Value_union.connectionInfo.atimWindowTu = appValue->unifi_Value_union.connectionInfo.atimWindowTu;
        evt->appValue.unifi_Value_union.connectionInfo.beaconPeriodTu = appValue->unifi_Value_union.connectionInfo.beaconPeriodTu;
        evt->appValue.unifi_Value_union.connectionInfo.reassociation = appValue->unifi_Value_union.connectionInfo.reassociation;
        evt->appValue.unifi_Value_union.connectionInfo.beaconFrameLength = appValue->unifi_Value_union.connectionInfo.beaconFrameLength;
        evt->appValue.unifi_Value_union.connectionInfo.beaconFrame = NULL;
        if (appValue->unifi_Value_union.connectionInfo.beaconFrameLength)
        {
            evt->appValue.unifi_Value_union.connectionInfo.beaconFrame = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionInfo.beaconFrameLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.beaconFrame, appValue->unifi_Value_union.connectionInfo.beaconFrame, appValue->unifi_Value_union.connectionInfo.beaconFrameLength);
        }
        evt->appValue.unifi_Value_union.connectionInfo.associationReqFrameLength = appValue->unifi_Value_union.connectionInfo.associationReqFrameLength;
        evt->appValue.unifi_Value_union.connectionInfo.associationReqFrame = NULL;
        if (appValue->unifi_Value_union.connectionInfo.associationReqFrameLength)
        {
            evt->appValue.unifi_Value_union.connectionInfo.associationReqFrame = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionInfo.associationReqFrameLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.associationReqFrame, appValue->unifi_Value_union.connectionInfo.associationReqFrame, appValue->unifi_Value_union.connectionInfo.associationReqFrameLength);
        }
        evt->appValue.unifi_Value_union.connectionInfo.associationRspFrameLength = appValue->unifi_Value_union.connectionInfo.associationRspFrameLength;
        evt->appValue.unifi_Value_union.connectionInfo.associationRspFrame = NULL;
        if (appValue->unifi_Value_union.connectionInfo.associationRspFrameLength)
        {
            evt->appValue.unifi_Value_union.connectionInfo.associationRspFrame = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionInfo.associationRspFrameLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.associationRspFrame, appValue->unifi_Value_union.connectionInfo.associationRspFrame, appValue->unifi_Value_union.connectionInfo.associationRspFrameLength);
        }
        evt->appValue.unifi_Value_union.connectionInfo.assocScanInfoElementsLength = appValue->unifi_Value_union.connectionInfo.assocScanInfoElementsLength;
        evt->appValue.unifi_Value_union.connectionInfo.assocScanInfoElements = NULL;
        if (appValue->unifi_Value_union.connectionInfo.assocScanInfoElementsLength)
        {
            evt->appValue.unifi_Value_union.connectionInfo.assocScanInfoElements = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionInfo.assocScanInfoElementsLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.assocScanInfoElements, appValue->unifi_Value_union.connectionInfo.assocScanInfoElements, appValue->unifi_Value_union.connectionInfo.assocScanInfoElementsLength);
        }
        evt->appValue.unifi_Value_union.connectionInfo.assocReqCapabilities = appValue->unifi_Value_union.connectionInfo.assocReqCapabilities;
        evt->appValue.unifi_Value_union.connectionInfo.assocReqListenIntervalBeacons = appValue->unifi_Value_union.connectionInfo.assocReqListenIntervalBeacons;
        CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.assocReqApAddress.data, appValue->unifi_Value_union.connectionInfo.assocReqApAddress.data, 6);
        evt->appValue.unifi_Value_union.connectionInfo.assocReqInfoElementsLength = appValue->unifi_Value_union.connectionInfo.assocReqInfoElementsLength;
        evt->appValue.unifi_Value_union.connectionInfo.assocReqInfoElements = NULL;
        if (appValue->unifi_Value_union.connectionInfo.assocReqInfoElementsLength)
        {
            evt->appValue.unifi_Value_union.connectionInfo.assocReqInfoElements = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionInfo.assocReqInfoElementsLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.assocReqInfoElements, appValue->unifi_Value_union.connectionInfo.assocReqInfoElements, appValue->unifi_Value_union.connectionInfo.assocReqInfoElementsLength);
        }
        evt->appValue.unifi_Value_union.connectionInfo.assocRspResult = appValue->unifi_Value_union.connectionInfo.assocRspResult;
        evt->appValue.unifi_Value_union.connectionInfo.assocRspCapabilityInfo = appValue->unifi_Value_union.connectionInfo.assocRspCapabilityInfo;
        evt->appValue.unifi_Value_union.connectionInfo.assocRspAssociationId = appValue->unifi_Value_union.connectionInfo.assocRspAssociationId;
        evt->appValue.unifi_Value_union.connectionInfo.assocRspInfoElementsLength = appValue->unifi_Value_union.connectionInfo.assocRspInfoElementsLength;
        evt->appValue.unifi_Value_union.connectionInfo.assocRspInfoElements = NULL;
        if (appValue->unifi_Value_union.connectionInfo.assocRspInfoElementsLength)
        {
            evt->appValue.unifi_Value_union.connectionInfo.assocRspInfoElements = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionInfo.assocRspInfoElementsLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionInfo.assocRspInfoElements, appValue->unifi_Value_union.connectionInfo.assocRspInfoElements, appValue->unifi_Value_union.connectionInfo.assocRspInfoElementsLength);
        }
    break;
    case unifi_CoexInfoValue:
        evt->appValue.unifi_Value_union.coexInfo.hasTrafficData = appValue->unifi_Value_union.coexInfo.hasTrafficData;
        evt->appValue.unifi_Value_union.coexInfo.currentTrafficType = appValue->unifi_Value_union.coexInfo.currentTrafficType;
        evt->appValue.unifi_Value_union.coexInfo.currentPeriodMs = appValue->unifi_Value_union.coexInfo.currentPeriodMs;
        evt->appValue.unifi_Value_union.coexInfo.currentPowerSave = appValue->unifi_Value_union.coexInfo.currentPowerSave;
        evt->appValue.unifi_Value_union.coexInfo.currentCoexPeriodMs = appValue->unifi_Value_union.coexInfo.currentCoexPeriodMs;
        evt->appValue.unifi_Value_union.coexInfo.currentCoexLatencyMs = appValue->unifi_Value_union.coexInfo.currentCoexLatencyMs;
        evt->appValue.unifi_Value_union.coexInfo.hasBtDevice = appValue->unifi_Value_union.coexInfo.hasBtDevice;
        evt->appValue.unifi_Value_union.coexInfo.currentBlackoutDurationUs = appValue->unifi_Value_union.coexInfo.currentBlackoutDurationUs;
        evt->appValue.unifi_Value_union.coexInfo.currentBlackoutPeriodUs = appValue->unifi_Value_union.coexInfo.currentBlackoutPeriodUs;
        evt->appValue.unifi_Value_union.coexInfo.currentCoexScheme = appValue->unifi_Value_union.coexInfo.currentCoexScheme;
    break;
    case unifi_CalibrationDataValue:
        evt->appValue.unifi_Value_union.calibrationData.length = appValue->unifi_Value_union.calibrationData.length;
        evt->appValue.unifi_Value_union.calibrationData.data = NULL;
        if (appValue->unifi_Value_union.calibrationData.length)
        {
            evt->appValue.unifi_Value_union.calibrationData.data = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.calibrationData.length);
            CsrMemCpy(evt->appValue.unifi_Value_union.calibrationData.data, appValue->unifi_Value_union.calibrationData.data, appValue->unifi_Value_union.calibrationData.length);
        }
    break;
    case unifi_ConnectionConfigValue:
        CsrMemCpy(evt->appValue.unifi_Value_union.connectionConfig.ssid.ssid, appValue->unifi_Value_union.connectionConfig.ssid.ssid, 32);
        evt->appValue.unifi_Value_union.connectionConfig.ssid.length = appValue->unifi_Value_union.connectionConfig.ssid.length;
        CsrMemCpy(evt->appValue.unifi_Value_union.connectionConfig.bssid.data, appValue->unifi_Value_union.connectionConfig.bssid.data, 6);
        evt->appValue.unifi_Value_union.connectionConfig.bssType = appValue->unifi_Value_union.connectionConfig.bssType;
        evt->appValue.unifi_Value_union.connectionConfig.ifIndex = appValue->unifi_Value_union.connectionConfig.ifIndex;
        evt->appValue.unifi_Value_union.connectionConfig.privacyMode = appValue->unifi_Value_union.connectionConfig.privacyMode;
        evt->appValue.unifi_Value_union.connectionConfig.authModeMask = appValue->unifi_Value_union.connectionConfig.authModeMask;
        evt->appValue.unifi_Value_union.connectionConfig.encryptionModeMask = appValue->unifi_Value_union.connectionConfig.encryptionModeMask;
        evt->appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength = appValue->unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength;
        evt->appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements = NULL;
        if (appValue->unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength)
        {
            evt->appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements = (CsrUint8*)CsrPmalloc(appValue->unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength);
            CsrMemCpy(evt->appValue.unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements, appValue->unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElements, appValue->unifi_Value_union.connectionConfig.mlmeAssociateReqInformationElementsLength);
        }
        evt->appValue.unifi_Value_union.connectionConfig.wmmQosInfo = appValue->unifi_Value_union.connectionConfig.wmmQosInfo;
        evt->appValue.unifi_Value_union.connectionConfig.adhocJoinOnly = appValue->unifi_Value_union.connectionConfig.adhocJoinOnly;
        evt->appValue.unifi_Value_union.connectionConfig.adhocChannel = appValue->unifi_Value_union.connectionConfig.adhocChannel;
    break;
    case unifi_CcxConfigValue:
        evt->appValue.unifi_Value_union.ccxConfig.keepAliveTimeMs = appValue->unifi_Value_union.ccxConfig.keepAliveTimeMs;
        evt->appValue.unifi_Value_union.ccxConfig.apRoamingEnabled = appValue->unifi_Value_union.ccxConfig.apRoamingEnabled;
        evt->appValue.unifi_Value_union.ccxConfig.measurementsMask = appValue->unifi_Value_union.ccxConfig.measurementsMask;
        evt->appValue.unifi_Value_union.ccxConfig.ccxRadioMgtEnabled = appValue->unifi_Value_union.ccxConfig.ccxRadioMgtEnabled;
    break;
    case unifi_PowerConfigValue:
        evt->appValue.unifi_Value_union.powerConfig.powerSaveLevel = appValue->unifi_Value_union.powerConfig.powerSaveLevel;
        evt->appValue.unifi_Value_union.powerConfig.listenIntervalBeacons = appValue->unifi_Value_union.powerConfig.listenIntervalBeacons;
        evt->appValue.unifi_Value_union.powerConfig.rxDtims = appValue->unifi_Value_union.powerConfig.rxDtims;
        evt->appValue.unifi_Value_union.powerConfig.d3AutoScanMode = appValue->unifi_Value_union.powerConfig.d3AutoScanMode;
    break;
    case unifi_HostConfigValue:
        evt->appValue.unifi_Value_union.hostConfig.powerMode = appValue->unifi_Value_union.hostConfig.powerMode;
        evt->appValue.unifi_Value_union.hostConfig.applicationDataPeriodMs = appValue->unifi_Value_union.hostConfig.applicationDataPeriodMs;
    break;
    default:
        break;
    };

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeConfigurationInstance, evt->common.id);
}

void unifi_mgt_tspec_req(FsmContext* context,
                         void* appHandle,
                         unifi_ListAction action,
                         CsrUint32 transactionId,
                         CsrBool strict,
                         CsrUint8 ctrlMask,
                         CsrUint16 tspecLength,
                         const CsrUint8 *tspec,
                         CsrUint16 tclasLength,
                         const CsrUint8 *tclas)
{
    UnifiMgtTspecReq_Evt* evt = (UnifiMgtTspecReq_Evt*)CsrPmalloc(sizeof(UnifiMgtTspecReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_TSPEC_REQ_ID);

    evt->appHandle = appHandle;
    evt->action = action;
    evt->transactionId = transactionId;
    evt->strict = strict;
    evt->ctrlMask = ctrlMask;
    evt->tspecLength = tspecLength;
    evt->tspec = NULL;
    if (tspecLength)
    {
        evt->tspec = (CsrUint8*)CsrPmalloc(tspecLength);
        CsrMemCpy(evt->tspec, tspec, tspecLength);
    }
    evt->tclasLength = tclasLength;
    evt->tclas = NULL;
    if (tclasLength)
    {
        evt->tclas = (CsrUint8*)CsrPmalloc(tclasLength);
        CsrMemCpy(evt->tclas, tclas, tclasLength);
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->qosInstance, evt->common.id);
}

void unifi_mgt_wifi_flightmode_req(FsmContext* context,
                                   void* appHandle,
                                   const unifi_MACAddress *address,
                                   CsrUint16 mibFilesCount,
                                   const unifi_DataBlock *mibFiles)
{
    UnifiMgtWifiFlightmodeReq_Evt* evt = (UnifiMgtWifiFlightmodeReq_Evt*)CsrPmalloc(sizeof(UnifiMgtWifiFlightmodeReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_WIFI_FLIGHTMODE_REQ_ID);

    evt->appHandle = appHandle;
    CsrMemCpy(evt->address.data, address->data, 6);
    evt->mibFilesCount = mibFilesCount;
    evt->mibFiles = NULL;
    if (mibFilesCount)
    {
        CsrUint16 i1;
        evt->mibFiles = (unifi_DataBlock*)CsrPmalloc(sizeof(unifi_DataBlock) * mibFilesCount);
        for(i1 = 0; i1 < mibFilesCount; i1++)
        {
            evt->mibFiles[i1].length = mibFiles[i1].length;
            evt->mibFiles[i1].data = NULL;
            if (mibFiles[i1].length)
            {
                evt->mibFiles[i1].data = (CsrUint8*)CsrPmalloc(mibFiles[i1].length);
                CsrMemCpy(evt->mibFiles[i1].data, mibFiles[i1].data, mibFiles[i1].length);
            }
        }
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeCoreInstance, evt->common.id);
}

void unifi_mgt_wifi_off_req(FsmContext* context,
                            void* appHandle)
{
    UnifiMgtWifiOffReq_Evt* evt = (UnifiMgtWifiOffReq_Evt*)CsrPmalloc(sizeof(UnifiMgtWifiOffReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_WIFI_OFF_REQ_ID);

    evt->appHandle = appHandle;

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeCoreInstance, evt->common.id);
}

void unifi_mgt_wifi_on_req(FsmContext* context,
                           void* appHandle,
                           const unifi_MACAddress *address,
                           CsrUint16 mibFilesCount,
                           const unifi_DataBlock *mibFiles)
{
    UnifiMgtWifiOnReq_Evt* evt = (UnifiMgtWifiOnReq_Evt*)CsrPmalloc(sizeof(UnifiMgtWifiOnReq_Evt));

    INIT_EVENT_HEADER(evt, UNIFI_MGT_WIFI_ON_REQ_ID);

    evt->appHandle = appHandle;
    CsrMemCpy(evt->address.data, address->data, 6);
    evt->mibFilesCount = mibFilesCount;
    evt->mibFiles = NULL;
    if (mibFilesCount)
    {
        CsrUint16 i1;
        evt->mibFiles = (unifi_DataBlock*)CsrPmalloc(sizeof(unifi_DataBlock) * mibFilesCount);
        for(i1 = 0; i1 < mibFilesCount; i1++)
        {
            evt->mibFiles[i1].length = mibFiles[i1].length;
            evt->mibFiles[i1].data = NULL;
            if (mibFiles[i1].length)
            {
                evt->mibFiles[i1].data = (CsrUint8*)CsrPmalloc(mibFiles[i1].length);
                CsrMemCpy(evt->mibFiles[i1].data, mibFiles[i1].data, mibFiles[i1].length);
            }
        }
    }

    fsm_send_event_external(context, (FsmEvent*)evt, getSmeContext(context)->smeCoreInstance, evt->common.id);
}


