
#
# Makefile for MMC/SD host controller drivers
#

obj-$(CONFIG_SW_MMC_POWER_CONTROL)    += mmc_power.o

mmc_power-y := mmc_power_manage.o mmc_pwr_swl_n20.o mmc_pwr_usi_bm01a.o \
                mmc_pwr_apm6xxx.o mmc_pwr_swb_b23.o
