/* This is an autogenerated file */
/* Tag: noCheckHeader */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2009. All rights reserved. */
/* */
/*   Refer to LICENSE.txt included with this source for details on the */
/*   license terms. */

#ifndef UNIFI_DRIVER_XML_TYPES_H
#define UNIFI_DRIVER_XML_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif











#ifdef __cplusplus
}
#endif

#endif /* UNIFI_DRIVER_XML_TYPES_H */
