/* This is an autogenerated file */
/* Tag: noCheckHeader */

/*    CONFIDENTIAL */
/*    Copyright (C) Cambridge Silicon Radio Ltd 2008. All rights reserved. */

#ifndef __SYS_SAP_SERIALIZE_H__
#define __SYS_SAP_SERIALIZE_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "sme_top_level_fsm/sme.h"
#include "smeio/smeio_fsm_events.h"

CsrUint16 serialise_unifi_sys_capabilities_cfm(CsrUint8** resultBuffer, void* appHandle, CsrUint16 commandQueueSize, CsrUint16 trafficQueueSize);
CsrUint16 serialise_unifi_sys_eapol_cfm(CsrUint8** resultBuffer, void* appHandle, unifi_EapolRc result);
CsrUint16 serialise_unifi_sys_hip_ind(CsrUint8** resultBuffer, CsrUint16 mlmeCommandLength, const CsrUint8 *mlmeCommand, CsrUint16 dataRef1Length, const CsrUint8 *dataRef1, CsrUint16 dataRef2Length, const CsrUint8 *dataRef2);
CsrUint16 serialise_unifi_sys_ip_configured_ind(CsrUint8** resultBuffer, CsrBool ipConfigured);
CsrUint16 serialise_unifi_sys_m4_transmitted_ind(CsrUint8** resultBuffer);
CsrUint16 serialise_unifi_sys_ma_unitdata_ind(CsrUint8** resultBuffer, void* appHandle, CsrUint8 subscriptionHandle, CsrUint16 frameLength, const CsrUint8 *frame, unifi_FrameFreeFunction freeFunction, unifi_ReceptionStatus receptionStatus, unifi_Priority priority, unifi_ServiceClass serviceClass);
CsrUint16 serialise_unifi_sys_ma_unitdata_cfm(CsrUint8** resultBuffer, void* appHandle, unifi_Status result, unifi_TransmissionStatus transmissionStatus, unifi_Priority providedPriority, unifi_ServiceClass providedServiceClass, CsrUint32 reqIdentifier);
CsrUint16 serialise_unifi_sys_ma_unitdata_subscribe_cfm(CsrUint8** resultBuffer, void* appHandle, CsrUint8 subscriptionHandle, unifi_SubscriptionResult status, CsrUint16 allocOffset);
CsrUint16 serialise_unifi_sys_ma_unitdata_unsubscribe_cfm(CsrUint8** resultBuffer, void* appHandle, unifi_SubscriptionResult status);
CsrUint16 serialise_unifi_sys_multicast_address_ind(CsrUint8** resultBuffer, unifi_ListAction action, CsrUint8 setAddressesCount, const unifi_MACAddress *setAddresses);
CsrUint16 serialise_unifi_sys_port_configure_cfm(CsrUint8** resultBuffer, unifi_Status status, const unifi_MACAddress *macAddress);
CsrUint16 serialise_unifi_sys_qos_control_cfm(CsrUint8** resultBuffer, unifi_Status status);
CsrUint16 serialise_unifi_sys_resume_ind(CsrUint8** resultBuffer, CsrBool powerMaintained);
CsrUint16 serialise_unifi_sys_suspend_ind(CsrUint8** resultBuffer, CsrBool hardSuspend, CsrBool d3Suspend);
CsrUint16 serialise_unifi_sys_tclas_add_cfm(CsrUint8** resultBuffer, unifi_Status status);
CsrUint16 serialise_unifi_sys_tclas_del_cfm(CsrUint8** resultBuffer, unifi_Status status);
CsrUint16 serialise_unifi_sys_traffic_protocol_ind(CsrUint8** resultBuffer, unifi_TrafficPacketType packetType, unifi_ProtocolDirection direction, const unifi_MACAddress *srcAddress);
CsrUint16 serialise_unifi_sys_traffic_sample_ind(CsrUint8** resultBuffer, const unifi_TrafficStats *stats);
CsrUint16 serialise_unifi_sys_wifi_off_ind(CsrUint8** resultBuffer, unifi_ControlIndication controlIndication);
CsrUint16 serialise_unifi_sys_wifi_off_cfm(CsrUint8** resultBuffer);
CsrUint16 serialise_unifi_sys_wifi_on_ind(CsrUint8** resultBuffer, unifi_Status status, const unifi_DriverVersions *driverVersions);
CsrUint16 serialise_unifi_sys_wifi_on_cfm(CsrUint8** resultBuffer, unifi_Status status);


#ifdef __cplusplus
}
#endif

#endif /* __SYS_SAP_SERIALIZE_H__ */
