

obj-$(CONFIG_SND_SUN4I_SOC_SPDIF) += sun4i_spdif.o
obj-$(CONFIG_SND_SUN4I_SOC_SPDIF) += sun4i_spdma.o
obj-$(CONFIG_SND_SUN4I_SOC_SPDIF) += anx7150sp.o
obj-$(CONFIG_SND_SUN4I_SOC_SPDIF) += sun4i_anx7150sp.o


