/***************************************************************************
 *
 * This is an AUTOGENERATED file from genio_signal_trace_c.pl
 *
 *    CONFIDENTIAL
 *    Copyright (C) Cambridge Silicon Radio Ltd 2007. All rights reserved.
 */

/***************************************************************************
 * Description:
 *       This file is used for debugging the PAL_HCI SAP.  It contains a list
 *       of functions that print the content of a signal into human readable 
 *       strings.
 *
 * Options used to generate this file:
 * perl genio_signal_trace_c.pl
 *       -o /home/bfsw/host/releases/unifi_hostsoftware_212/build/unifi-driver-212/host/lib_sme/sme/../saps/pal_hci_sap/pal_hci_sap_signals_trace.c
 *       -x /home/bfsw/host/releases/unifi_hostsoftware_212/build/unifi-driver-212/host/lib_sme/../common/amp_hci/bt_amp_hci.xml
 *       -i PAL_HCI
 *       -d 
 *
 ***************************************************************************/


#include "fsm/csr_wifi_fsm.h" 
#include "fsm/fsm_internal.h" 

#include "sme_trace/sme_trace.h"
#include "sme_trace/sme_pbc.h"

#include "pal_hci_sap/pal_hci_sap_types.h"
#include "pal_hci_sap/pal_hci_sap.h"
#include "pal_hci_sap_types_trace.h"
#include "pal_hci_sap_signals.h"
#include "pal_hci_sap_signals_trace.h"

#ifdef SME_TRACE_ENABLE

/* -------------------------- HCI_No_Operation.Command -------------------------- */
void trace_HciNoOperationCmd(const char* text, const FsmContext* context, const HciNoOperationCmd *pHciNoOperationCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_No_Operation.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Create_Physical_Link.Command -------------------------- */
void trace_HciCreatePhysicalLinkCmd(const char* text, const FsmContext* context, const HciCreatePhysicalLinkCmd *pHciCreatePhysicalLinkCmd)
{
    char *dedicatedAmpKey_Str = trace_hci_Buffer(pHciCreatePhysicalLinkCmd->dedicatedAmpKey,pHciCreatePhysicalLinkCmd->dedicatedAmpKeyLength);
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Create_Physical_Link.Command: Physical_Link_Handle = %d Dedicated_AMP_Key_Length = %d Dedicated_AMP_Key_Type = %s Dedicated_AMP_Key = %s) To(%s)", 
        "ENV", 
        text,
        pHciCreatePhysicalLinkCmd->physicalLinkHandle,
        pHciCreatePhysicalLinkCmd->dedicatedAmpKeyLength,
        trace_LinkKeyType(pHciCreatePhysicalLinkCmd->dedicatedAmpKeyType),
        dedicatedAmpKey_Str,
        "PAL_MGR" 
    ));
    CsrPfree(dedicatedAmpKey_Str);
}


/* -------------------------- HCI_Accept_Physical_Link_Request.Command -------------------------- */
void trace_HciAcceptPhysicalLinkRequestCmd(const char* text, const FsmContext* context, const HciAcceptPhysicalLinkRequestCmd *pHciAcceptPhysicalLinkRequestCmd)
{
    char *dedicatedAmpKey_Str = trace_hci_Buffer(pHciAcceptPhysicalLinkRequestCmd->dedicatedAmpKey,pHciAcceptPhysicalLinkRequestCmd->dedicatedAmpKeyLength);
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Accept_Physical_Link_Request.Command: Physical_Link_Handle = %d Dedicated_AMP_Key_Length = %d Dedicated_AMP_Key_Type = %s Dedicated_AMP_Key = %s) To(%s)", 
        "ENV", 
        text,
        pHciAcceptPhysicalLinkRequestCmd->physicalLinkHandle,
        pHciAcceptPhysicalLinkRequestCmd->dedicatedAmpKeyLength,
        trace_LinkKeyType(pHciAcceptPhysicalLinkRequestCmd->dedicatedAmpKeyType),
        dedicatedAmpKey_Str,
        "PAL_MGR" 
    ));
    CsrPfree(dedicatedAmpKey_Str);
}


/* -------------------------- HCI_Disconnect_Physical_Link.Command -------------------------- */
void trace_HciDisconnectPhysicalLinkCmd(const char* text, const FsmContext* context, const HciDisconnectPhysicalLinkCmd *pHciDisconnectPhysicalLinkCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Disconnect_Physical_Link.Command: Physical_Link_Handle = %d Reason = %s) To(%s)", 
        "ENV", 
        text,
        pHciDisconnectPhysicalLinkCmd->physicalLinkHandle,
        trace_HciStatusCode(pHciDisconnectPhysicalLinkCmd->reason),
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Create_Logical_Link.Command -------------------------- */
void trace_HciCreateLogicalLinkCmd(const char* text, const FsmContext* context, const HciCreateLogicalLinkCmd *pHciCreateLogicalLinkCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Create_Logical_Link.Command: Physical_Link_Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciCreateLogicalLinkCmd->physicalLinkHandle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Accept_Logical_Link.Command -------------------------- */
void trace_HciAcceptLogicalLinkCmd(const char* text, const FsmContext* context, const HciAcceptLogicalLinkCmd *pHciAcceptLogicalLinkCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Accept_Logical_Link.Command: Physical_Link_Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciAcceptLogicalLinkCmd->physicalLinkHandle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Disconnect_Logical_Link.Command -------------------------- */
void trace_HciDisconnectLogicalLinkCmd(const char* text, const FsmContext* context, const HciDisconnectLogicalLinkCmd *pHciDisconnectLogicalLinkCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Disconnect_Logical_Link.Command: Logical_Link_Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciDisconnectLogicalLinkCmd->logicalLinkHandle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Logical_Link_Cancel.Command -------------------------- */
void trace_HciLogicalLinkCancelCmd(const char* text, const FsmContext* context, const HciLogicalLinkCancelCmd *pHciLogicalLinkCancelCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Logical_Link_Cancel.Command: Physical_Link_Handle = %d Tx_Flow_Spec_ID = %d) To(%s)", 
        "ENV", 
        text,
        pHciLogicalLinkCancelCmd->physicalLinkHandle,
        pHciLogicalLinkCancelCmd->txFlowSpecId,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Flow_Spec_Modify.Command -------------------------- */
void trace_HciFlowSpecModifyCmd(const char* text, const FsmContext* context, const HciFlowSpecModifyCmd *pHciFlowSpecModifyCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Flow_Spec_Modify.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciFlowSpecModifyCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Set_Event_Mask.Command -------------------------- */
void trace_HciSetEventMaskCmd(const char* text, const FsmContext* context, const HciSetEventMaskCmd *pHciSetEventMaskCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Set_Event_Mask.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Reset.Command -------------------------- */
void trace_HciResetCmd(const char* text, const FsmContext* context, const HciResetCmd *pHciResetCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Reset.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Flush.Command -------------------------- */
void trace_HciFlushCmd(const char* text, const FsmContext* context, const HciFlushCmd *pHciFlushCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Flush.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciFlushCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Connection_Accept_Timeout.Command -------------------------- */
void trace_HciReadConnectionAcceptTimeoutCmd(const char* text, const FsmContext* context, const HciReadConnectionAcceptTimeoutCmd *pHciReadConnectionAcceptTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Connection_Accept_Timeout.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Connection_Accept_Timeout.Command -------------------------- */
void trace_HciWriteConnectionAcceptTimeoutCmd(const char* text, const FsmContext* context, const HciWriteConnectionAcceptTimeoutCmd *pHciWriteConnectionAcceptTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Connection_Accept_Timeout.Command: Conn_Accept_Timeout = %d) To(%s)", 
        "ENV", 
        text,
        pHciWriteConnectionAcceptTimeoutCmd->connAcceptTimeout,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Link_Supervision_Timeout.Command -------------------------- */
void trace_HciReadLinkSupervisionTimeoutCmd(const char* text, const FsmContext* context, const HciReadLinkSupervisionTimeoutCmd *pHciReadLinkSupervisionTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Link_Supervision_Timeout.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciReadLinkSupervisionTimeoutCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Link_Supervision_Timeout.Command -------------------------- */
void trace_HciWriteLinkSupervisionTimeoutCmd(const char* text, const FsmContext* context, const HciWriteLinkSupervisionTimeoutCmd *pHciWriteLinkSupervisionTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Link_Supervision_Timeout.Command: Handle = %d Link_Supervision_Timeout = %d) To(%s)", 
        "ENV", 
        text,
        pHciWriteLinkSupervisionTimeoutCmd->handle,
        pHciWriteLinkSupervisionTimeoutCmd->linkSupervisionTimeout,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Enhanced_Flush.Command -------------------------- */
void trace_HciEnhancedFlushCmd(const char* text, const FsmContext* context, const HciEnhancedFlushCmd *pHciEnhancedFlushCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Enhanced_Flush.Command: Handle = %d Packet_Type = %s) To(%s)", 
        "ENV", 
        text,
        pHciEnhancedFlushCmd->handle,
        trace_PacketType(pHciEnhancedFlushCmd->packetType),
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Logical_Link_Accept_Timeout.Command -------------------------- */
void trace_HciReadLogicalLinkAcceptTimeoutCmd(const char* text, const FsmContext* context, const HciReadLogicalLinkAcceptTimeoutCmd *pHciReadLogicalLinkAcceptTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Logical_Link_Accept_Timeout.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Logical_Link_Accept_Timeout.Command -------------------------- */
void trace_HciWriteLogicalLinkAcceptTimeoutCmd(const char* text, const FsmContext* context, const HciWriteLogicalLinkAcceptTimeoutCmd *pHciWriteLogicalLinkAcceptTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Logical_Link_Accept_Timeout.Command: Logical_Link_Accept_Timeout = %d) To(%s)", 
        "ENV", 
        text,
        pHciWriteLogicalLinkAcceptTimeoutCmd->logicalLinkAcceptTimeout,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Set_Event_Mask_Page2.Command -------------------------- */
void trace_HciSetEventMaskPage2Cmd(const char* text, const FsmContext* context, const HciSetEventMaskPage2Cmd *pHciSetEventMaskPage2Cmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Set_Event_Mask_Page2.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Location_Data.Command -------------------------- */
void trace_HciReadLocationDataCmd(const char* text, const FsmContext* context, const HciReadLocationDataCmd *pHciReadLocationDataCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Location_Data.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Location_Data.Command -------------------------- */
void trace_HciWriteLocationDataCmd(const char* text, const FsmContext* context, const HciWriteLocationDataCmd *pHciWriteLocationDataCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Location_Data.Command: Location_Domain_Aware = %s Location_Domain = %d Location_Domain_Options = %s Location_Options = %s) To(%s)", 
        "ENV", 
        text,
        trace_LocationDomainAware(pHciWriteLocationDataCmd->locationDomainAware),
        pHciWriteLocationDataCmd->locationDomain,
        trace_LocationDomainOptions(pHciWriteLocationDataCmd->locationDomainOptions),
        trace_LocationOptions(pHciWriteLocationDataCmd->locationOptions),
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Best_Effort_Flush_Timeout.Command -------------------------- */
void trace_HciReadBestEffortFlushTimeoutCmd(const char* text, const FsmContext* context, const HciReadBestEffortFlushTimeoutCmd *pHciReadBestEffortFlushTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Best_Effort_Flush_Timeout.Command: Logical_Link_Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciReadBestEffortFlushTimeoutCmd->logicalLinkHandle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Best_Effort_Flush_Timeout.Command -------------------------- */
void trace_HciWriteBestEffortFlushTimeoutCmd(const char* text, const FsmContext* context, const HciWriteBestEffortFlushTimeoutCmd *pHciWriteBestEffortFlushTimeoutCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Best_Effort_Flush_Timeout.Command: Logical_Link_Handle = %d Best_Effort_Flush_Timeout = %d) To(%s)", 
        "ENV", 
        text,
        pHciWriteBestEffortFlushTimeoutCmd->logicalLinkHandle,
        pHciWriteBestEffortFlushTimeoutCmd->bestEffortFlushTimeout,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Short_Range_Mode.Command -------------------------- */
void trace_HciShortRangeModeCmd(const char* text, const FsmContext* context, const HciShortRangeModeCmd *pHciShortRangeModeCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Short_Range_Mode.Command: Physical_Link_Handle = %d Short_Range_Mode = %s) To(%s)", 
        "ENV", 
        text,
        pHciShortRangeModeCmd->physicalLinkHandle,
        trace_ShortRangeMode(pHciShortRangeModeCmd->shortRangeMode),
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Local_Version_Information.Command -------------------------- */
void trace_HciReadLocalVersionInformationCmd(const char* text, const FsmContext* context, const HciReadLocalVersionInformationCmd *pHciReadLocalVersionInformationCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Local_Version_Information.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Local_Supported_Commands.Command -------------------------- */
void trace_HciReadLocalSupportedCommandsCmd(const char* text, const FsmContext* context, const HciReadLocalSupportedCommandsCmd *pHciReadLocalSupportedCommandsCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Local_Supported_Commands.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Data_Block_Size.Command -------------------------- */
void trace_HciReadDataBlockSizeCmd(const char* text, const FsmContext* context, const HciReadDataBlockSizeCmd *pHciReadDataBlockSizeCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Data_Block_Size.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Failed_Contact_Counter.Command -------------------------- */
void trace_HciReadFailedContactCounterCmd(const char* text, const FsmContext* context, const HciReadFailedContactCounterCmd *pHciReadFailedContactCounterCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Failed_Contact_Counter.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciReadFailedContactCounterCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Reset_Failed_Contact_Counter.Command -------------------------- */
void trace_HciResetFailedContactCounterCmd(const char* text, const FsmContext* context, const HciResetFailedContactCounterCmd *pHciResetFailedContactCounterCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Reset_Failed_Contact_Counter.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciResetFailedContactCounterCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Link_Quality.Command -------------------------- */
void trace_HciReadLinkQualityCmd(const char* text, const FsmContext* context, const HciReadLinkQualityCmd *pHciReadLinkQualityCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Link_Quality.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciReadLinkQualityCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_RSSI.Command -------------------------- */
void trace_HciReadRssiCmd(const char* text, const FsmContext* context, const HciReadRssiCmd *pHciReadRssiCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_RSSI.Command: Handle = %d) To(%s)", 
        "ENV", 
        text,
        pHciReadRssiCmd->handle,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Local_AMP_Info.Command -------------------------- */
void trace_HciReadLocalAmpInfoCmd(const char* text, const FsmContext* context, const HciReadLocalAmpInfoCmd *pHciReadLocalAmpInfoCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Local_AMP_Info.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Read_Local_AMP_ASSOC.Command -------------------------- */
void trace_HciReadLocalAmpAssocCmd(const char* text, const FsmContext* context, const HciReadLocalAmpAssocCmd *pHciReadLocalAmpAssocCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Local_AMP_ASSOC.Command: Physical_Link_Handle = %d Length_So_Far = %d Max_Remote_AMP_ASSOC_Length = %d) To(%s)", 
        "ENV", 
        text,
        pHciReadLocalAmpAssocCmd->physicalLinkHandle,
        pHciReadLocalAmpAssocCmd->lengthSoFar,
        pHciReadLocalAmpAssocCmd->maxRemoteAmpAssocLength,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Remote_AMP_ASSOC.Command -------------------------- */
void trace_HciWriteRemoteAmpAssocCmd(const char* text, const FsmContext* context, const HciWriteRemoteAmpAssocCmd *pHciWriteRemoteAmpAssocCmd)
{
    char *assocFragment_Str = trace_hci_Buffer(pHciWriteRemoteAmpAssocCmd->assocFragment.data,pHciWriteRemoteAmpAssocCmd->assocFragment.dataLen);
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Remote_AMP_ASSOC.Command: Physical_Link_Handle = %d Length_So_Far = %d Remaining_Length = %d Assoc_Fragment = %s) To(%s)", 
        "ENV", 
        text,
        pHciWriteRemoteAmpAssocCmd->physicalLinkHandle,
        pHciWriteRemoteAmpAssocCmd->lengthSoFar,
        pHciWriteRemoteAmpAssocCmd->remainingLength,
        assocFragment_Str,
        "PAL_MGR" 
    ));
    CsrPfree(assocFragment_Str);
}


/* -------------------------- HCI_Read_Loopback_Mode.Command -------------------------- */
void trace_HciReadLoopbackModeCmd(const char* text, const FsmContext* context, const HciReadLoopbackModeCmd *pHciReadLoopbackModeCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Read_Loopback_Mode.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Write_Loopback_Mode.Command -------------------------- */
void trace_HciWriteLoopbackModeCmd(const char* text, const FsmContext* context, const HciWriteLoopbackModeCmd *pHciWriteLoopbackModeCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Write_Loopback_Mode.Command: Loopback_Mode = %s) To(%s)", 
        "ENV", 
        text,
        trace_HciLoopbackMode(pHciWriteLoopbackModeCmd->loopbackMode),
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Enable_AMP_Test_Mode.Command -------------------------- */
void trace_HciEnableAmpTestModeCmd(const char* text, const FsmContext* context, const HciEnableAmpTestModeCmd *pHciEnableAmpTestModeCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Enable_AMP_Test_Mode.Command: Enable = %s) To(%s)", 
        "ENV", 
        text,
        trace_TestMode(pHciEnableAmpTestModeCmd->enable),
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Set_AMP_Transmit_Power_Test.Command -------------------------- */
void trace_HciSetAmpTransmitPowerTestCmd(const char* text, const FsmContext* context, const HciSetAmpTransmitPowerTestCmd *pHciSetAmpTransmitPowerTestCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Set_AMP_Transmit_Power_Test.Command: Power_Level = %d) To(%s)", 
        "ENV", 
        text,
        pHciSetAmpTransmitPowerTestCmd->powerLevel,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Enable_AMP_Receiver_Reports.Command -------------------------- */
void trace_HciEnableAmpReceiverReportsCmd(const char* text, const FsmContext* context, const HciEnableAmpReceiverReportsCmd *pHciEnableAmpReceiverReportsCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Enable_AMP_Receiver_Reports.Command: Enable = %d Interval = %d) To(%s)", 
        "ENV", 
        text,
        pHciEnableAmpReceiverReportsCmd->enable,
        pHciEnableAmpReceiverReportsCmd->interval,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Transmitter_AMP_Test.Command -------------------------- */
void trace_HciTransmitterAmpTestCmd(const char* text, const FsmContext* context, const HciTransmitterAmpTestCmd *pHciTransmitterAmpTestCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Transmitter_AMP_Test.Command: Test_Scenario = %d) To(%s)", 
        "ENV", 
        text,
        pHciTransmitterAmpTestCmd->testScenario,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Receiver_AMP_Test.Command -------------------------- */
void trace_HciReceiverAmpTestCmd(const char* text, const FsmContext* context, const HciReceiverAmpTestCmd *pHciReceiverAmpTestCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Receiver_AMP_Test.Command: Test_Scenario = %d) To(%s)", 
        "ENV", 
        text,
        pHciReceiverAmpTestCmd->testScenario,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_AMP_Test_End.Command -------------------------- */
void trace_HciAmpTestEndCmd(const char* text, const FsmContext* context, const HciAmpTestEndCmd *pHciAmpTestEndCmd)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_AMP_Test_End.Command:) To(%s)", 
        "ENV", 
        text,
        "PAL_MGR" 
    ));
}


/* -------------------------- HCI_Command_Complete.Event -------------------------- */
void trace_HciCommandCompleteEvtParam(const char* text, CsrUint8 numHciCommandPackets, const ReturnParameters *returnParameters)
{
    switch (returnParameters->commandCode) {
        case HCI_AMP_TEST_END_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s ampTestEndStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.ampTestEndStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_ENABLE_AMP_RECEIVER_REPORTS_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s enableAMPReceiverReportsStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.enableAMPReceiverReportsStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_ENABLE_AMP_TEST_MODE_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s testModeStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.testModeStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_FLUSH_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.flushReturn.status),
                returnParameters->hciReturnParam.flushReturn.handle,
                "ENV" 
            ));
            break;
        }


        case HCI_LOGICAL_LINK_CANCEL_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Physical_Link_Handle = %d Tx_Flow_Spec_ID = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.logicalLinkCancelReturn.status),
                returnParameters->hciReturnParam.logicalLinkCancelReturn.physicalLinkHandle,
                returnParameters->hciReturnParam.logicalLinkCancelReturn.txFlowSpecId,
                "ENV" 
            ));
            break;
        }


        case HCI_NO_OPERATION_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                "ENV" 
            ));
            break;
        }


        case HCI_READ_BEST_EFFORT_FLUSH_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Best_Effort_Flush_Timeout = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readBEFlushTimeoutReturn.status),
                returnParameters->hciReturnParam.readBEFlushTimeoutReturn.bestEffortFlushTimeout,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_CONNECTION_ACCEPT_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Conn_Accept_Timeout = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readConnectionAcceptTimeout.status),
                returnParameters->hciReturnParam.readConnectionAcceptTimeout.connAcceptTimeout,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_DATA_BLOCK_SIZE_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Max_ACL_Data_Packet_Length = %d Data_Block_Length = %d Total_Number_Of_Blocks = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readDataBlockSizeReturn.status),
                returnParameters->hciReturnParam.readDataBlockSizeReturn.maxAclDataPacketLength,
                returnParameters->hciReturnParam.readDataBlockSizeReturn.dataBlockLength,
                returnParameters->hciReturnParam.readDataBlockSizeReturn.totalNumberOfBlocks,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_FAILED_CONTACT_COUNTER_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d Failed_Contact_Counter = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readFailedContactCounterReturn.status),
                returnParameters->hciReturnParam.readFailedContactCounterReturn.handle,
                returnParameters->hciReturnParam.readFailedContactCounterReturn.failedContactCounter,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LINK_QUALITY_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d Link_Quality = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLinkQualityReturn.status),
                returnParameters->hciReturnParam.readLinkQualityReturn.handle,
                returnParameters->hciReturnParam.readLinkQualityReturn.linkQuality,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LINK_SUPERVISION_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d Link_Supervision_Timeout = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readTimeoutReturn.status),
                returnParameters->hciReturnParam.readTimeoutReturn.handle,
                returnParameters->hciReturnParam.readTimeoutReturn.linkSupervisionTimeout,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LOCAL_AMP_ASSOC_CODE: {
            char *assocFragment_Str = trace_hci_Buffer(returnParameters->hciReturnParam.readLocalAmpAssocReturn.assocFragment.data,returnParameters->hciReturnParam.readLocalAmpAssocReturn.assocFragment.dataLen);
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Physical_Link_Handle = %d Remaining_Length = %d Assoc_Fragment = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLocalAmpAssocReturn.status),
                returnParameters->hciReturnParam.readLocalAmpAssocReturn.physicalLinkHandle,
                returnParameters->hciReturnParam.readLocalAmpAssocReturn.remainingLength,
                assocFragment_Str,
                "ENV" 
            ));
            CsrPfree(assocFragment_Str);
            break;
        }


        case HCI_READ_LOCAL_AMP_INFO_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Amp_Status = %s Total_Bandwidth = %d Max_Guaranteed_Bandwidth = %d Min_Latency = %d Max_PDU_Size = %d Controller_Type = %s PAL_Capabilities = %d AMP_ASSOC_Length = %d Max_Flush_Timeout = %d Best_Effort_Flush_Timeout = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLocalAmpInfoReturn.status),
                trace_AmpStatus(returnParameters->hciReturnParam.readLocalAmpInfoReturn.ampStatus),
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.totalBandwidth,
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.maxGuaranteedBandwidth,
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.minLatency,
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.maxPduSize,
                trace_AmpControllerType(returnParameters->hciReturnParam.readLocalAmpInfoReturn.controllerType),
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.palCapabilities,
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.ampAssocLength,
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.maxFlushTimeout,
                returnParameters->hciReturnParam.readLocalAmpInfoReturn.bestEffortFlushTimeout,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LOCAL_SUPPORTED_COMMANDS_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s M = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLocalSupportedCommandsReturn.status),
                returnParameters->hciReturnParam.readLocalSupportedCommandsReturn.supportedCommands.m,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LOCAL_VERSION_INFORMATION_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s HCI_Version = %d HCI_Revision = %d PAL_Version = %d Manufacturer_Name = %d PAL_Subversion = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLocalVersionInformationReturn.status),
                returnParameters->hciReturnParam.readLocalVersionInformationReturn.hciVersion,
                returnParameters->hciReturnParam.readLocalVersionInformationReturn.hciRevision,
                returnParameters->hciReturnParam.readLocalVersionInformationReturn.palVersion,
                returnParameters->hciReturnParam.readLocalVersionInformationReturn.manufacturerName,
                returnParameters->hciReturnParam.readLocalVersionInformationReturn.palSubversion,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LOCATION_DATA_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Location_Domain_Aware = %s Location_Domain = %d Location_Domain_Options = %s Location_Options = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLocationDataReturn.status),
                trace_LocationDomainAware(returnParameters->hciReturnParam.readLocationDataReturn.locationDomainAware),
                returnParameters->hciReturnParam.readLocationDataReturn.locationDomain,
                trace_LocationDomainOptions(returnParameters->hciReturnParam.readLocationDataReturn.locationDomainOptions),
                trace_LocationOptions(returnParameters->hciReturnParam.readLocationDataReturn.locationOptions),
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Logical_Link_Accept_Timeout = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLogicalLinkAcceptTimeout.status),
                returnParameters->hciReturnParam.readLogicalLinkAcceptTimeout.logicalLinkAcceptTimeout,
                "ENV" 
            ));
            break;
        }


        case HCI_READ_LOOPBACK_MODE_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Loopback_Mode = %s readLoopbackReturn = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readLoopbackReturn.status),
                trace_HciLoopbackMode(returnParameters->hciReturnParam.readLoopbackReturn.loopbackMode),
                "ENV" 
            ));
            break;
        }


        case HCI_READ_RSSI_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d RSSI = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.readRSSIReturn.status),
                returnParameters->hciReturnParam.readRSSIReturn.handle,
                returnParameters->hciReturnParam.readRSSIReturn.rSSI,
                "ENV" 
            ));
            break;
        }


        case HCI_RESET_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s resetStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.resetStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_RESET_FAILED_CONTACT_COUNTER_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.resetFailedContactCounterReturn.status),
                returnParameters->hciReturnParam.resetFailedContactCounterReturn.handle,
                "ENV" 
            ));
            break;
        }


        case HCI_SET_EVENT_MASK_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s setEventMaskStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.setEventMaskStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_SET_EVENT_MASK_PAGE2_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s setEventMaskPage2Status = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.setEventMaskPage2Status),
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_BEST_EFFORT_FLUSH_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s writeBEFlushTimeoutReturn = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeBEFlushTimeoutReturn),
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s writeConnectionAcceptTimeoutStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeConnectionAcceptTimeoutStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_LINK_SUPERVISION_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Handle = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeTimeoutReturn.status),
                returnParameters->hciReturnParam.writeTimeoutReturn.handle,
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_LOCATION_DATA_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s writeLocationDataStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeLocationDataStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s writeLogicalLinkAcceptTimeout = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeLogicalLinkAcceptTimeout),
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_LOOPBACK_MODE_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s writeLoopbackStatus = %s) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeLoopbackStatus),
                "ENV" 
            ));
            break;
        }


        case HCI_WRITE_REMOTE_AMP_ASSOC_CODE: {
            sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Complete.Event: Num_HCI_Command_Packets = %d Command_Code = %s Status = %s Physical_Link_Handle = %d) To(%s)", 
                "PAL_MGR", 
                text,
                numHciCommandPackets,
                trace_HciOpcode(returnParameters->commandCode),
                trace_HciStatusCode(returnParameters->hciReturnParam.writeRemoteAmpAssocReturn.status),
                returnParameters->hciReturnParam.writeRemoteAmpAssocReturn.physicalLinkHandle,
                "ENV" 
            ));
            break;
        }


        default:
        {
             verify(TR_MSC, 0); /*lint !e774*/
             break;
        }

    }
}
/* -------------------------- HCI_Command_Status.Event -------------------------- */
void trace_HciCommandStatusEvtParam(const char* text, HciStatusCode status, CsrUint8 numHciCommandPackets, HciOpcode commandOpcode)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Command_Status.Event: Status = %s Num_HCI_Command_Packets = %d Command_Opcode = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        numHciCommandPackets,
        trace_HciOpcode(commandOpcode),
        "ENV" 
    ));
}


/* -------------------------- HCI_Hardware_Error.Event -------------------------- */
void trace_HciHardwareErrorEvtParam(const char* text, CsrUint8 hardwareCode)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Hardware_Error.Event: Hardware_Code = %d) To(%s)", 
        "PAL_MGR", 
        text,
        hardwareCode,
        "ENV" 
    ));
}


/* -------------------------- HCI_Flush_Occurred.Event -------------------------- */
void trace_HciFlushOccurredEvtParam(const char* text, CsrUint16 handle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Flush_Occurred.Event: Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        handle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Loopback_Command.Event -------------------------- */
void trace_HciLoopbackCommandEvtParam(const char* text)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Loopback_Command.Event:) To(%s)", 
        "PAL_MGR", 
        text,
        "ENV" 
    ));
}


/* -------------------------- HCI_Data_Buffer_Overflow.Event -------------------------- */
void trace_HciDataBufferOverflowEvtParam(const char* text, HciLinkType linkType)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Data_Buffer_Overflow.Event: Link_Type = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciLinkType(linkType),
        "ENV" 
    ));
}


/* -------------------------- HCI_QoS_Violation.Event -------------------------- */
void trace_HciQosViolationEvtParam(const char* text, CsrUint16 handle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_QoS_Violation.Event: Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        handle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Enhanced_Flush_Complete.Event -------------------------- */
void trace_HciEnhancedFlushCompleteEvtParam(const char* text, CsrUint16 handle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Enhanced_Flush_Complete.Event: Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        handle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Physical_Link_Complete.Event -------------------------- */
void trace_HciPhysicalLinkCompleteEvtParam(const char* text, HciStatusCode status, CsrUint8 physicalLinkHandle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Physical_Link_Complete.Event: Status = %s Physical_Link_Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        physicalLinkHandle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Channel_Select.Event -------------------------- */
void trace_HciChannelSelectEvtParam(const char* text, CsrUint8 physicalLinkHandle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Channel_Select.Event: Physical_Link_Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        physicalLinkHandle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Disconnect_Physical_Link_Complete.Event -------------------------- */
void trace_HciDisconnectPhysicalLinkCompleteEvtParam(const char* text, HciStatusCode status, CsrUint8 physicalLinkHandle, CsrUint8 reason)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Disconnect_Physical_Link_Complete.Event: Status = %s Physical_Link_Handle = %d Reason = %d) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        physicalLinkHandle,
        reason,
        "ENV" 
    ));
}


/* -------------------------- HCI_Physical_Link_Loss_Early_Warning.Event -------------------------- */
void trace_HciPhysicalLinkLossEarlyWarningEvtParam(const char* text, CsrUint8 physicalLinkHandle, LinkLossReasonCode linkLossReason)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Physical_Link_Loss_Early_Warning.Event: Physical_Link_Handle = %d Link_Loss_Reason = %s) To(%s)", 
        "PAL_MGR", 
        text,
        physicalLinkHandle,
        trace_LinkLossReasonCode(linkLossReason),
        "ENV" 
    ));
}


/* -------------------------- HCI_Physical_Link_Recovery.Event -------------------------- */
void trace_HciPhysicalLinkRecoveryEvtParam(const char* text, CsrUint8 physicalLinkHandle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Physical_Link_Recovery.Event: Physical_Link_Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        physicalLinkHandle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Logical_Link_Complete.Event -------------------------- */
void trace_HciLogicalLinkCompleteEvtParam(const char* text, HciStatusCode status, CsrUint16 logicalLinkHandle, CsrUint8 physicalLinkHandle, CsrUint8 txFlowSpecId)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Logical_Link_Complete.Event: Status = %s Logical_Link_Handle = %d Physical_Link_Handle = %d TX_Flow_Spec_ID = %d) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        logicalLinkHandle,
        physicalLinkHandle,
        txFlowSpecId,
        "ENV" 
    ));
}


/* -------------------------- HCI_Disconnect_Logical_Link_Complete.Event -------------------------- */
void trace_HciDisconnectLogicalLinkCompleteEvtParam(const char* text, HciStatusCode status, CsrUint16 logicalLinkHandle, CsrUint8 reason)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Disconnect_Logical_Link_Complete.Event: Status = %s Logical_Link_Handle = %d Reason = %d) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        logicalLinkHandle,
        reason,
        "ENV" 
    ));
}


/* -------------------------- HCI_Flow_Spec_Modify_Complete.Event -------------------------- */
void trace_HciFlowSpecModifyCompleteEvtParam(const char* text, HciStatusCode status, CsrUint16 handle)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Flow_Spec_Modify_Complete.Event: Status = %s Handle = %d) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        handle,
        "ENV" 
    ));
}


/* -------------------------- HCI_Number_Of_Completed_Data_Blocks.Event -------------------------- */
void trace_HciNumberOfCompletedDataBlocksEvtParam(const char* text, CsrUint16 totalNumDataBlocks, CsrUint8 numberOfHandles, CsrUint16 handle, CsrUint16 numberOfCompletedPackets, CsrUint16 numberOfCompletedBlocks)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Number_Of_Completed_Data_Blocks.Event: Total_Num_Data_Blocks = %d Number_Of_Handles = %d Handle = %d Number_Of_Completed_Packets = %d Number_Of_Completed_Blocks = %d) To(%s)", 
        "PAL_MGR", 
        text,
        totalNumDataBlocks,
        numberOfHandles,
        handle,
        numberOfCompletedPackets,
        numberOfCompletedBlocks,
        "ENV" 
    ));
}


/* -------------------------- HCI_Short_Range_Mode_Change_Complete.Event -------------------------- */
void trace_HciShortRangeModeChangeCompleteEvtParam(const char* text, HciStatusCode status, CsrUint8 physicalLinkHandle, ShortRangeMode shortRangeModeState)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Short_Range_Mode_Change_Complete.Event: Status = %s Physical_Link_Handle = %d Short_Range_Mode_State = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        physicalLinkHandle,
        trace_ShortRangeMode(shortRangeModeState),
        "ENV" 
    ));
}


/* -------------------------- HCI_AMP_Status_Change.Event -------------------------- */
void trace_HciAmpStatusChangeEvtParam(const char* text, HciStatusCode status, AmpStatus ampStatus)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_AMP_Status_Change.Event: Status = %s AMP_Status = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        trace_AmpStatus(ampStatus),
        "ENV" 
    ));
}


/* -------------------------- HCI_Generic_AMP_Link_Key.Notification -------------------------- */
void trace_HciGenericAmpLinkKeyNtParam(const char* text, LinkKeyType keyType)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:HCI_Generic_AMP_Link_Key.Notification: Key_Type = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_LinkKeyType(keyType),
        "ENV" 
    ));
}


/* -------------------------- AMP_Transmit_Power.Event -------------------------- */
void trace_AmpTransmitPowerEvtParam(const char* text, HciStatusCode status, PowerLevel powerLevel)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:AMP_Transmit_Power.Event: Status = %s Power_Level = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        trace_PowerLevel(powerLevel),
        "ENV" 
    ));
}


/* -------------------------- AMP_Receiver_Report.Event -------------------------- */
void trace_AmpReceiverReportEvtParam(const char* text, CsrUint8 ampReport)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:AMP_Receiver_Report.Event: AMP_REPORT = %d) To(%s)", 
        "PAL_MGR", 
        text,
        ampReport,
        "ENV" 
    ));
}


/* -------------------------- AMP_Start_Transmitter_Test.Event -------------------------- */
void trace_AmpStartTransmitterTestEvtParam(const char* text, HciStatusCode status, CsrUint8 powerLevel)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:AMP_Start_Transmitter_Test.Event: Status = %s Power_Level = %d) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        powerLevel,
        "ENV" 
    ));
}


/* -------------------------- AMP_Start_Receiver_Test.Event -------------------------- */
void trace_AmpStartReceiverTestEvtParam(const char* text, HciStatusCode status)
{
    sme_trace_msc((TR_MSC, "MSC MESSAGE :: From(%s) Event(%s:AMP_Start_Receiver_Test.Event: Status = %s) To(%s)", 
        "PAL_MGR", 
        text,
        trace_HciStatusCode(status),
        "ENV" 
    ));
}



#endif /* SME_TRACE_ENABLE */

